// Topic: Art & Literature — 70 questions (Wave 1 global classic, Wave 2 Indian/Malayalam focus)
export default [
  // ===== WAVE 1 — GLOBAL CLASSIC (35) =====
  // Easy (12)
  { d: 'easy', s: 'classic', q: 'Who painted the "Mona Lisa"?', o: ['Michelangelo', 'Leonardo da Vinci', 'Raphael', 'Donatello'], c: 1, e: 'Leonardo da Vinci painted the Mona Lisa.' },
  { d: 'easy', s: 'classic', q: 'Who wrote the tragedy "Romeo and Juliet"?', o: ['Charles Dickens', 'William Shakespeare', 'John Milton', 'Geoffrey Chaucer'], c: 1, e: 'Shakespeare wrote Romeo and Juliet.' },
  { d: 'easy', s: 'classic', q: 'The swirling night sky painting "The Starry Night" was created by whom?', o: ['Claude Monet', 'Vincent van Gogh', 'Paul Cézanne', 'Edgar Degas'], c: 1, e: 'Van Gogh painted The Starry Night in 1889.' },
  { d: 'easy', s: 'classic', q: 'Who wrote "The Lord of the Rings"?', o: ['C.S. Lewis', 'J.R.R. Tolkien', 'George R.R. Martin', 'Philip Pullman'], c: 1, e: 'Tolkien wrote the epic fantasy.' },
  { d: 'easy', s: 'classic', q: 'Pablo Picasso co-founded which art movement?', o: ['Impressionism', 'Cubism', 'Surrealism', 'Baroque'], c: 1, e: 'Picasso pioneered Cubism with Braque.' },
  { d: 'easy', s: 'classic', q: 'Who sculpted the famous Renaissance statue "David"?', o: ['Bernini', 'Michelangelo', 'Rodin', 'Donatello'], c: 1, e: 'Michelangelo sculpted David in marble.' },
  { d: 'easy', s: 'classic', q: 'Who wrote "Pride and Prejudice"?', o: ['Charlotte Brontë', 'Jane Austen', 'Emily Dickinson', 'Mary Shelley'], c: 1, e: 'Jane Austen wrote Pride and Prejudice.' },
  { d: 'easy', s: 'classic', q: 'Who painted the ceiling of the Sistine Chapel?', o: ['Raphael', 'Michelangelo', 'Titian', 'Caravaggio'], c: 1, e: 'Michelangelo painted the Sistine ceiling.' },
  { d: 'easy', s: 'classic', q: 'The dystopian novel "1984" was written by whom?', o: ['Aldous Huxley', 'George Orwell', 'Ray Bradbury', 'H.G. Wells'], c: 1, e: 'George Orwell wrote 1984.' },
  { d: 'easy', s: 'classic', q: 'The anguished painting "The Scream" was created by whom?', o: ['Gustav Klimt', 'Edvard Munch', 'Salvador Dalí', 'Henri Matisse'], c: 1, e: 'Edvard Munch painted The Scream.' },
  { d: 'easy', s: 'classic', q: 'Which Shakespeare play features a melancholy Prince of Denmark?', o: ['Macbeth', 'Hamlet', 'Othello', 'King Lear'], c: 1, e: 'Hamlet is the Prince of Denmark.' },
  { d: 'easy', s: 'classic', q: 'Who is the author of the "Harry Potter" book series?', o: ['Suzanne Collins', 'J.K. Rowling', 'Roald Dahl', 'Philip Pullman'], c: 1, e: 'J.K. Rowling wrote Harry Potter.' },
  // Medium (12)
  { d: 'medium', s: 'classic', q: 'Salvador Dalí is most associated with which art movement?', o: ['Cubism', 'Surrealism', 'Realism', 'Pop Art'], c: 1, e: 'Dalí was a leading Surrealist.' },
  { d: 'medium', s: 'classic', q: 'Who wrote the epic novel "War and Peace"?', o: ['Fyodor Dostoevsky', 'Leo Tolstoy', 'Anton Chekhov', 'Ivan Turgenev'], c: 1, e: 'Tolstoy wrote War and Peace.' },
  { d: 'medium', s: 'classic', q: 'In which museum is the "Mona Lisa" displayed?', o: ['The Prado', 'The Louvre', 'The Uffizi', 'The Met'], c: 1, e: 'The Mona Lisa hangs in the Louvre, Paris.' },
  { d: 'medium', s: 'classic', q: 'Which novel famously opens with "Call me Ishmael"?', o: ['Moby-Dick', 'The Old Man and the Sea', 'Treasure Island', 'Robinson Crusoe'], c: 0, e: 'Moby-Dick by Herman Melville opens this way.' },
  { d: 'medium', s: 'classic', q: 'Who wrote "Crime and Punishment"?', o: ['Leo Tolstoy', 'Fyodor Dostoevsky', 'Nikolai Gogol', 'Boris Pasternak'], c: 1, e: 'Dostoevsky wrote Crime and Punishment.' },
  { d: 'medium', s: 'classic', q: 'Claude Monet is a founder of which art movement?', o: ['Impressionism', 'Expressionism', 'Cubism', 'Fauvism'], c: 0, e: 'Monet helped launch Impressionism.' },
  { d: 'medium', s: 'classic', q: 'Who wrote "The Great Gatsby"?', o: ['Ernest Hemingway', 'F. Scott Fitzgerald', 'John Steinbeck', 'William Faulkner'], c: 1, e: 'F. Scott Fitzgerald wrote The Great Gatsby.' },
  { d: 'medium', s: 'classic', q: 'Shakespeare\'s plays were famously staged at which London theatre?', o: ['The Globe', 'The Old Vic', 'Drury Lane', 'The Rose'], c: 0, e: 'The Globe Theatre hosted his plays.' },
  { d: 'medium', s: 'classic', q: 'The artist Frida Kahlo was from which country?', o: ['Spain', 'Mexico', 'Argentina', 'Cuba'], c: 1, e: 'Frida Kahlo was a Mexican painter.' },
  { d: 'medium', s: 'classic', q: 'Who wrote the haunting poem "The Raven"?', o: ['Walt Whitman', 'Edgar Allan Poe', 'Robert Frost', 'Emily Dickinson'], c: 1, e: 'Edgar Allan Poe wrote The Raven.' },
  { d: 'medium', s: 'classic', q: 'Picasso\'s anti-war mural "Guernica" depicts the bombing of a town in which country?', o: ['France', 'Spain', 'Italy', 'Germany'], c: 1, e: 'It protests the bombing of Guernica, Spain.' },
  { d: 'medium', s: 'classic', q: 'The dystopian world with "Big Brother" appears in which novel?', o: ['Brave New World', '1984', 'Fahrenheit 451', 'Animal Farm'], c: 1, e: 'Big Brother watches in Orwell\'s 1984.' },
  // Hard (11)
  { d: 'hard', s: 'classic', q: 'Who wrote "One Hundred Years of Solitude"?', o: ['Jorge Luis Borges', 'Gabriel García Márquez', 'Pablo Neruda', 'Mario Vargas Llosa'], c: 1, e: 'García Márquez wrote the magical-realist classic.' },
  { d: 'hard', s: 'classic', q: 'Who wrote the modernist novel "Ulysses"?', o: ['Virginia Woolf', 'James Joyce', 'Marcel Proust', 'Franz Kafka'], c: 1, e: 'James Joyce wrote Ulysses.' },
  { d: 'hard', s: 'classic', q: 'The "Dada" art movement arose largely in reaction to which event?', o: ['The French Revolution', 'World War I', 'The Cold War', 'The Great Depression'], c: 1, e: 'Dada emerged amid the horrors of WWI.' },
  { d: 'hard', s: 'classic', q: 'Salvador Dalí\'s melting-clocks painting is titled what?', o: ['The Persistence of Memory', 'The Elephants', 'Swans Reflecting Elephants', 'Galatea of the Spheres'], c: 0, e: 'The Persistence of Memory features drooping clocks.' },
  { d: 'hard', s: 'classic', q: 'Who wrote the influential modernist poem "The Waste Land"?', o: ['W.B. Yeats', 'T.S. Eliot', 'Ezra Pound', 'W.H. Auden'], c: 1, e: 'T.S. Eliot published The Waste Land in 1922.' },
  { d: 'hard', s: 'classic', q: 'Which Renaissance artist painted "The Birth of Venus"?', o: ['Sandro Botticelli', 'Titian', 'Raphael', 'Caravaggio'], c: 0, e: 'Botticelli painted The Birth of Venus.' },
  { d: 'hard', s: 'classic', q: 'Who wrote the early novel "Don Quixote"?', o: ['Miguel de Cervantes', 'Lope de Vega', 'Dante Alighieri', 'Voltaire'], c: 0, e: 'Cervantes wrote Don Quixote.' },
  { d: 'hard', s: 'classic', q: 'A figure of speech comparing two things using "like" or "as" is called a what?', o: ['Metaphor', 'Simile', 'Hyperbole', 'Personification'], c: 1, e: 'A simile uses "like" or "as".' },
  { d: 'hard', s: 'classic', q: 'Who wrote the landmark African novel "Things Fall Apart"?', o: ['Wole Soyinka', 'Chinua Achebe', 'Ngugi wa Thiong\'o', 'Ben Okri'], c: 1, e: 'Chinua Achebe wrote Things Fall Apart.' },
  { d: 'hard', s: 'classic', q: 'The prestigious Booker Prize is awarded for excellence in what?', o: ['Poetry', 'Fiction (a novel)', 'Drama', 'Journalism'], c: 1, e: 'The Booker honors a work of fiction.' },
  { d: 'hard', s: 'classic', q: 'Which artist is famous for soup-can prints and the Pop Art movement?', o: ['Roy Lichtenstein', 'Andy Warhol', 'Jackson Pollock', 'Jeff Koons'], c: 1, e: 'Andy Warhol epitomized Pop Art.' },

  // ===== WAVE 2 — INDIAN / MALAYALAM FOCUS (35) =====
  // Easy (12)
  { d: 'easy', s: 'classic', q: 'Who wrote the Booker-winning novel "The God of Small Things"?', o: ['Kiran Desai', 'Arundhati Roy', 'Anita Desai', 'Jhumpa Lahiri'], c: 1, e: 'Arundhati Roy wrote it, set in Kerala.' },
  { d: 'easy', s: 'classic', q: 'Author Ruskin Bond is best known for stories set where?', o: ['Mumbai slums', 'The Himalayan hills', 'Rajasthan deserts', 'Kerala backwaters'], c: 1, e: 'Bond\'s tales are set in the hills around Mussoorie.' },
  { d: 'easy', s: 'classic', q: 'R.K. Narayan set many of his stories in which fictional town?', o: ['Malgudi', 'Champaner', 'Shanti Nagar', 'Devgarh'], c: 0, e: 'Malgudi is Narayan\'s beloved fictional town.' },
  { d: 'easy', s: 'classic', q: 'Vaikom Muhammad Basheer was a celebrated writer in which language?', o: ['Tamil', 'Malayalam', 'Kannada', 'Telugu'], c: 1, e: 'Basheer is a giant of Malayalam literature.' },
  { d: 'easy', s: 'classic', q: 'Rabindranath Tagore won the Nobel Prize in which field?', o: ['Peace', 'Literature', 'Physics', 'Economics'], c: 1, e: 'Tagore won the 1913 Literature Nobel.' },
  { d: 'easy', s: 'classic', q: 'Rabindranath Tagore wrote which national anthem?', o: ['Vande Mataram', 'Jana Gana Mana', 'Saare Jahan Se Achha', 'Sayare'], c: 1, e: 'Tagore penned India\'s anthem Jana Gana Mana.' },
  { d: 'easy', s: 'classic', q: 'The epic "Ramayana" is traditionally attributed to which sage?', o: ['Ved Vyasa', 'Valmiki', 'Tulsidas', 'Kalidasa'], c: 1, e: 'Sage Valmiki composed the Ramayana.' },
  { d: 'easy', s: 'classic', q: 'M.T. Vasudevan Nair is a legendary figure in which literature?', o: ['Bengali', 'Malayalam', 'Marathi', 'Hindi'], c: 1, e: 'MT is a towering Malayalam writer.' },
  { d: 'easy', s: 'classic', q: 'Who wrote the novel "Midnight\'s Children"?', o: ['Vikram Seth', 'Salman Rushdie', 'Amitav Ghosh', 'Rohinton Mistry'], c: 1, e: 'Salman Rushdie wrote Midnight\'s Children.' },
  { d: 'easy', s: 'classic', q: 'The "Sahitya Akademi" is India\'s national academy of what?', o: ['Music', 'Letters (literature)', 'Dance', 'Cinema'], c: 1, e: 'It promotes Indian literature.' },
  { d: 'easy', s: 'classic', q: 'Basheer\'s famous work "Pathummayude Aadu" is in which language?', o: ['Hindi', 'Malayalam', 'Tamil', 'Urdu'], c: 1, e: 'It is a beloved Malayalam novel.' },
  { d: 'easy', s: 'classic', q: 'Which collection of poems won Tagore the Nobel Prize?', o: ['Gitanjali', 'Gora', 'Kabuliwala', 'The Home and the World'], c: 0, e: 'Gitanjali ("Song Offerings") won the Nobel.' },
  // Medium (12)
  { d: 'medium', s: 'classic', q: 'Tagore won the Nobel Prize in Literature in which year?', o: ['1901', '1913', '1925', '1930'], c: 1, e: 'He won in 1913, the first non-European laureate.' },
  { d: 'medium', s: 'classic', q: 'The Jnanpith Award is India\'s highest honor in which field?', o: ['Science', 'Literature', 'Cinema', 'Public service'], c: 1, e: 'The Jnanpith honors literary achievement.' },
  { d: 'medium', s: 'classic', q: 'The classic Malayalam novel "Chemmeen" was written by whom?', o: ['Thakazhi Sivasankara Pillai', 'M.T. Vasudevan Nair', 'O.V. Vijayan', 'Basheer'], c: 0, e: 'Thakazhi wrote Chemmeen, set among fisherfolk.' },
  { d: 'medium', s: 'classic', q: 'Arundhati Roy won the Booker Prize in which year?', o: ['1995', '1997', '2001', '2008'], c: 1, e: 'The God of Small Things won the 1997 Booker.' },
  { d: 'medium', s: 'classic', q: 'Salman Rushdie\'s "Midnight\'s Children" won which major award?', o: ['Nobel', 'Booker Prize', 'Pulitzer', 'Jnanpith'], c: 1, e: 'It won the Booker (and "Booker of Bookers").' },
  { d: 'medium', s: 'classic', q: 'Which painter is the key figure of the Bengal School of Art?', o: ['Raja Ravi Varma', 'Abanindranath Tagore', 'M.F. Husain', 'Jamini Roy'], c: 1, e: 'Abanindranath Tagore led the Bengal School.' },
  { d: 'medium', s: 'classic', q: 'Kamala Das, who wrote in English and Malayalam, used which pen name?', o: ['Madhavikutty', 'Lalithambika', 'Sugathakumari', 'Balamani Amma'], c: 0, e: 'In Malayalam she wrote as Madhavikutty.' },
  { d: 'medium', s: 'classic', q: 'The collection of Kerala legends "Aithihyamala" was compiled by whom?', o: ['Kottarathil Sankunni', 'Kumaran Asan', 'Vallathol', 'Ulloor'], c: 0, e: 'Kottarathil Sankunni compiled the Aithihyamala.' },
  { d: 'medium', s: 'classic', q: 'Who wrote the Booker-winning novel "The White Tiger"?', o: ['Aravind Adiga', 'Amitav Ghosh', 'Kiran Desai', 'Vikram Chandra'], c: 0, e: 'Aravind Adiga won the 2008 Booker.' },
  { d: 'medium', s: 'classic', q: 'Painter Raja Ravi Varma is famous for depicting what in a realistic European style?', o: ['Abstract shapes', 'Hindu gods and Indian themes', 'Landscapes only', 'Still life'], c: 1, e: 'He brought Indian mythology to oil painting.' },
  { d: 'medium', s: 'classic', q: 'Which Indian poet-lyricist won the Jnanpith and wrote many Malayalam film songs?', o: ['O.N.V. Kurup', 'Vairamuthu', 'Gulzar', 'Javed Akhtar'], c: 0, e: 'O.N.V. Kurup was a Jnanpith-winning poet.' },
  { d: 'medium', s: 'classic', q: 'Vikram Seth\'s sprawling novel about 1950s India is titled what?', o: ['A Suitable Boy', 'The Golden Gate', 'An Equal Music', 'Two Lives'], c: 0, e: 'A Suitable Boy is his famous epic.' },
  // Hard (11)
  { d: 'hard', s: 'classic', q: 'Which work is widely regarded as the first Malayalam novel?', o: ['Indulekha', 'Chemmeen', 'Khasakkinte Itihasam', 'Naalukettu'], c: 0, e: 'O. Chandu Menon\'s "Indulekha" (1889) is considered the first.' },
  { d: 'hard', s: 'classic', q: 'Thunchaththu Ezhuthachan is revered as the father of which language/literature?', o: ['Tamil', 'Malayalam', 'Kannada', 'Telugu'], c: 1, e: 'He is called the father of Malayalam.' },
  { d: 'hard', s: 'classic', q: '"Randamoozham", retelling the Mahabharata through Bhima, was written by whom?', o: ['M.T. Vasudevan Nair', 'O.V. Vijayan', 'Basheer', 'Thakazhi'], c: 0, e: 'MT wrote Randamoozham (Second Turn).' },
  { d: 'hard', s: 'classic', q: 'Vallathol Narayana Menon founded which famous arts institution?', o: ['Kerala Kalamandalam', 'Sahitya Akademi', 'Sangeet Natak Akademi', 'Lalit Kala Akademi'], c: 0, e: 'Vallathol founded the Kerala Kalamandalam.' },
  { d: 'hard', s: 'classic', q: 'M.T. Vasudevan Nair\'s acclaimed debut novel is titled what?', o: ['Naalukettu', 'Asuravithu', 'Kaalam', 'Manju'], c: 0, e: 'Naalukettu was MT\'s debut novel.' },
  { d: 'hard', s: 'classic', q: 'O.V. Vijayan\'s landmark modernist Malayalam novel is titled what?', o: ['Khasakkinte Itihasam', 'Chemmeen', 'Indulekha', 'Balyakalasakhi'], c: 0, e: 'Khasakkinte Itihasam (The Legends of Khasak) was groundbreaking.' },
  { d: 'hard', s: 'classic', q: 'The International Booker Prize 2022 went to which Hindi novel (in translation)?', o: ['Tomb of Sand', 'The Plague Upon Us', 'The Adivasi Will Not Dance', 'Ghachar Ghochar'], c: 0, e: 'Geetanjali Shree\'s "Tomb of Sand" won.' },
  { d: 'hard', s: 'classic', q: 'Kumaran Asan, a celebrated Malayalam poet, is linked to which era?', o: ['The Kerala literary renaissance', 'The Bhakti movement', 'The Sangam age', 'The colonial chronicles'], c: 0, e: 'Asan was a romantic poet of Kerala\'s renaissance.' },
  { d: 'hard', s: 'classic', q: 'Which artist of the Progressive Artists\' Group became one of India\'s most famous painters?', o: ['M.F. Husain', 'Nandalal Bose', 'Amrita Sher-Gil', 'Raja Ravi Varma'], c: 0, e: 'M.F. Husain was a leading modern Indian painter.' },
  { d: 'hard', s: 'classic', q: 'Basheer\'s tender novella "Balyakalasakhi" deals with which theme?', o: ['War', 'Childhood love', 'Politics', 'Religion only'], c: 1, e: 'It is a poignant tale of childhood sweethearts.' },
  { d: 'hard', s: 'classic', q: 'The Sangam-era Tamil classic "Thirukkural" was authored by whom?', o: ['Thiruvalluvar', 'Ilango Adigal', 'Kambar', 'Avvaiyar'], c: 0, e: 'Thiruvalluvar wrote the Thirukkural.' },
];
