// Topic: Food & Drink — 70 questions (35 classic + 35 Indian/Malayali cultural)
export default [
  // ===== SET A — CLASSIC / GLOBAL (35) =====
  // Easy (12)
  { d: 'easy', s: 'classic', q: 'Sushi is a dish that originated in which country?', o: ['China', 'Japan', 'Thailand', 'Korea'], c: 1, e: 'Sushi originated in Japan.' },
  { d: 'easy', s: 'classic', q: 'What is the main ingredient in guacamole?', o: ['Tomato', 'Avocado', 'Cucumber', 'Pea'], c: 1, e: 'Guacamole is made primarily from avocado.' },
  { d: 'easy', s: 'classic', q: 'Pizza is traditionally associated with which country?', o: ['Greece', 'Italy', 'Spain', 'France'], c: 1, e: 'Pizza originated in Italy.' },
  { d: 'easy', s: 'classic', q: 'Which fruit is most commonly used to make wine?', o: ['Apple', 'Grape', 'Cherry', 'Plum'], c: 1, e: 'Wine is fermented from grapes.' },
  { d: 'easy', s: 'classic', q: 'Espresso is a concentrated form of which beverage?', o: ['Tea', 'Coffee', 'Cocoa', 'Juice'], c: 1, e: 'Espresso is brewed coffee made under pressure.' },
  { d: 'easy', s: 'classic', q: 'Croissants are most associated with which country\'s cuisine?', o: ['Germany', 'France', 'Belgium', 'Italy'], c: 1, e: 'The flaky croissant is a French bakery staple.' },
  { d: 'easy', s: 'classic', q: 'Tofu is made from which plant?', o: ['Soybeans', 'Lentils', 'Peanuts', 'Corn'], c: 0, e: 'Tofu is curdled soybean milk.' },
  { d: 'easy', s: 'classic', q: 'Hummus is a dip made mainly from which legume?', o: ['Black beans', 'Chickpeas', 'Kidney beans', 'Peas'], c: 1, e: 'Hummus is blended chickpeas with tahini.' },
  { d: 'easy', s: 'classic', q: 'Cheddar is a type of what?', o: ['Bread', 'Cheese', 'Wine', 'Sauce'], c: 1, e: 'Cheddar is a popular firm cheese.' },
  { d: 'easy', s: 'classic', q: 'Tacos are a traditional dish of which country?', o: ['Spain', 'Mexico', 'Peru', 'Brazil'], c: 1, e: 'Tacos are iconic Mexican street food.' },
  { d: 'easy', s: 'classic', q: 'Basmati is a famous variety of what?', o: ['Wheat', 'Rice', 'Lentil', 'Millet'], c: 1, e: 'Basmati is an aromatic long-grain rice.' },
  { d: 'easy', s: 'classic', q: 'Which spice is the most expensive in the world by weight?', o: ['Vanilla', 'Saffron', 'Cardamom', 'Cinnamon'], c: 1, e: 'Saffron threads are hand-harvested, making it costly.' },
  // Medium (12)
  { d: 'medium', s: 'classic', q: 'A Margherita pizza is topped with tomato, basil and which cheese?', o: ['Cheddar', 'Mozzarella', 'Parmesan', 'Feta'], c: 1, e: 'Mozzarella tops the classic Margherita.' },
  { d: 'medium', s: 'classic', q: 'Paella is a famous rice dish from which country?', o: ['Italy', 'Spain', 'Portugal', 'Greece'], c: 1, e: 'Paella hails from Valencia, Spain.' },
  { d: 'medium', s: 'classic', q: 'Sashimi consists of thinly sliced raw what?', o: ['Beef', 'Fish', 'Vegetables', 'Tofu'], c: 1, e: 'Sashimi is fresh raw fish or seafood.' },
  { d: 'medium', s: 'classic', q: 'Genuine Champagne must come from which region of France?', o: ['Bordeaux', 'Champagne', 'Burgundy', 'Provence'], c: 1, e: 'Only sparkling wine from Champagne earns the name.' },
  { d: 'medium', s: 'classic', q: 'Which spirit is the base of a classic Mojito?', o: ['Vodka', 'Rum', 'Gin', 'Tequila'], c: 1, e: 'A Mojito uses white rum, mint and lime.' },
  { d: 'medium', s: 'classic', q: 'Tiramisu is a layered dessert from which country?', o: ['France', 'Italy', 'Austria', 'Greece'], c: 1, e: 'Tiramisu is a coffee-flavored Italian dessert.' },
  { d: 'medium', s: 'classic', q: 'Wasabi is the spicy green paste typically served with what?', o: ['Pasta', 'Sushi', 'Curry', 'Tacos'], c: 1, e: 'Wasabi accompanies sushi and sashimi.' },
  { d: 'medium', s: 'classic', q: 'Marzipan is a sweet paste made mainly from which nut?', o: ['Walnut', 'Almond', 'Cashew', 'Hazelnut'], c: 1, e: 'Marzipan is ground almonds and sugar.' },
  { d: 'medium', s: 'classic', q: 'A sommelier is an expert in what?', o: ['Cheese', 'Wine', 'Bread', 'Chocolate'], c: 1, e: 'A sommelier specializes in wine service.' },
  { d: 'medium', s: 'classic', q: 'Pho is a fragrant noodle soup from which country?', o: ['Thailand', 'Vietnam', 'China', 'Japan'], c: 1, e: 'Pho is Vietnam\'s signature noodle soup.' },
  { d: 'medium', s: 'classic', q: 'Feta cheese is traditionally associated with which country?', o: ['Italy', 'Greece', 'Turkey', 'France'], c: 1, e: 'Feta is a brined Greek cheese.' },
  { d: 'medium', s: 'classic', q: 'The famous Michelin restaurant guide was originally published by what kind of company?', o: ['Tire company', 'Airline', 'Newspaper', 'Hotel chain'], c: 0, e: 'Michelin tires created the guide to encourage driving.' },
  // Hard (11)
  { d: 'hard', s: 'classic', q: '"Umami" is recognized as which of the five basic tastes?', o: ['The sour taste', 'The savory fifth taste', 'A type of sweetness', 'A spice level'], c: 1, e: 'Umami is the savory taste from glutamates.' },
  { d: 'hard', s: 'classic', q: 'A Negroni cocktail is gin, sweet vermouth and which bitter liqueur?', o: ['Aperol', 'Campari', 'Cointreau', 'Chartreuse'], c: 1, e: 'Campari gives the Negroni its bitter edge.' },
  { d: 'hard', s: 'classic', q: 'Which country is famously the highest coffee consumer per capita?', o: ['Italy', 'Finland', 'Brazil', 'USA'], c: 1, e: 'Finland tops per-capita coffee consumption.' },
  { d: 'hard', s: 'classic', q: 'Roquefort, a famous blue cheese, is made from which animal\'s milk?', o: ['Cow', 'Sheep', 'Goat', 'Buffalo'], c: 1, e: 'Roquefort is a sheep\'s-milk blue cheese.' },
  { d: 'hard', s: 'classic', q: 'Sourdough bread rises using what leavening?', o: ['Baking soda', 'Wild yeast and bacteria', 'Commercial yeast only', 'Egg whites'], c: 1, e: 'A natural starter culture ferments sourdough.' },
  { d: 'hard', s: 'classic', q: 'The spicy heat of chili peppers is measured in which units?', o: ['Calories', 'Scoville units', 'Brix', 'Proof'], c: 1, e: 'The Scoville scale rates chili pungency.' },
  { d: 'hard', s: 'classic', q: 'Authentic balsamic vinegar comes from which Italian city?', o: ['Modena', 'Milan', 'Rome', 'Venice'], c: 0, e: 'Traditional balsamic is aged in Modena.' },
  { d: 'hard', s: 'classic', q: 'The "sous vide" cooking method involves cooking food how?', o: ['Over open flame', 'Sealed in a bag in a water bath', 'In hot oil', 'Smoked slowly'], c: 1, e: 'Sous vide cooks vacuum-sealed food at precise temperatures.' },
  { d: 'hard', s: 'classic', q: 'Prized Kobe beef comes from which country?', o: ['Argentina', 'Japan', 'USA', 'Australia'], c: 1, e: 'Kobe beef is a wagyu beef from Japan.' },
  { d: 'hard', s: 'classic', q: 'A classic béchamel sauce is built from milk and what base?', o: ['Egg yolks', 'A roux of butter and flour', 'Cornstarch slurry', 'Cream and cheese'], c: 1, e: 'Béchamel is one of the French "mother sauces".' },
  { d: 'hard', s: 'classic', q: 'The fermented Korean side dish of spiced vegetables is called what?', o: ['Miso', 'Kimchi', 'Natto', 'Tempeh'], c: 1, e: 'Kimchi is Korea\'s staple fermented dish.' },

  // ===== SET B — INDIAN / MALAYALI CULTURAL (35) =====
  // Easy (12)
  { d: 'easy', s: 'cultural', q: 'Puttu is traditionally steamed in which vessel?', o: ['Tawa', 'Puttu Kudam', 'Appachatti', 'Uruli'], c: 1, e: 'A "Puttu Kudam" cylinder steams the rice-and-coconut dish.' },
  { d: 'easy', s: 'cultural', q: 'The grand vegetarian Onam feast is called what?', o: ['Sadya', 'Thali', 'Bhog', 'Langar'], c: 0, e: 'The Onam Sadya is served on a banana leaf.' },
  { d: 'easy', s: 'cultural', q: 'Which Indian city is especially famous for the "Kathi Roll"?', o: ['Mumbai', 'Kolkata', 'Delhi', 'Chennai'], c: 1, e: 'The Kathi Roll is a Kolkata street-food icon.' },
  { d: 'easy', s: 'cultural', q: 'Biryani from which city is most hotly debated as "the best"?', o: ['Lucknow', 'Hyderabad', 'Kolkata', 'Delhi'], c: 1, e: 'Hyderabadi biryani is a perennial favorite.' },
  { d: 'easy', s: 'cultural', q: 'Appam is most classically paired with which dish?', o: ['Sambar', 'Stew', 'Rasam', 'Chutney'], c: 1, e: 'Soft appam is enjoyed with vegetable or meat stew.' },
  { d: 'easy', s: 'cultural', q: 'Karimeen, used in a famous Kerala fish dish, is which fish?', o: ['Mackerel', 'Pearl spot', 'Tuna', 'Sardine'], c: 1, e: 'Karimeen (pearl spot) thrives in Kerala backwaters.' },
  { d: 'easy', s: 'cultural', q: 'Avial, a creamy mixed-vegetable dish, belongs to which cuisine?', o: ['Punjabi', 'Kerala', 'Gujarati', 'Bengali'], c: 1, e: 'Avial is a Sadya staple from Kerala.' },
  { d: 'easy', s: 'cultural', q: 'Masala dosa originates from which part of India?', o: ['North India', 'South India', 'East India', 'Northeast India'], c: 1, e: 'The crispy dosa is a South Indian classic.' },
  { d: 'easy', s: 'cultural', q: 'The Onam Sadya is traditionally served on what?', o: ['Steel plate', 'Banana leaf', 'Clay pot', 'Wooden tray'], c: 1, e: 'Sadya is eaten off a fresh plantain leaf.' },
  { d: 'easy', s: 'cultural', q: 'Pazham Pori, a popular Kerala snack, is a fritter made of what?', o: ['Potato', 'Banana (plantain)', 'Onion', 'Jackfruit'], c: 1, e: 'Ripe plantain slices are battered and fried.' },
  { d: 'easy', s: 'cultural', q: 'Sambar is most commonly eaten with which foods?', o: ['Naan and roti', 'Idli and dosa', 'Pasta', 'Bread'], c: 1, e: 'Sambar accompanies South Indian breakfasts.' },
  { d: 'easy', s: 'cultural', q: '"Kappa" in Malayalam refers to which food?', o: ['Tapioca', 'Banana', 'Rice', 'Yam'], c: 0, e: 'Kappa is boiled tapioca, often eaten with fish curry.' },
  // Medium (12)
  { d: 'medium', s: 'cultural', q: 'Kerala Porotta (Malabar paratha) is made primarily from which flour?', o: ['Whole wheat', 'Maida (refined flour)', 'Rice flour', 'Gram flour'], c: 1, e: 'The flaky, layered porotta uses maida.' },
  { d: 'medium', s: 'cultural', q: 'Which city is the home of the famous street snack "Vada Pav"?', o: ['Mumbai', 'Pune', 'Surat', 'Nagpur'], c: 0, e: 'Vada Pav is Mumbai\'s beloved street food.' },
  { d: 'medium', s: 'cultural', q: 'Hyderabadi biryani is traditionally cooked using which method?', o: ['Tandoor', 'Dum (slow-sealed)', 'Deep frying', 'Steaming'], c: 1, e: 'Dum cooking seals the pot to trap aromas.' },
  { d: 'medium', s: 'cultural', q: '"Payasam" is which kind of Kerala dish?', o: ['Spicy curry', 'Sweet pudding (kheer)', 'Pickle', 'Bread'], c: 1, e: 'Payasam is a sweet, milky dessert.' },
  { d: 'medium', s: 'cultural', q: 'Filter coffee is most strongly associated with which region of India?', o: ['North India', 'South India', 'West India', 'Northeast India'], c: 1, e: 'South Indian filter coffee is a daily ritual.' },
  { d: 'medium', s: 'cultural', q: 'The idli/dosa batter is fermented from rice and which lentil?', o: ['Toor dal', 'Urad dal', 'Chana dal', 'Moong dal'], c: 1, e: 'Urad dal and rice ferment to make the batter.' },
  { d: 'medium', s: 'cultural', q: 'Which classic combo pairs boiled tapioca with a spicy fish curry?', o: ['Kappa and Meen Curry', 'Idli and Sambar', 'Appam and Stew', 'Puttu and Kadala'], c: 0, e: 'Kappa and Meen Curry is a Kerala favorite.' },
  { d: 'medium', s: 'cultural', q: '"Masala chai" gets its signature flavor from milk, tea and what?', o: ['Spices', 'Coffee', 'Honey only', 'Lemon'], c: 0, e: 'Cardamom, ginger and other spices flavor masala chai.' },
  { d: 'medium', s: 'cultural', q: 'The spongy white sweet "Rasgulla" is associated with which region?', o: ['Punjab', 'Bengal/Odisha', 'Gujarat', 'Kerala'], c: 1, e: 'Rasgulla hails from eastern India.' },
  { d: 'medium', s: 'cultural', q: 'Puttu is classically paired with which side at breakfast?', o: ['Kadala curry', 'Butter chicken', 'Paneer', 'Dal makhani'], c: 0, e: 'Puttu with kadala (black chickpea) curry is iconic.' },
  { d: 'medium', s: 'cultural', q: 'Which Kerala drink is a mildly alcoholic sap tapped from palm trees?', o: ['Toddy (Kallu)', 'Lassi', 'Feni', 'Arrack'], c: 0, e: 'Toddy is fermented coconut/palm sap.' },
  { d: 'medium', s: 'cultural', q: '"Beef Ularthiyathu" is a slow-roasted specialty of which cuisine?', o: ['Goan', 'Kerala', 'Kashmiri', 'Bengali'], c: 1, e: 'Kerala beef fry is a regional delicacy.' },
  // Hard (11)
  { d: 'hard', s: 'cultural', q: 'What is the Malayalam term for a dry, lightly stir-fried vegetable side dish?', o: ['Mezhukkupuratti', 'Thoran', 'Pachadi', 'Olan'], c: 0, e: 'Mezhukkupuratti is a coated dry stir-fry.' },
  { d: 'hard', s: 'cultural', q: 'A traditional Onam Sadya can include roughly how many items?', o: ['About 8', 'About 15', 'Over two dozen', 'Exactly 5'], c: 2, e: 'A full Sadya can feature 26 or more dishes.' },
  { d: 'hard', s: 'cultural', q: '"Garam masala" literally translates to what?', o: ['Mixed spice', 'Hot spices', 'Sweet blend', 'Curry powder'], c: 1, e: 'Garam masala means "warm/hot spices".' },
  { d: 'hard', s: 'cultural', q: 'Thalassery (Malabar) biryani is famous for using which special rice?', o: ['Basmati', 'Jeerakasala (Kaima)', 'Sona Masoori', 'Ponni'], c: 1, e: 'Short-grain Jeerakasala rice defines Thalassery biryani.' },
  { d: 'hard', s: 'cultural', q: 'The dessert "Ada Pradhaman" is a payasam made with jaggery and what?', o: ['Rice ada', 'Vermicelli', 'Lentils', 'Sago only'], c: 0, e: 'Rice ada flakes simmer with jaggery and coconut milk.' },
  { d: 'hard', s: 'cultural', q: 'A Kerala "Thoran" is best described as what?', o: ['A sweet dish', 'A stir-fried vegetable with grated coconut', 'A spicy gravy', 'A fried bread'], c: 1, e: 'Thoran tosses vegetables with coconut and spices.' },
  { d: 'hard', s: 'cultural', q: 'Legend links the mixed dish "Avial" to which Mahabharata hero?', o: ['Arjuna', 'Bhima', 'Yudhishthira', 'Nakula'], c: 1, e: 'Folklore credits Bhima with inventing avial.' },
  { d: 'hard', s: 'cultural', q: 'The acclaimed Indian-origin chef Gaggan Anand runs his famous restaurant in which city?', o: ['Mumbai', 'Bangkok', 'London', 'Dubai'], c: 1, e: 'Gaggan\'s progressive Indian restaurant is in Bangkok.' },
  { d: 'hard', s: 'cultural', q: '"Olan", a mild Sadya dish, is cooked in which base?', o: ['Tomato gravy', 'Coconut milk', 'Tamarind water', 'Yogurt'], c: 1, e: 'Olan simmers ash gourd and beans in coconut milk.' },
  { d: 'hard', s: 'cultural', q: 'The "Puttu Kudam" steamer is traditionally crafted from which material?', o: ['Bamboo', 'Glass', 'Plastic', 'Cast iron'], c: 0, e: 'Classic puttu makers were bamboo (now often brass/steel).' },
  { d: 'hard', s: 'cultural', q: 'Which tangy Sadya dish combines yogurt with vegetables like cucumber or pineapple?', o: ['Pachadi', 'Thoran', 'Mezhukkupuratti', 'Erissery'], c: 0, e: 'Pachadi is a sweet-tangy yogurt side dish.' },
];
