// Topic: Geography — 70 questions (Wave 1 global classic, Wave 2 Gulf/India/Kerala NRI focus)
export default [
  // ===== WAVE 1 — GLOBAL CLASSIC (35) =====
  // Easy (12)
  { d: 'easy', s: 'classic', q: 'What is the capital of France?', o: ['Lyon', 'Paris', 'Marseille', 'Nice'], c: 1, e: 'Paris is the capital of France.' },
  { d: 'easy', s: 'classic', q: 'What is the capital of Japan?', o: ['Osaka', 'Kyoto', 'Tokyo', 'Nagoya'], c: 2, e: 'Tokyo is Japan\'s capital.' },
  { d: 'easy', s: 'classic', q: 'Which is the largest continent by area?', o: ['Africa', 'Asia', 'Europe', 'North America'], c: 1, e: 'Asia is the largest continent.' },
  { d: 'easy', s: 'classic', q: 'The Nile is commonly cited as the longest river on which continent?', o: ['Asia', 'Africa', 'South America', 'Europe'], c: 1, e: 'The Nile flows through northeastern Africa.' },
  { d: 'easy', s: 'classic', q: 'How many continents are there on Earth?', o: ['5', '6', '7', '8'], c: 2, e: 'There are seven continents.' },
  { d: 'easy', s: 'classic', q: 'What is the capital of the United States?', o: ['New York', 'Washington, D.C.', 'Los Angeles', 'Chicago'], c: 1, e: 'Washington, D.C. is the US capital.' },
  { d: 'easy', s: 'classic', q: 'Which is the largest ocean on Earth?', o: ['Atlantic', 'Indian', 'Pacific', 'Arctic'], c: 2, e: 'The Pacific is the largest ocean.' },
  { d: 'easy', s: 'classic', q: 'What is the capital of Italy?', o: ['Milan', 'Rome', 'Naples', 'Turin'], c: 1, e: 'Rome is Italy\'s capital.' },
  { d: 'easy', s: 'classic', q: 'The Sahara is the world\'s largest what?', o: ['Forest', 'Hot desert', 'Lake', 'Glacier'], c: 1, e: 'The Sahara is the largest hot desert.' },
  { d: 'easy', s: 'classic', q: 'What is the capital of Australia?', o: ['Sydney', 'Melbourne', 'Canberra', 'Perth'], c: 2, e: 'Canberra, not Sydney, is the capital.' },
  { d: 'easy', s: 'classic', q: 'Which country currently has the largest population?', o: ['China', 'India', 'USA', 'Indonesia'], c: 1, e: 'India became the most populous country in 2023.' },
  { d: 'easy', s: 'classic', q: 'What is the capital of Canada?', o: ['Toronto', 'Ottawa', 'Vancouver', 'Montreal'], c: 1, e: 'Ottawa is Canada\'s capital.' },
  // Medium (12)
  { d: 'medium', s: 'classic', q: 'What is the capital of Brazil?', o: ['Rio de Janeiro', 'São Paulo', 'Brasília', 'Salvador'], c: 2, e: 'Brasília has been the capital since 1960.' },
  { d: 'medium', s: 'classic', q: 'Mount Everest is part of which mountain range?', o: ['Andes', 'Himalayas', 'Alps', 'Rockies'], c: 1, e: 'Everest lies in the Himalayas.' },
  { d: 'medium', s: 'classic', q: 'Which is the smallest country in the world by area?', o: ['Monaco', 'Vatican City', 'Nauru', 'San Marino'], c: 1, e: 'Vatican City is the smallest sovereign state.' },
  { d: 'medium', s: 'classic', q: 'The Amazon rainforest is located mostly within which country?', o: ['Peru', 'Brazil', 'Colombia', 'Venezuela'], c: 1, e: 'Most of the Amazon lies in Brazil.' },
  { d: 'medium', s: 'classic', q: 'What is the capital of Russia?', o: ['Saint Petersburg', 'Moscow', 'Kazan', 'Novosibirsk'], c: 1, e: 'Moscow is Russia\'s capital.' },
  { d: 'medium', s: 'classic', q: 'The Great Barrier Reef lies off the coast of which country?', o: ['Indonesia', 'Australia', 'Philippines', 'Fiji'], c: 1, e: 'It runs along Queensland, Australia.' },
  { d: 'medium', s: 'classic', q: 'What is the capital of South Korea?', o: ['Busan', 'Seoul', 'Incheon', 'Daegu'], c: 1, e: 'Seoul is South Korea\'s capital.' },
  { d: 'medium', s: 'classic', q: 'The Andes, the longest mountain range above sea level, run through which continent?', o: ['Africa', 'Asia', 'South America', 'Europe'], c: 2, e: 'The Andes stretch along western South America.' },
  { d: 'medium', s: 'classic', q: 'What is the capital of Egypt?', o: ['Alexandria', 'Cairo', 'Giza', 'Luxor'], c: 1, e: 'Cairo is Egypt\'s capital.' },
  { d: 'medium', s: 'classic', q: 'Mount Kilimanjaro, Africa\'s highest peak, is in which country?', o: ['Kenya', 'Tanzania', 'Uganda', 'Ethiopia'], c: 1, e: 'Kilimanjaro rises in Tanzania.' },
  { d: 'medium', s: 'classic', q: 'Which country uses the most time zones for a single contiguous nation?', o: ['Russia', 'Canada', 'China', 'USA'], c: 0, e: 'Russia spans 11 time zones.' },
  { d: 'medium', s: 'classic', q: 'Which European country is shaped like a boot?', o: ['Spain', 'Italy', 'Greece', 'Portugal'], c: 1, e: 'Italy\'s peninsula resembles a boot.' },
  // Hard (11)
  { d: 'hard', s: 'classic', q: 'What is the capital of Kazakhstan?', o: ['Almaty', 'Astana', 'Bishkek', 'Tashkent'], c: 1, e: 'Astana is the capital of Kazakhstan.' },
  { d: 'hard', s: 'classic', q: 'What is the deepest point in Earth\'s oceans?', o: ['Puerto Rico Trench', 'Mariana Trench', 'Java Trench', 'Tonga Trench'], c: 1, e: 'The Mariana Trench reaches nearly 11 km deep.' },
  { d: 'hard', s: 'classic', q: 'Lake Baikal, the deepest lake on Earth, is located in which country?', o: ['Mongolia', 'Russia', 'China', 'Kazakhstan'], c: 1, e: 'Baikal lies in Siberia, Russia.' },
  { d: 'hard', s: 'classic', q: 'What is the capital of Argentina?', o: ['Santiago', 'Buenos Aires', 'Montevideo', 'Lima'], c: 1, e: 'Buenos Aires is Argentina\'s capital.' },
  { d: 'hard', s: 'classic', q: 'Which strait separates Asia from North America?', o: ['Strait of Malacca', 'Bering Strait', 'Bosphorus', 'Strait of Hormuz'], c: 1, e: 'The Bering Strait lies between Russia and Alaska.' },
  { d: 'hard', s: 'classic', q: 'The Atacama, the driest non-polar desert, is in which country?', o: ['Peru', 'Chile', 'Bolivia', 'Argentina'], c: 1, e: 'The Atacama lies in northern Chile.' },
  { d: 'hard', s: 'classic', q: 'Which African country was never formally colonized by a European power?', o: ['Kenya', 'Ethiopia', 'Ghana', 'Nigeria'], c: 1, e: 'Ethiopia famously resisted colonization.' },
  { d: 'hard', s: 'classic', q: 'The Volga, the longest river in Europe, flows through which country?', o: ['Germany', 'Russia', 'Ukraine', 'Poland'], c: 1, e: 'The Volga flows through western Russia.' },
  { d: 'hard', s: 'classic', q: 'What is the capital of New Zealand?', o: ['Auckland', 'Wellington', 'Christchurch', 'Hamilton'], c: 1, e: 'Wellington is the capital, not Auckland.' },
  { d: 'hard', s: 'classic', q: 'Which country has the most natural lakes in the world?', o: ['Russia', 'Canada', 'Finland', 'USA'], c: 1, e: 'Canada holds the majority of the world\'s lakes.' },
  { d: 'hard', s: 'classic', q: 'The Strait of Gibraltar separates Europe from which continent?', o: ['Asia', 'Africa', 'South America', 'Antarctica'], c: 1, e: 'It separates Spain from Morocco in Africa.' },

  // ===== WAVE 2 — GULF / INDIA / KERALA (NRI FOCUS) (35) =====
  // Easy (12)
  { d: 'easy', s: 'classic', q: 'What is the capital of the United Arab Emirates?', o: ['Dubai', 'Abu Dhabi', 'Sharjah', 'Ajman'], c: 1, e: 'Abu Dhabi is the UAE capital, not Dubai.' },
  { d: 'easy', s: 'classic', q: 'The Burj Khalifa, the world\'s tallest building, is in which city?', o: ['Doha', 'Dubai', 'Riyadh', 'Abu Dhabi'], c: 1, e: 'The Burj Khalifa stands in Dubai.' },
  { d: 'easy', s: 'classic', q: 'What is the capital of Saudi Arabia?', o: ['Jeddah', 'Riyadh', 'Mecca', 'Dammam'], c: 1, e: 'Riyadh is Saudi Arabia\'s capital.' },
  { d: 'easy', s: 'classic', q: 'What is the capital of Kerala?', o: ['Kochi', 'Kozhikode', 'Thiruvananthapuram', 'Thrissur'], c: 2, e: 'Thiruvananthapuram (Trivandrum) is Kerala\'s capital.' },
  { d: 'easy', s: 'classic', q: 'What is the capital of Qatar?', o: ['Doha', 'Al Wakrah', 'Lusail', 'Al Rayyan'], c: 0, e: 'Doha is Qatar\'s capital.' },
  { d: 'easy', s: 'classic', q: 'The famous backwaters are a key attraction of which Indian state?', o: ['Goa', 'Kerala', 'Tamil Nadu', 'Karnataka'], c: 1, e: 'Kerala\'s backwaters draw tourists worldwide.' },
  { d: 'easy', s: 'classic', q: 'What is the capital of India?', o: ['Mumbai', 'New Delhi', 'Kolkata', 'Chennai'], c: 1, e: 'New Delhi is India\'s capital.' },
  { d: 'easy', s: 'classic', q: 'Which sea lies to the west of Kerala?', o: ['Bay of Bengal', 'Arabian Sea', 'Indian Ocean', 'Laccadive Sea'], c: 1, e: 'The Arabian Sea borders Kerala\'s coast.' },
  { d: 'easy', s: 'classic', q: 'Kochi (Cochin) is a major port city in which state?', o: ['Karnataka', 'Kerala', 'Goa', 'Tamil Nadu'], c: 1, e: 'Kochi is Kerala\'s commercial hub.' },
  { d: 'easy', s: 'classic', q: 'What is the capital of Oman?', o: ['Salalah', 'Muscat', 'Sohar', 'Nizwa'], c: 1, e: 'Muscat is Oman\'s capital.' },
  { d: 'easy', s: 'classic', q: 'What is the capital of Kuwait?', o: ['Kuwait City', 'Hawalli', 'Salmiya', 'Jahra'], c: 0, e: 'Kuwait City is the capital.' },
  { d: 'easy', s: 'classic', q: 'What is the capital of Bahrain?', o: ['Riffa', 'Manama', 'Muharraq', 'Isa Town'], c: 1, e: 'Manama is Bahrain\'s capital.' },
  // Medium (12)
  { d: 'medium', s: 'classic', q: 'How many emirates make up the United Arab Emirates?', o: ['5', '6', '7', '9'], c: 2, e: 'The UAE is a federation of seven emirates.' },
  { d: 'medium', s: 'classic', q: 'Which Kerala hill station is most famous for its tea plantations?', o: ['Wayanad', 'Munnar', 'Ponmudi', 'Vagamon'], c: 1, e: 'Munnar is renowned for sprawling tea estates.' },
  { d: 'medium', s: 'classic', q: 'The Western Ghats run along which coast of India?', o: ['Eastern', 'Western', 'Northern', 'Southern'], c: 1, e: 'The Western Ghats parallel India\'s west coast.' },
  { d: 'medium', s: 'classic', q: 'The Periyar is the longest river in which Indian state?', o: ['Tamil Nadu', 'Kerala', 'Karnataka', 'Goa'], c: 1, e: 'The Periyar is Kerala\'s longest river.' },
  { d: 'medium', s: 'classic', q: 'Which Gulf nation is an island country (archipelago)?', o: ['Qatar', 'Bahrain', 'Kuwait', 'Oman'], c: 1, e: 'Bahrain is an archipelago in the Persian Gulf.' },
  { d: 'medium', s: 'classic', q: 'Kerala is popularly marketed with which tourism tagline?', o: ['Incredible Coast', 'God\'s Own Country', 'Land of Spices', 'Emerald Isle'], c: 1, e: '"God\'s Own Country" is Kerala\'s famous slogan.' },
  { d: 'medium', s: 'classic', q: 'The Palm Jumeirah artificial island is located in which city?', o: ['Doha', 'Dubai', 'Abu Dhabi', 'Manama'], c: 1, e: 'The palm-shaped island is in Dubai.' },
  { d: 'medium', s: 'classic', q: 'Which is the largest country on the Arabian Peninsula by area?', o: ['UAE', 'Saudi Arabia', 'Oman', 'Yemen'], c: 1, e: 'Saudi Arabia dominates the peninsula.' },
  { d: 'medium', s: 'classic', q: 'Wayanad, known for its hills and wildlife, is a district of which state?', o: ['Karnataka', 'Kerala', 'Tamil Nadu', 'Telangana'], c: 1, e: 'Wayanad is a northeastern district of Kerala.' },
  { d: 'medium', s: 'classic', q: 'The capital of the neighboring state Karnataka is which tech city?', o: ['Hyderabad', 'Bengaluru', 'Chennai', 'Pune'], c: 1, e: 'Bengaluru is Karnataka\'s capital.' },
  { d: 'medium', s: 'classic', q: 'Which Indian metro is the closest major Gulf-flight hub for many Malayalis?', o: ['Kochi (Cochin) Airport', 'Delhi Airport', 'Kolkata Airport', 'Pune Airport'], c: 0, e: 'Cochin International Airport handles huge NRI traffic.' },
  { d: 'medium', s: 'classic', q: 'The Strait of Hormuz, vital for oil shipping, lies between Oman and which country?', o: ['Iran', 'Iraq', 'Yemen', 'Pakistan'], c: 0, e: 'It connects the Persian Gulf to the Gulf of Oman between Iran and Oman.' },
  // Hard (11)
  { d: 'hard', s: 'classic', q: 'How many districts does Kerala have?', o: ['12', '14', '16', '18'], c: 1, e: 'Kerala is divided into 14 districts.' },
  { d: 'hard', s: 'classic', q: 'Anamudi, the highest peak in South India, is located in which state?', o: ['Tamil Nadu', 'Kerala', 'Karnataka', 'Andhra Pradesh'], c: 1, e: 'Anamudi (2,695 m) is in Kerala\'s Idukki district.' },
  { d: 'hard', s: 'classic', q: 'The King Fahd Causeway connects Bahrain to which country?', o: ['Qatar', 'Saudi Arabia', 'UAE', 'Kuwait'], c: 1, e: 'The causeway links Bahrain and Saudi Arabia.' },
  { d: 'hard', s: 'classic', q: 'Which is the southernmost district of Kerala?', o: ['Kollam', 'Thiruvananthapuram', 'Kanyakumari', 'Pathanamthitta'], c: 1, e: 'Thiruvananthapuram is Kerala\'s southernmost district.' },
  { d: 'hard', s: 'classic', q: 'The vast "Empty Quarter" (Rub\' al Khali) desert spans which region?', o: ['Sahara', 'Arabian Peninsula', 'Central Asia', 'Horn of Africa'], c: 1, e: 'It is the world\'s largest sand desert, in Arabia.' },
  { d: 'hard', s: 'classic', q: 'Vembanad, the longest lake in India, is located in which state?', o: ['Odisha', 'Kerala', 'Andhra Pradesh', 'West Bengal'], c: 1, e: 'Vembanad Lake stretches across central Kerala.' },
  { d: 'hard', s: 'classic', q: 'The Lakshadweep islands lie in which body of water?', o: ['Bay of Bengal', 'Arabian Sea', 'Andaman Sea', 'Indian Ocean (far south)'], c: 1, e: 'Lakshadweep sits in the Arabian Sea off Kerala.' },
  { d: 'hard', s: 'classic', q: 'Which UAE emirate is the largest by land area?', o: ['Dubai', 'Abu Dhabi', 'Sharjah', 'Ras Al Khaimah'], c: 1, e: 'Abu Dhabi covers most of the UAE\'s land.' },
  { d: 'hard', s: 'classic', q: 'Silent Valley National Park is located in which Kerala district?', o: ['Idukki', 'Palakkad', 'Wayanad', 'Pathanamthitta'], c: 1, e: 'Silent Valley lies in Palakkad district.' },
  { d: 'hard', s: 'classic', q: 'The Mahé enclave (part of Puducherry) is surrounded by which state?', o: ['Tamil Nadu', 'Kerala', 'Karnataka', 'Goa'], c: 1, e: 'Mahé is a coastal enclave within Kerala.' },
  { d: 'hard', s: 'classic', q: 'The Nilgiri mountains form a tri-junction of Kerala, Tamil Nadu and which state?', o: ['Karnataka', 'Andhra Pradesh', 'Telangana', 'Goa'], c: 0, e: 'The Nilgiris meet Kerala, Tamil Nadu and Karnataka.' },
];
