// Topic: History — 70 questions (all classic; Wave 1 global, Wave 2 Asia/Middle East/India)
export default [
  // ===== WAVE 1 — GLOBAL CLASSIC (35) =====
  // Easy (12)
  { d: 'easy', s: 'classic', q: 'In which year did World War II end?', o: ['1918', '1939', '1945', '1950'], c: 2, e: 'WWII ended in 1945 with Axis surrender.' },
  { d: 'easy', s: 'classic', q: 'Who was the first President of the United States?', o: ['Thomas Jefferson', 'George Washington', 'Abraham Lincoln', 'John Adams'], c: 1, e: 'Washington took office in 1789.' },
  { d: 'easy', s: 'classic', q: 'The Great Wall is located in which country?', o: ['Japan', 'China', 'Mongolia', 'India'], c: 1, e: 'The Great Wall stretches across northern China.' },
  { d: 'easy', s: 'classic', q: 'Ancient Egyptians built pyramids primarily as what?', o: ['Temples', 'Tombs', 'Granaries', 'Palaces'], c: 1, e: 'Pyramids were monumental tombs for pharaohs.' },
  { d: 'easy', s: 'classic', q: 'In which year did the Titanic sink?', o: ['1905', '1912', '1920', '1898'], c: 1, e: 'The Titanic sank on its maiden voyage in 1912.' },
  { d: 'easy', s: 'classic', q: 'The Colosseum was built by which ancient civilization?', o: ['Greek', 'Roman', 'Egyptian', 'Persian'], c: 1, e: 'The Romans built the Colosseum in the 1st century AD.' },
  { d: 'easy', s: 'classic', q: 'Who reached the Americas in 1492 under the Spanish crown?', o: ['Vasco da Gama', 'Christopher Columbus', 'Ferdinand Magellan', 'Marco Polo'], c: 1, e: 'Columbus crossed the Atlantic in 1492.' },
  { d: 'easy', s: 'classic', q: 'The French Revolution began in which year?', o: ['1776', '1789', '1804', '1815'], c: 1, e: 'It began in 1789 with the storming of the Bastille.' },
  { d: 'easy', s: 'classic', q: 'In which year did Apollo 11 land humans on the Moon?', o: ['1965', '1969', '1972', '1959'], c: 1, e: 'Armstrong and Aldrin landed in July 1969.' },
  { d: 'easy', s: 'classic', q: 'The Cold War was primarily between the USA and which power?', o: ['Germany', 'Soviet Union', 'China', 'Japan'], c: 1, e: 'It was a rivalry between the US and the USSR.' },
  { d: 'easy', s: 'classic', q: 'Cleopatra was the last active ruler of which ancient kingdom?', o: ['Persia', 'Egypt', 'Greece', 'Carthage'], c: 1, e: 'Cleopatra VII ruled Ptolemaic Egypt.' },
  { d: 'easy', s: 'classic', q: 'Adolf Hitler led which political party?', o: ['Fascist Party', 'Nazi Party', 'Communist Party', 'Labour Party'], c: 1, e: 'Hitler led the National Socialist (Nazi) Party.' },
  // Medium (12)
  { d: 'medium', s: 'classic', q: 'In which year did World War I begin?', o: ['1912', '1914', '1916', '1918'], c: 1, e: 'WWI began in 1914 after the assassination of Franz Ferdinand.' },
  { d: 'medium', s: 'classic', q: 'The Berlin Wall fell in which year?', o: ['1985', '1989', '1991', '1993'], c: 1, e: 'The wall fell in November 1989.' },
  { d: 'medium', s: 'classic', q: 'Who was Britain\'s Prime Minister for most of World War II?', o: ['Neville Chamberlain', 'Winston Churchill', 'Clement Attlee', 'Anthony Eden'], c: 1, e: 'Churchill led Britain from 1940.' },
  { d: 'medium', s: 'classic', q: 'The Magna Carta was sealed in which year?', o: ['1066', '1215', '1348', '1492'], c: 1, e: 'King John sealed Magna Carta in 1215.' },
  { d: 'medium', s: 'classic', q: 'Which civilization built Machu Picchu?', o: ['Aztec', 'Maya', 'Inca', 'Olmec'], c: 2, e: 'The Inca built Machu Picchu in the 15th century.' },
  { d: 'medium', s: 'classic', q: 'The Renaissance began in which country?', o: ['France', 'Italy', 'England', 'Spain'], c: 1, e: 'The Renaissance began in Italy in the 14th century.' },
  { d: 'medium', s: 'classic', q: 'Who assassinated US President Abraham Lincoln?', o: ['Lee Harvey Oswald', 'John Wilkes Booth', 'Charles Guiteau', 'Leon Czolgosz'], c: 1, e: 'Booth shot Lincoln in 1865.' },
  { d: 'medium', s: 'classic', q: 'The US Declaration of Independence was adopted in which year?', o: ['1776', '1781', '1787', '1791'], c: 0, e: 'It was adopted on July 4, 1776.' },
  { d: 'medium', s: 'classic', q: 'In which year did the Russian (Bolshevik) Revolution occur?', o: ['1905', '1917', '1923', '1929'], c: 1, e: 'The October Revolution took place in 1917.' },
  { d: 'medium', s: 'classic', q: 'Napoleon Bonaparte was finally defeated at which 1815 battle?', o: ['Austerlitz', 'Waterloo', 'Trafalgar', 'Leipzig'], c: 1, e: 'Napoleon lost at Waterloo in 1815.' },
  { d: 'medium', s: 'classic', q: 'Who was the first human to journey into outer space?', o: ['Neil Armstrong', 'Yuri Gagarin', 'Alan Shepard', 'John Glenn'], c: 1, e: 'Soviet cosmonaut Gagarin orbited Earth in 1961.' },
  { d: 'medium', s: 'classic', q: 'The "Black Death" of the 14th century was what kind of disaster?', o: ['Famine', 'Plague pandemic', 'War', 'Volcanic winter'], c: 1, e: 'The bubonic plague killed a third of Europe.' },
  // Hard (11)
  { d: 'hard', s: 'classic', q: 'The 1919 Treaty of Versailles formally ended which war?', o: ['World War I', 'World War II', 'Franco-Prussian War', 'Crimean War'], c: 0, e: 'It imposed terms on Germany after WWI.' },
  { d: 'hard', s: 'classic', q: 'General Hannibal famously crossed the Alps using what animals?', o: ['Horses', 'Camels', 'Elephants', 'Oxen'], c: 2, e: 'Hannibal led war elephants against Rome.' },
  { d: 'hard', s: 'classic', q: 'Which is the only surviving Wonder of the Ancient World?', o: ['Hanging Gardens', 'Great Pyramid of Giza', 'Colossus of Rhodes', 'Lighthouse of Alexandria'], c: 1, e: 'The Great Pyramid still stands today.' },
  { d: 'hard', s: 'classic', q: 'The Hundred Years\' War was fought between England and which country?', o: ['Spain', 'France', 'Scotland', 'Germany'], c: 1, e: 'England and France fought from 1337 to 1453.' },
  { d: 'hard', s: 'classic', q: 'Who became the first Roman Emperor?', o: ['Julius Caesar', 'Augustus', 'Nero', 'Trajan'], c: 1, e: 'Augustus (Octavian) became the first emperor in 27 BC.' },
  { d: 'hard', s: 'classic', q: 'The Rosetta Stone was key to deciphering what?', o: ['Cuneiform', 'Egyptian hieroglyphs', 'Linear B', 'Mayan glyphs'], c: 1, e: 'Champollion used it to crack hieroglyphs.' },
  { d: 'hard', s: 'classic', q: 'The Battle of Hastings took place in which year?', o: ['1066', '1215', '1314', '1485'], c: 0, e: 'William the Conqueror won in 1066.' },
  { d: 'hard', s: 'classic', q: 'Genghis Khan founded which empire?', o: ['Ottoman Empire', 'Mongol Empire', 'Persian Empire', 'Byzantine Empire'], c: 1, e: 'He united the tribes into the Mongol Empire in 1206.' },
  { d: 'hard', s: 'classic', q: 'Constantinople fell in 1453 to which empire?', o: ['Mongol', 'Ottoman', 'Roman', 'Safavid'], c: 1, e: 'The Ottomans captured the Byzantine capital.' },
  { d: 'hard', s: 'classic', q: 'The Code of Hammurabi originated in which ancient region?', o: ['Egypt', 'Babylon', 'Greece', 'China'], c: 1, e: 'It is one of the oldest law codes, from Babylon.' },
  { d: 'hard', s: 'classic', q: 'The Aztec Empire was conquered by which Spanish conquistador?', o: ['Francisco Pizarro', 'Hernán Cortés', 'Hernando de Soto', 'Vasco Núñez'], c: 1, e: 'Cortés toppled the Aztecs in 1521.' },

  // ===== WAVE 2 — ASIA / MIDDLE EAST / INDIA (35) =====
  // Easy (12)
  { d: 'easy', s: 'classic', q: 'Who led India\'s nonviolent independence movement?', o: ['Jawaharlal Nehru', 'Mahatma Gandhi', 'Bhagat Singh', 'Subhas Chandra Bose'], c: 1, e: 'Gandhi championed nonviolent resistance (satyagraha).' },
  { d: 'easy', s: 'classic', q: 'In which year did India gain independence?', o: ['1945', '1947', '1950', '1942'], c: 1, e: 'India became independent on 15 August 1947.' },
  { d: 'easy', s: 'classic', q: 'Emperor Ashoka belonged to which dynasty?', o: ['Gupta', 'Maurya', 'Chola', 'Mughal'], c: 1, e: 'Ashoka was the great Mauryan emperor.' },
  { d: 'easy', s: 'classic', q: 'The Taj Mahal was commissioned by which Mughal emperor?', o: ['Akbar', 'Shah Jahan', 'Aurangzeb', 'Humayun'], c: 1, e: 'Shah Jahan built it for Mumtaz Mahal.' },
  { d: 'easy', s: 'classic', q: 'Akbar the Great was a ruler of which empire?', o: ['Maratha', 'Mughal', 'Maurya', 'Vijayanagara'], c: 1, e: 'Akbar was the third Mughal emperor.' },
  { d: 'easy', s: 'classic', q: 'Who was the first Prime Minister of independent India?', o: ['Sardar Patel', 'Jawaharlal Nehru', 'Rajendra Prasad', 'B. R. Ambedkar'], c: 1, e: 'Nehru became PM in 1947.' },
  { d: 'easy', s: 'classic', q: 'Mohenjo-daro and Harappa belong to which ancient civilization?', o: ['Vedic', 'Indus Valley', 'Gupta', 'Mauryan'], c: 1, e: 'They were major Indus Valley cities.' },
  { d: 'easy', s: 'classic', q: 'Chandragupta founded which Indian empire?', o: ['Gupta', 'Maurya', 'Chola', 'Pala'], c: 1, e: 'Chandragupta Maurya founded the Maurya Empire.' },
  { d: 'easy', s: 'classic', q: 'The Pyramids of Giza lie near which modern city?', o: ['Alexandria', 'Cairo', 'Luxor', 'Aswan'], c: 1, e: 'The Giza pyramids are on Cairo\'s outskirts.' },
  { d: 'easy', s: 'classic', q: 'India celebrates Independence Day on which date?', o: ['26 January', '15 August', '2 October', '14 August'], c: 1, e: '15 August marks independence from Britain.' },
  { d: 'easy', s: 'classic', q: 'Ancient Egyptians wrote using which script?', o: ['Cuneiform', 'Hieroglyphics', 'Sanskrit', 'Runes'], c: 1, e: 'Hieroglyphics combined logographic and alphabetic signs.' },
  { d: 'easy', s: 'classic', q: 'India\'s Republic Day is celebrated on which date?', o: ['15 August', '26 January', '2 October', '1 January'], c: 1, e: 'The Constitution came into force on 26 January 1950.' },
  // Medium (12)
  { d: 'medium', s: 'classic', q: 'The 1947 Partition of British India created which new nation?', o: ['Bangladesh', 'Pakistan', 'Sri Lanka', 'Nepal'], c: 1, e: 'Partition split British India into India and Pakistan.' },
  { d: 'medium', s: 'classic', q: 'Who founded the Mughal Empire in India?', o: ['Akbar', 'Babur', 'Humayun', 'Shah Jahan'], c: 1, e: 'Babur won the First Battle of Panipat in 1526.' },
  { d: 'medium', s: 'classic', q: 'The Silk Road primarily connected China with which region?', o: ['Australia', 'Europe and the Mediterranean', 'Sub-Saharan Africa', 'The Americas'], c: 1, e: 'It linked Asian and Mediterranean trade.' },
  { d: 'medium', s: 'classic', q: 'The Ottoman Empire was centered in which modern country?', o: ['Iran', 'Turkey', 'Egypt', 'Iraq'], c: 1, e: 'Its capital Constantinople is today\'s Istanbul.' },
  { d: 'medium', s: 'classic', q: 'The 1919 Jallianwala Bagh massacre took place in which city?', o: ['Lahore', 'Amritsar', 'Delhi', 'Kolkata'], c: 1, e: 'British troops fired on civilians in Amritsar.' },
  { d: 'medium', s: 'classic', q: 'The Quit India Movement was launched in which year?', o: ['1930', '1942', '1945', '1919'], c: 1, e: 'Gandhi launched it in 1942.' },
  { d: 'medium', s: 'classic', q: 'Tipu Sultan was the ruler of which kingdom?', o: ['Hyderabad', 'Mysore', 'Travancore', 'Awadh'], c: 1, e: 'Tipu, the "Tiger of Mysore", fought the British.' },
  { d: 'medium', s: 'classic', q: 'The 1757 Battle of Plassey established the power of which force in Bengal?', o: ['French', 'British East India Company', 'Dutch', 'Portuguese'], c: 1, e: 'Robert Clive\'s victory began British rule in India.' },
  { d: 'medium', s: 'classic', q: 'Emperor Ashoka embraced which religion after the Kalinga war?', o: ['Jainism', 'Buddhism', 'Hinduism', 'Sikhism'], c: 1, e: 'The bloodshed led Ashoka to Buddhism.' },
  { d: 'medium', s: 'classic', q: 'The Gupta period is often called India\'s what?', o: ['Dark Age', 'Golden Age', 'Iron Age', 'Bronze Age'], c: 1, e: 'It saw great advances in science, art and math.' },
  { d: 'medium', s: 'classic', q: 'Akbar built which planned Mughal city near Agra?', o: ['Fatehpur Sikri', 'Jaipur', 'Lucknow', 'Hyderabad'], c: 0, e: 'Fatehpur Sikri served briefly as Akbar\'s capital.' },
  { d: 'medium', s: 'classic', q: 'Which ancient Indian university was a renowned center of learning?', o: ['Nalanda', 'Oxford', 'Al-Azhar', 'Bologna'], c: 0, e: 'Nalanda attracted scholars from across Asia.' },
  // Hard (11)
  { d: 'hard', s: 'classic', q: 'Who won the First Battle of Panipat in 1526?', o: ['Akbar', 'Babur', 'Ibrahim Lodi', 'Sher Shah Suri'], c: 1, e: 'Babur defeated Ibrahim Lodi to found the Mughal Empire.' },
  { d: 'hard', s: 'classic', q: 'Who was the last Mughal emperor of India?', o: ['Aurangzeb', 'Bahadur Shah Zafar', 'Shah Alam II', 'Akbar II'], c: 1, e: 'Bahadur Shah Zafar was exiled after 1857.' },
  { d: 'hard', s: 'classic', q: 'What is the status of the Indus Valley script today?', o: ['Fully deciphered', 'Undeciphered', 'A form of Sanskrit', 'A form of Tamil'], c: 1, e: 'The Harappan script remains undeciphered.' },
  { d: 'hard', s: 'classic', q: 'What was the capital of the Mauryan Empire?', o: ['Ujjain', 'Pataliputra', 'Taxila', 'Varanasi'], c: 1, e: 'Pataliputra (modern Patna) was the Mauryan capital.' },
  { d: 'hard', s: 'classic', q: 'The 1565 Battle of Talikota led to the fall of which empire?', o: ['Vijayanagara', 'Chola', 'Pallava', 'Pandya'], c: 0, e: 'A coalition of sultanates defeated Vijayanagara.' },
  { d: 'hard', s: 'classic', q: 'Who is credited with writing the ancient treatise "Arthashastra"?', o: ['Kalidasa', 'Chanakya (Kautilya)', 'Panini', 'Aryabhata'], c: 1, e: 'Chanakya wrote the manual on statecraft and economics.' },
  { d: 'hard', s: 'classic', q: 'The Suez Canal connects the Mediterranean Sea to which body of water?', o: ['Black Sea', 'Red Sea', 'Arabian Sea', 'Caspian Sea'], c: 1, e: 'It links the Mediterranean and the Red Sea.' },
  { d: 'hard', s: 'classic', q: 'Persepolis was the ceremonial capital of which empire?', o: ['Babylonian', 'Achaemenid (Persian)', 'Ottoman', 'Assyrian'], c: 1, e: 'Persepolis was built by the Achaemenid Persians.' },
  { d: 'hard', s: 'classic', q: 'Which Mongol leader sacked Baghdad in 1258?', o: ['Genghis Khan', 'Hulagu Khan', 'Kublai Khan', 'Timur'], c: 1, e: 'Hulagu Khan ended the Abbasid Caliphate.' },
  { d: 'hard', s: 'classic', q: 'The 1857 uprising in India is also known as what?', o: ['The Sepoy Mutiny', 'The Quit India Movement', 'The Salt March', 'The Bengal Famine'], c: 0, e: 'It is called the Sepoy Mutiny or First War of Independence.' },
  { d: 'hard', s: 'classic', q: 'The famous Kohinoor diamond originally came from which region?', o: ['South Africa', 'India', 'Brazil', 'Russia'], c: 1, e: 'It was mined in the Golconda region of India.' },
];
