// Topic: Language & Words — 70 questions (35 classic + 35 Indian/Malayali cultural)
export default [
  // ===== SET A — CLASSIC / GLOBAL (35) =====
  // Easy (12)
  { d: 'easy', s: 'classic', q: 'The idiom "break a leg" is a way of wishing someone what?', o: ['Goodbye', 'Good luck', 'Bad news', 'A quick recovery'], c: 1, e: 'It means "good luck", especially in theatre.' },
  { d: 'easy', s: 'classic', q: 'Words that sound alike but are spelled differently are called what?', o: ['Synonyms', 'Homophones', 'Antonyms', 'Acronyms'], c: 1, e: 'Like "to", "too" and "two" — homophones.' },
  { d: 'easy', s: 'classic', q: 'What is the antonym (opposite) of "happy"?', o: ['Joyful', 'Sad', 'Cheerful', 'Glad'], c: 1, e: 'Sad is the opposite of happy.' },
  { d: 'easy', s: 'classic', q: 'Which word is a synonym for "big"?', o: ['Tiny', 'Large', 'Narrow', 'Short'], c: 1, e: 'Large means the same as big.' },
  { d: 'easy', s: 'classic', q: 'The idiom "raining cats and dogs" means it is raining how?', o: ['Lightly', 'Very heavily', 'Not at all', 'With sunshine'], c: 1, e: 'It describes a heavy downpour.' },
  { d: 'easy', s: 'classic', q: 'A word that imitates a sound, like "buzz" or "bang", is an example of what?', o: ['Metaphor', 'Onomatopoeia', 'Simile', 'Idiom'], c: 1, e: 'Such sound-words are onomatopoeia.' },
  { d: 'easy', s: 'classic', q: 'What is the plural of "child"?', o: ['Childs', 'Children', 'Childes', 'Childer'], c: 1, e: '"Children" is the irregular plural.' },
  { d: 'easy', s: 'classic', q: 'A noun is a word for a what?', o: ['Action', 'Person, place or thing', 'Description', 'Connection'], c: 1, e: 'Nouns name people, places or things.' },
  { d: 'easy', s: 'classic', q: 'What is the past tense of "go"?', o: ['Goed', 'Gone', 'Went', 'Going'], c: 2, e: 'The simple past of "go" is "went".' },
  { d: 'easy', s: 'classic', q: 'Which of these letters is a vowel?', o: ['B', 'E', 'R', 'T'], c: 1, e: 'E is a vowel (A, E, I, O, U).' },
  { d: 'easy', s: 'classic', q: 'The idiom "a piece of cake" means something is very what?', o: ['Sweet', 'Easy', 'Expensive', 'Rare'], c: 1, e: 'It means very easy to do.' },
  { d: 'easy', s: 'classic', q: 'A verb is best described as a what?', o: ['Naming word', 'Action or doing word', 'Describing word', 'Joining word'], c: 1, e: 'Verbs express actions or states.' },
  // Medium (12)
  { d: 'medium', s: 'classic', q: 'The study of the origin and history of words is called what?', o: ['Etymology', 'Entomology', 'Phonology', 'Morphology'], c: 0, e: 'Etymology traces word origins.' },
  { d: 'medium', s: 'classic', q: 'The German loanword "schadenfreude" means what?', o: ['Joy of life', 'Pleasure at another\'s misfortune', 'Fear of crowds', 'Love of nature'], c: 1, e: 'It is taking pleasure in someone\'s misfortune.' },
  { d: 'medium', s: 'classic', q: 'A metaphor compares two things without using which words?', o: ['"Is" or "was"', '"Like" or "as"', '"And" or "but"', '"Very" or "really"'], c: 1, e: 'Unlike a simile, a metaphor omits "like/as".' },
  { d: 'medium', s: 'classic', q: 'The word "alphabet" comes from the first two letters of which alphabet?', o: ['Latin', 'Greek (alpha, beta)', 'Hebrew', 'Cyrillic'], c: 1, e: 'Alpha + Beta gives us "alphabet".' },
  { d: 'medium', s: 'classic', q: 'The phrase "bon appétit" comes from which language?', o: ['Italian', 'French', 'Spanish', 'Latin'], c: 1, e: 'It is French for "enjoy your meal".' },
  { d: 'medium', s: 'classic', q: 'A "palindrome" is a word or phrase that reads the same how?', o: ['Upside down', 'Backward and forward', 'In a mirror only', 'In all caps'], c: 1, e: 'Like "level" or "racecar".' },
  { d: 'medium', s: 'classic', q: 'The figure of speech "hyperbole" refers to what?', o: ['Understatement', 'Exaggeration', 'Repetition', 'Contradiction'], c: 1, e: 'Hyperbole is deliberate exaggeration.' },
  { d: 'medium', s: 'classic', q: 'The Latin abbreviation "etc." (et cetera) means what?', o: ['For example', 'And so on', 'That is', 'In other words'], c: 1, e: '"Et cetera" means "and the rest".' },
  { d: 'medium', s: 'classic', q: 'The French phrase "déjà vu" literally means what?', o: ['Already seen', 'Goodbye', 'Of course', 'So be it'], c: 0, e: 'It means "already seen".' },
  { d: 'medium', s: 'classic', q: 'An "oxymoron" combines two terms that are what?', o: ['Identical', 'Contradictory', 'Rhyming', 'Foreign'], c: 1, e: 'Like "deafening silence" — contradictory terms.' },
  { d: 'medium', s: 'classic', q: 'The loanword "tsunami" comes from which language?', o: ['Chinese', 'Japanese', 'Korean', 'Thai'], c: 1, e: '"Tsunami" is Japanese for "harbor wave".' },
  { d: 'medium', s: 'classic', q: 'The word "robot" entered English from a play in which language?', o: ['Russian', 'Czech', 'Polish', 'German'], c: 1, e: 'It comes from Karel Čapek\'s Czech play "R.U.R.".' },
  // Hard (11)
  { d: 'hard', s: 'classic', q: 'The branch of linguistics that studies speech sounds is called what?', o: ['Syntax', 'Phonetics', 'Semantics', 'Pragmatics'], c: 1, e: 'Phonetics studies the sounds of speech.' },
  { d: 'hard', s: 'classic', q: '"Lexicography" is the practice of doing what?', o: ['Writing poetry', 'Compiling dictionaries', 'Translating texts', 'Studying grammar'], c: 1, e: 'Lexicographers compile dictionaries.' },
  { d: 'hard', s: 'classic', q: 'English belongs primarily to which language family?', o: ['Sino-Tibetan', 'Indo-European', 'Afro-Asiatic', 'Dravidian'], c: 1, e: 'English is a Germanic, Indo-European language.' },
  { d: 'hard', s: 'classic', q: 'The "Oxford comma" is placed where in a list?', o: ['After the first item', 'Before the final "and"', 'At the start', 'Never used'], c: 1, e: 'It precedes the conjunction before the last item.' },
  { d: 'hard', s: 'classic', q: 'A "morpheme" is the smallest unit of what in language?', o: ['Sound', 'Meaning', 'Spelling', 'Stress'], c: 1, e: 'A morpheme is the smallest meaningful unit.' },
  { d: 'hard', s: 'classic', q: 'The Latin phrase "carpe diem" translates to what?', o: ['Seize the day', 'To each their own', 'Buyer beware', 'Time flies'], c: 0, e: '"Carpe diem" means "seize the day".' },
  { d: 'hard', s: 'classic', q: 'Esperanto is best described as what kind of language?', o: ['An ancient dialect', 'A constructed (artificial) language', 'A dead language', 'A sign language'], c: 1, e: 'Esperanto was created to be a universal second language.' },
  { d: 'hard', s: 'classic', q: 'The small dot above a lowercase "i" or "j" is called a what?', o: ['Tittle', 'Serif', 'Diacritic', 'Cedilla'], c: 0, e: 'That dot is called a "tittle".' },
  { d: 'hard', s: 'classic', q: 'A writing system where each symbol represents a consonant-vowel syllable is called what?', o: ['Alphabet', 'Abugida (alphasyllabary)', 'Logography', 'Abjad'], c: 1, e: 'Many Indian scripts are abugidas.' },
  { d: 'hard', s: 'classic', q: 'The word "quarantine" originates from a word meaning which number of days?', o: ['Ten', 'Forty', 'Sixty', 'Seven'], c: 1, e: 'It comes from Italian "quaranta" (forty) days of isolation.' },
  { d: 'hard', s: 'classic', q: 'Which writing direction does Arabic use?', o: ['Left to right', 'Right to left', 'Top to bottom', 'Boustrophedon'], c: 1, e: 'Arabic is written right to left.' },

  // ===== SET B — INDIAN / MALAYALI CULTURAL (35) =====
  // Easy (12)
  { d: 'easy', s: 'cultural', q: 'Which script is used to write Malayalam?', o: ['Devanagari', 'Malayalam script (Brahmic)', 'Tamil script', 'Bengali script'], c: 1, e: 'Malayalam uses its own Brahmic-family script.' },
  { d: 'easy', s: 'cultural', q: 'The Malayalam word "Ente" means what?', o: ['Your', 'My/Mine', 'Our', 'Their'], c: 1, e: '"Ente" means "my" or "mine".' },
  { d: 'easy', s: 'cultural', q: 'The English word "bungalow" originated from which Indian language?', o: ['Tamil', 'Bengali (Bangla)', 'Malayalam', 'Punjabi'], c: 1, e: 'It comes from "bangla", meaning a Bengali-style house.' },
  { d: 'easy', s: 'cultural', q: 'What does "Nanni" mean in Malayalam?', o: ['Sorry', 'Thank you', 'Please', 'Hello'], c: 1, e: '"Nanni" means "thank you".' },
  { d: 'easy', s: 'cultural', q: 'The Malayalam word "Vellam" means what?', o: ['Fire', 'Water', 'Food', 'Wind'], c: 1, e: '"Vellam" means water.' },
  { d: 'easy', s: 'cultural', q: 'In Malayalam, "Aana" refers to which animal?', o: ['Tiger', 'Elephant', 'Horse', 'Cow'], c: 1, e: '"Aana" means elephant.' },
  { d: 'easy', s: 'cultural', q: 'Malayalam is the official language of which Indian state?', o: ['Tamil Nadu', 'Kerala', 'Karnataka', 'Telangana'], c: 1, e: 'Malayalam is Kerala\'s official language.' },
  { d: 'easy', s: 'cultural', q: 'The Malayalam word "Veedu" means what?', o: ['Road', 'House/home', 'Tree', 'River'], c: 1, e: '"Veedu" means house or home.' },
  { d: 'easy', s: 'cultural', q: 'The casual Malayalam term "Chettan" means what?', o: ['Younger sister', 'Elder brother', 'Father', 'Friend'], c: 1, e: '"Chettan/Cheta" addresses an elder brother.' },
  { d: 'easy', s: 'cultural', q: 'The English word "catamaran" comes from a Tamil word meaning what?', o: ['Tied logs/wood', 'Big boat', 'Fishing net', 'Sea wave'], c: 0, e: 'From "kattumaram" — tied (kattu) wood (maram).' },
  { d: 'easy', s: 'cultural', q: 'The Malayalam greeting "Sukhamano?" roughly means what?', o: ['Where are you?', 'Are you well? / How are you?', 'What is your name?', 'Goodbye'], c: 1, e: 'It asks after someone\'s well-being.' },
  { d: 'easy', s: 'cultural', q: 'The Malayalam word "Choru" refers to what?', o: ['Cooked rice', 'Curry', 'Bread', 'Tea'], c: 0, e: '"Choru" means cooked rice/a meal.' },
  // Medium (12)
  { d: 'medium', s: 'cultural', q: 'Malayalam vocabulary is strongly influenced by which two languages?', o: ['Hindi and Urdu', 'Sanskrit and Tamil', 'Arabic and Persian', 'Telugu and Kannada'], c: 1, e: 'Malayalam blends Sanskrit and Tamil heavily.' },
  { d: 'medium', s: 'cultural', q: 'The English word "mango" ultimately derives from a Dravidian word, often given as what?', o: ['Manga', 'Amra', 'Phal', 'Maav'], c: 0, e: 'It comes from "manga" (via Portuguese "manga").' },
  { d: 'medium', s: 'cultural', q: 'The English word "teak" (the wood) comes from the Malayalam word what?', o: ['Thekku', 'Maram', 'Mരം', 'Kayar'], c: 0, e: '"Teak" derives from Malayalam "thekku".' },
  { d: 'medium', s: 'cultural', q: 'Malayalam belongs to which language family?', o: ['Indo-Aryan', 'Dravidian', 'Austroasiatic', 'Sino-Tibetan'], c: 1, e: 'Malayalam is a Dravidian language.' },
  { d: 'medium', s: 'cultural', q: 'The English word "coir" (coconut fibre) comes from the Malayalam/Tamil word what?', o: ['Kayar', 'Thenga', 'Mathi', 'Kappa'], c: 0, e: '"Coir" comes from "kayar", meaning cord/rope.' },
  { d: 'medium', s: 'cultural', q: '"Manglish" refers to what?', o: ['A Malayalam dialect of Mangalore', 'Mixing Malayalam and English', 'Old Malayalam grammar', 'A Malayalam font'], c: 1, e: 'Manglish casually blends Malayalam with English.' },
  { d: 'medium', s: 'cultural', q: 'The common Onam greeting in Malayalam is what?', o: ['Pongal Vazhthukkal', 'Onashamsakal', 'Vishu Ashamsakal', 'Eid Mubarak'], c: 1, e: '"Onashamsakal" means happy Onam wishes.' },
  { d: 'medium', s: 'cultural', q: 'The English word "curry" is widely believed to come from which Dravidian word?', o: ['Kari', 'Masala', 'Sambar', 'Thoran'], c: 0, e: 'From "kari", meaning a sauce or relish.' },
  { d: 'medium', s: 'cultural', q: 'The Malayalam word "Nadan" means what?', o: ['Foreign', 'Local/native', 'Modern', 'Expensive'], c: 1, e: '"Nadan" means native or local (e.g., nadan food).' },
  { d: 'medium', s: 'cultural', q: 'The word "pukka/pucca", meaning solid or proper, entered English from which language?', o: ['Tamil', 'Hindi', 'Bengali', 'Marathi'], c: 1, e: '"Pucca" comes from Hindi, meaning ripe/solid.' },
  { d: 'medium', s: 'cultural', q: 'The Malayalam word "Paal" means what?', o: ['Water', 'Milk', 'Oil', 'Honey'], c: 1, e: '"Paal" means milk.' },
  { d: 'medium', s: 'cultural', q: 'In Malayalam, the polite term "Namaskaram" is used for what?', o: ['Goodbye only', 'A respectful greeting/salutation', 'An apology', 'A toast'], c: 1, e: 'It is a respectful Sanskrit-derived greeting.' },
  // Hard (11)
  { d: 'hard', s: 'cultural', q: 'In 2013, Malayalam was officially granted which special status by India?', o: ['Scheduled language', 'Classical Language', 'Link language', 'Associate language'], c: 1, e: 'Malayalam was declared a Classical Language in 2013.' },
  { d: 'hard', s: 'cultural', q: 'Malayalam is most closely related to which neighbouring Dravidian language?', o: ['Telugu', 'Tamil', 'Kannada', 'Tulu'], c: 1, e: 'Malayalam diverged from Tamil and is closest to it.' },
  { d: 'hard', s: 'cultural', q: 'Thunchaththu Ezhuthachan is credited with reforming the Malayalam what?', o: ['Cuisine', 'Script/alphabet', 'Calendar', 'Music'], c: 1, e: 'He systematized the modern Malayalam script.' },
  { d: 'hard', s: 'cultural', q: 'The word "anaconda" may derive from a Tamil/Malayalam phrase meaning what?', o: ['Water snake', 'Elephant killer', 'Long rope', 'Forest god'], c: 1, e: 'It is linked to "anai-kondra" (elephant killer).' },
  { d: 'hard', s: 'cultural', q: 'The English word "betel" (the leaf) comes from the Malayalam word what?', o: ['Vettila', 'Adakka', 'Cheru', 'Pakku'], c: 0, e: '"Betel" derives from Malayalam "vettila".' },
  { d: 'hard', s: 'cultural', q: 'The Malayalam script developed from which earlier scripts?', o: ['Devanagari', 'Grantha and Vatteluttu (from Brahmi)', 'Kharosthi', 'Sharada'], c: 1, e: 'It evolved from Grantha and Vatteluttu, both Brahmi-derived.' },
  { d: 'hard', s: 'cultural', q: 'The English word "cheroot" (a cigar) comes from a Tamil/Malayalam word meaning what?', o: ['Smoke', 'A roll', 'Tobacco leaf', 'Fire'], c: 1, e: 'From "churuttu", meaning something rolled.' },
  { d: 'hard', s: 'cultural', q: 'Like other Indian abugidas, Malayalam is written in which direction?', o: ['Right to left', 'Left to right', 'Top to bottom', 'Boustrophedon'], c: 1, e: 'Malayalam is written left to right.' },
  { d: 'hard', s: 'cultural', q: 'The honorific suffix "-ji" used across India (as in "Gandhiji") originates mainly from which language?', o: ['Tamil', 'Hindi/North Indian languages', 'Malayalam', 'Bengali'], c: 1, e: 'The respectful "-ji" comes from Hindi/Hindustani.' },
  { d: 'hard', s: 'cultural', q: 'The English word "veranda" is generally traced to which origin via Indian usage?', o: ['Hindi/Bengali (and Portuguese)', 'Japanese', 'Arabic only', 'Greek'], c: 0, e: 'It spread into English through Indian "varanda".' },
  { d: 'hard', s: 'cultural', q: 'The Malayalam exclamation "Ayyo" generally expresses what?', o: ['Joy only', 'Dismay, surprise or sympathy', 'A greeting', 'Agreement'], c: 1, e: '"Ayyo" conveys alarm, sympathy or surprise.' },
];
