// Topic: Mathematics — 70 questions (all classic; Wave 1 problems/concepts, Wave 2 mathematicians & Indian math)
export default [
  // ===== WAVE 1 — CONCEPTS & PROBLEMS (35) =====
  // Easy (12)
  { d: 'easy', s: 'classic', q: 'What is 7 × 8?', o: ['54', '56', '64', '48'], c: 1, e: '7 times 8 is 56.' },
  { d: 'easy', s: 'classic', q: 'How many sides does a triangle have?', o: ['2', '3', '4', '5'], c: 1, e: 'A triangle has three sides.' },
  { d: 'easy', s: 'classic', q: 'What is 100 ÷ 4?', o: ['20', '25', '30', '40'], c: 1, e: '100 divided by 4 is 25.' },
  { d: 'easy', s: 'classic', q: 'The value of pi (π) is approximately what?', o: ['2.14', '3.14', '4.13', '3.41'], c: 1, e: 'Pi is about 3.14159.' },
  { d: 'easy', s: 'classic', q: 'What is 15 + 27?', o: ['41', '42', '43', '52'], c: 1, e: '15 plus 27 equals 42.' },
  { d: 'easy', s: 'classic', q: 'A right angle measures how many degrees?', o: ['45', '90', '180', '360'], c: 1, e: 'A right angle is 90 degrees.' },
  { d: 'easy', s: 'classic', q: 'How many sides does a hexagon have?', o: ['5', '6', '7', '8'], c: 1, e: 'A hexagon has six sides.' },
  { d: 'easy', s: 'classic', q: 'What is 9 squared (9²)?', o: ['18', '72', '81', '99'], c: 2, e: '9 × 9 = 81.' },
  { d: 'easy', s: 'classic', q: 'The interior angles of any triangle add up to how many degrees?', o: ['90', '180', '270', '360'], c: 1, e: 'They always sum to 180°.' },
  { d: 'easy', s: 'classic', q: 'What is 12 × 12?', o: ['124', '132', '144', '154'], c: 2, e: '12 times 12 is 144.' },
  { d: 'easy', s: 'classic', q: 'Which of these is an even number?', o: ['7', '11', '14', '9'], c: 2, e: '14 is divisible by 2.' },
  { d: 'easy', s: 'classic', q: 'What is half of 50?', o: ['15', '20', '25', '30'], c: 2, e: 'Half of 50 is 25.' },
  // Medium (12)
  { d: 'medium', s: 'classic', q: 'What is the square root of 144?', o: ['11', '12', '13', '14'], c: 1, e: '12 × 12 = 144.' },
  { d: 'medium', s: 'classic', q: 'The Pythagorean theorem states a² + b² = ?', o: ['c', 'c²', '2c', 'ab'], c: 1, e: 'In a right triangle, a² + b² = c².' },
  { d: 'medium', s: 'classic', q: 'What is 20% of 200?', o: ['20', '40', '50', '60'], c: 1, e: '20% of 200 is 40.' },
  { d: 'medium', s: 'classic', q: 'A polygon with eight sides is called what?', o: ['Heptagon', 'Octagon', 'Nonagon', 'Decagon'], c: 1, e: 'An octagon has eight sides.' },
  { d: 'medium', s: 'classic', q: 'How many degrees are in a full circle?', o: ['180', '270', '360', '400'], c: 2, e: 'A circle contains 360 degrees.' },
  { d: 'medium', s: 'classic', q: 'What is 3 cubed (3³)?', o: ['9', '18', '27', '81'], c: 2, e: '3 × 3 × 3 = 27.' },
  { d: 'medium', s: 'classic', q: 'Which of these is a prime number?', o: ['9', '15', '17', '21'], c: 2, e: '17 has no divisors other than 1 and itself.' },
  { d: 'medium', s: 'classic', q: 'What is the perimeter of a square with a side of 5 units?', o: ['10', '15', '20', '25'], c: 2, e: 'Perimeter = 4 × 5 = 20.' },
  { d: 'medium', s: 'classic', q: 'What is 2 to the power of 10 (2¹⁰)?', o: ['512', '1000', '1024', '2048'], c: 2, e: '2¹⁰ = 1024.' },
  { d: 'medium', s: 'classic', q: 'The area of a rectangle equals length times what?', o: ['Height', 'Width', 'Diagonal', 'Perimeter'], c: 1, e: 'Area = length × width.' },
  { d: 'medium', s: 'classic', q: 'In statistics, the "median" of a data set is what?', o: ['The average', 'The middle value', 'The most frequent value', 'The range'], c: 1, e: 'The median is the middle value when ordered.' },
  { d: 'medium', s: 'classic', q: 'What is the next prime number after 7?', o: ['8', '9', '11', '13'], c: 2, e: '11 is the next prime after 7.' },
  // Hard (11)
  { d: 'hard', s: 'classic', q: 'The mathematical constant "e" is approximately equal to what?', o: ['1.618', '2.718', '3.142', '1.414'], c: 1, e: 'Euler\'s number e ≈ 2.718.' },
  { d: 'hard', s: 'classic', q: 'The interior angles of a pentagon sum to how many degrees?', o: ['360', '450', '540', '720'], c: 2, e: 'A pentagon\'s angles total 540°.' },
  { d: 'hard', s: 'classic', q: 'What is the derivative of x² with respect to x?', o: ['x', '2x', 'x³/3', '2'], c: 1, e: 'd/dx (x²) = 2x.' },
  { d: 'hard', s: 'classic', q: 'In the Fibonacci sequence 1, 1, 2, 3, 5, 8, ..., what comes next?', o: ['11', '12', '13', '15'], c: 2, e: '5 + 8 = 13.' },
  { d: 'hard', s: 'classic', q: 'What is log base 10 of 1000?', o: ['2', '3', '10', '100'], c: 1, e: '10³ = 1000, so log₁₀(1000) = 3.' },
  { d: 'hard', s: 'classic', q: 'The area of a circle is given by which formula?', o: ['2πr', 'πr²', 'πd', 'r²'], c: 1, e: 'Area = π × r².' },
  { d: 'hard', s: 'classic', q: 'What is the value of 0! (zero factorial)?', o: ['0', '1', 'Undefined', 'Infinity'], c: 1, e: 'By definition, 0! = 1.' },
  { d: 'hard', s: 'classic', q: 'The golden ratio is approximately equal to what?', o: ['1.414', '1.618', '2.718', '3.142'], c: 1, e: 'The golden ratio φ ≈ 1.618.' },
  { d: 'hard', s: 'classic', q: 'A "googol" is the number 10 raised to which power?', o: ['10', '50', '100', '1000'], c: 2, e: 'A googol is 10¹⁰⁰.' },
  { d: 'hard', s: 'classic', q: 'In a right triangle, the longest side opposite the right angle is called what?', o: ['Adjacent', 'Hypotenuse', 'Opposite', 'Base'], c: 1, e: 'The hypotenuse is the longest side.' },
  { d: 'hard', s: 'classic', q: 'A number divisible only by 1 and itself is called a what?', o: ['Composite', 'Prime', 'Perfect', 'Rational'], c: 1, e: 'Such numbers are prime numbers.' },

  // ===== WAVE 2 — MATHEMATICIANS & INDIAN MATH (35) =====
  // Easy (12)
  { d: 'easy', s: 'classic', q: 'Which ancient Greek is famous for a theorem about right triangles?', o: ['Euclid', 'Pythagoras', 'Archimedes', 'Plato'], c: 1, e: 'The Pythagorean theorem bears his name.' },
  { d: 'easy', s: 'classic', q: 'Which Indian mathematician is called "The Man Who Knew Infinity"?', o: ['Aryabhata', 'Srinivasa Ramanujan', 'Bhaskara', 'Brahmagupta'], c: 1, e: 'Ramanujan inspired the book and film by that name.' },
  { d: 'easy', s: 'classic', q: 'The concept of zero as a number is widely credited to which civilization?', o: ['Greece', 'India', 'Rome', 'Egypt'], c: 1, e: 'Indian mathematicians formalized zero.' },
  { d: 'easy', s: 'classic', q: 'Aryabhata was a famous ancient Indian what?', o: ['Poet', 'Mathematician-astronomer', 'King', 'Painter'], c: 1, e: 'Aryabhata was a mathematician and astronomer.' },
  { d: 'easy', s: 'classic', q: 'Calculus was independently developed by Isaac Newton and whom?', o: ['Gottfried Leibniz', 'René Descartes', 'Blaise Pascal', 'Pierre Fermat'], c: 0, e: 'Newton and Leibniz both developed calculus.' },
  { d: 'easy', s: 'classic', q: 'Euclid is celebrated as the father of which branch of math?', o: ['Algebra', 'Geometry', 'Calculus', 'Statistics'], c: 1, e: 'Euclid wrote "Elements", the basis of geometry.' },
  { d: 'easy', s: 'classic', q: 'The digits 0–9 we use today are called what numerals?', o: ['Roman', 'Hindu-Arabic', 'Greek', 'Babylonian'], c: 1, e: 'They are Hindu-Arabic numerals.' },
  { d: 'easy', s: 'classic', q: 'Srinivasa Ramanujan was born in which country?', o: ['England', 'India', 'Greece', 'Egypt'], c: 1, e: 'Ramanujan was born in Tamil Nadu, India.' },
  { d: 'easy', s: 'classic', q: 'Carl Friedrich Gauss is nicknamed the "Prince of" what?', o: ['Physicists', 'Mathematicians', 'Astronomers', 'Philosophers'], c: 1, e: 'Gauss is called the "Prince of Mathematicians".' },
  { d: 'easy', s: 'classic', q: 'Pi (π) is the ratio of a circle\'s circumference to its what?', o: ['Radius', 'Diameter', 'Area', 'Chord'], c: 1, e: 'π = circumference ÷ diameter.' },
  { d: 'easy', s: 'classic', q: 'The place-value decimal system spread to the world largely from where?', o: ['Greece', 'India', 'China', 'Persia'], c: 1, e: 'India\'s decimal place-value system spread via Arab scholars.' },
  { d: 'easy', s: 'classic', q: 'Which mathematician proved many results on circles, levers and buoyancy in ancient Greece?', o: ['Archimedes', 'Thales', 'Zeno', 'Hippocrates'], c: 0, e: 'Archimedes made famous discoveries in geometry and physics.' },
  // Medium (12)
  { d: 'medium', s: 'classic', q: 'Ramanujan famously collaborated with which British mathematician?', o: ['Alan Turing', 'G. H. Hardy', 'Bertrand Russell', 'Isaac Newton'], c: 1, e: 'Hardy brought Ramanujan to Cambridge.' },
  { d: 'medium', s: 'classic', q: 'The "Ramanujan number" 1729 is the smallest number expressible as what?', o: ['A perfect square', 'A sum of two cubes in two ways', 'A prime times two', 'A factorial'], c: 1, e: '1729 = 1³+12³ = 9³+10³.' },
  { d: 'medium', s: 'classic', q: 'Aryabhata gave a remarkably accurate approximation of which constant?', o: ['e', 'Pi (π)', 'The golden ratio', 'Square root of 2'], c: 1, e: 'Aryabhata approximated π to several decimals.' },
  { d: 'medium', s: 'classic', q: 'Aryabhata correctly proposed that the Earth does what?', o: ['Is flat', 'Rotates on its axis', 'Is the center of all orbits', 'Stands still'], c: 1, e: 'He proposed the Earth\'s daily rotation.' },
  { d: 'medium', s: 'classic', q: 'Brahmagupta was the first to give clear rules for arithmetic with what?', o: ['Fractions', 'Zero and negative numbers', 'Imaginary numbers', 'Logarithms'], c: 1, e: 'Brahmagupta formalized rules for zero and negatives.' },
  { d: 'medium', s: 'classic', q: 'The number "e" is named after which mathematician?', o: ['Euclid', 'Leonhard Euler', 'Évariste Galois', 'Eratosthenes'], c: 1, e: 'Euler\'s number is named for Leonhard Euler.' },
  { d: 'medium', s: 'classic', q: 'The Indian mathematician Bhaskara II wrote which famous treatise?', o: ['Lilavati', 'Elements', 'Principia', 'Almagest'], c: 0, e: 'Bhaskara II authored "Lilavati".' },
  { d: 'medium', s: 'classic', q: 'Fermat\'s Last Theorem was finally proved in the 1990s by whom?', o: ['Andrew Wiles', 'Grigori Perelman', 'Terence Tao', 'John Nash'], c: 0, e: 'Andrew Wiles proved it in 1994.' },
  { d: 'medium', s: 'classic', q: 'The Fields Medal is the highest honor in which field?', o: ['Physics', 'Mathematics', 'Chemistry', 'Economics'], c: 1, e: 'The Fields Medal is mathematics\' top prize.' },
  { d: 'medium', s: 'classic', q: 'Which Indian-origin mathematician won the 2014 Fields Medal?', o: ['Manjul Bhargava', 'C. R. Rao', 'Harish-Chandra', 'S. R. S. Varadhan'], c: 0, e: 'Manjul Bhargava won the Fields Medal in 2014.' },
  { d: 'medium', s: 'classic', q: 'The triangular array of binomial coefficients is named after whom?', o: ['Pascal', 'Newton', 'Fermat', 'Euler'], c: 0, e: 'It is Pascal\'s triangle.' },
  { d: 'medium', s: 'classic', q: 'Which mathematician introduced the foundations of modern "set theory"?', o: ['Georg Cantor', 'David Hilbert', 'Kurt Gödel', 'Bertrand Russell'], c: 0, e: 'Georg Cantor founded set theory.' },
  // Hard (11)
  { d: 'hard', s: 'classic', q: 'The famous Riemann Hypothesis concerns the distribution of what?', o: ['Perfect numbers', 'Prime numbers', 'Irrational numbers', 'Complex roots of unity'], c: 1, e: 'It relates to the distribution of primes.' },
  { d: 'hard', s: 'classic', q: 'Aryabhata\'s seminal mathematical-astronomical work is titled what?', o: ['Aryabhatiya', 'Lilavati', 'Brahmasphutasiddhanta', 'Ganitasara'], c: 0, e: 'The Aryabhatiya is his major work.' },
  { d: 'hard', s: 'classic', q: 'Ramanujan\'s legendary notebooks contained thousands of what?', o: ['Poems', 'Mathematical formulas and theorems', 'Letters', 'Maps'], c: 1, e: 'They held thousands of original results.' },
  { d: 'hard', s: 'classic', q: 'Euler\'s identity elegantly links e, i, π, 1 and which other number?', o: ['2', '0', '10', '-1'], c: 1, e: 'e^(iπ) + 1 = 0 includes 0.' },
  { d: 'hard', s: 'classic', q: 'A Mersenne prime is a prime of which form?', o: ['2ⁿ − 1', 'n² + 1', '2ⁿ + 1', 'n! − 1'], c: 0, e: 'Mersenne primes have the form 2ⁿ − 1.' },
  { d: 'hard', s: 'classic', q: 'Gödel\'s famous "incompleteness theorems" belong to which area?', o: ['Geometry', 'Mathematical logic', 'Number theory', 'Topology'], c: 1, e: 'They are landmark results in logic.' },
  { d: 'hard', s: 'classic', q: 'The number pi (π) has been proven to be what kind of number?', o: ['Rational', 'Irrational', 'Imaginary', 'Whole'], c: 1, e: 'π is irrational (and transcendental).' },
  { d: 'hard', s: 'classic', q: 'The "P versus NP" problem is a major open question in which field?', o: ['Statistics', 'Computational complexity', 'Geometry', 'Calculus'], c: 1, e: 'P vs NP is central to theoretical computer science.' },
  { d: 'hard', s: 'classic', q: 'Manjul Bhargava, a Fields Medalist, is of which heritage?', o: ['Indian', 'Chinese', 'Russian', 'Greek'], c: 0, e: 'Bhargava is a Canadian-American of Indian descent.' },
  { d: 'hard', s: 'classic', q: 'Which constant did Indian-born mathematician work tie to "mock theta functions"?', o: ['Ramanujan', 'Aryabhata', 'Bhaskara', 'Brahmagupta'], c: 0, e: 'Ramanujan introduced mock theta functions late in life.' },
  { d: 'hard', s: 'classic', q: 'Grigori Perelman famously solved which Millennium Prize problem?', o: ['Poincaré Conjecture', 'Riemann Hypothesis', 'Hodge Conjecture', 'P vs NP'], c: 0, e: 'Perelman proved the Poincaré Conjecture.' },
];
