// Topic: Movies & TV — 70 questions (35 classic + 35 cultural)
export default [
  // ===== SET A — CLASSIC / GLOBAL (35) =====
  // Easy (12)
  { d: 'easy', s: 'classic', q: 'Who directed the 1993 blockbuster "Jurassic Park"?', o: ['George Lucas', 'Steven Spielberg', 'James Cameron', 'Ridley Scott'], c: 1, e: 'Spielberg brought dinosaurs to life in Jurassic Park.' },
  { d: 'easy', s: 'classic', q: 'Which superhero is the alter ego of Bruce Wayne?', o: ['Superman', 'Batman', 'Spider-Man', 'Iron Man'], c: 1, e: 'Bruce Wayne fights crime as Batman.' },
  { d: 'easy', s: 'classic', q: '"May the Force be with you" is a famous line from which franchise?', o: ['Star Trek', 'Star Wars', 'Dune', 'Guardians of the Galaxy'], c: 1, e: 'It is the signature blessing of Star Wars.' },
  { d: 'easy', s: 'classic', q: 'Who played Jack in the 1997 film "Titanic"?', o: ['Brad Pitt', 'Leonardo DiCaprio', 'Tom Cruise', 'Matt Damon'], c: 1, e: 'DiCaprio played Jack opposite Kate Winslet.' },
  { d: 'easy', s: 'classic', q: 'What is the name of the lion cub hero in "The Lion King"?', o: ['Mufasa', 'Simba', 'Nala', 'Scar'], c: 1, e: 'Simba grows up to reclaim Pride Rock.' },
  { d: 'easy', s: 'classic', q: 'Marvel\'s flagship superhero team is called what?', o: ['The Justice League', 'The Avengers', 'The X-Men', 'The Defenders'], c: 1, e: 'Earth\'s Mightiest Heroes are the Avengers.' },
  { d: 'easy', s: 'classic', q: '"I\'ll be back" is an iconic line from which film?', o: ['Predator', 'The Terminator', 'RoboCop', 'Total Recall'], c: 1, e: 'Arnold Schwarzenegger\'s Terminator says it.' },
  { d: 'easy', s: 'classic', q: 'What is the name of the snowman in Disney\'s "Frozen"?', o: ['Sven', 'Olaf', 'Kristoff', 'Marshmallow'], c: 1, e: 'Olaf is the cheerful, summer-loving snowman.' },
  { d: 'easy', s: 'classic', q: 'In "Harry Potter", what is the wizarding school called?', o: ['Durmstrang', 'Hogwarts', 'Beauxbatons', 'Ilvermorny'], c: 1, e: 'Hogwarts School of Witchcraft and Wizardry.' },
  { d: 'easy', s: 'classic', q: 'Tony Stark is the secret identity of which hero?', o: ['Hulk', 'Iron Man', 'Thor', 'Captain America'], c: 1, e: 'Genius billionaire Tony Stark is Iron Man.' },
  { d: 'easy', s: 'classic', q: 'Who is Disney\'s famous mouse mascot?', o: ['Jerry', 'Mickey Mouse', 'Stuart', 'Speedy'], c: 1, e: 'Mickey Mouse debuted in 1928.' },
  { d: 'easy', s: 'classic', q: 'What is the name of the cowboy doll in "Toy Story"?', o: ['Buzz', 'Woody', 'Rex', 'Hamm'], c: 1, e: 'Sheriff Woody leads Andy\'s toys.' },
  // Medium (12)
  { d: 'medium', s: 'classic', q: 'Who directed "Pulp Fiction" (1994)?', o: ['Martin Scorsese', 'Quentin Tarantino', 'Coen Brothers', 'David Fincher'], c: 1, e: 'Tarantino\'s nonlinear crime film became a classic.' },
  { d: 'medium', s: 'classic', q: 'Which 1997 film tied the record with 11 Academy Awards?', o: ['Titanic', 'Forrest Gump', 'Gladiator', 'Braveheart'], c: 0, e: 'Titanic won 11 Oscars, including Best Picture.' },
  { d: 'medium', s: 'classic', q: 'Who plays Captain Jack Sparrow in "Pirates of the Caribbean"?', o: ['Orlando Bloom', 'Johnny Depp', 'Geoffrey Rush', 'Javier Bardem'], c: 1, e: 'Johnny Depp\'s Jack Sparrow defined the franchise.' },
  { d: 'medium', s: 'classic', q: 'Keanu Reeves stars as Neo in which film series?', o: ['Blade Runner', 'The Matrix', 'Tron', 'Minority Report'], c: 1, e: 'Neo is "The One" in The Matrix.' },
  { d: 'medium', s: 'classic', q: 'Who directed "Inception" (2010)?', o: ['Christopher Nolan', 'Denis Villeneuve', 'Ridley Scott', 'Alfonso Cuarón'], c: 0, e: 'Nolan\'s dream-heist thriller is Inception.' },
  { d: 'medium', s: 'classic', q: 'Pixar\'s "Finding Nemo" centers on what kind of fish?', o: ['Goldfish', 'Clownfish', 'Pufferfish', 'Angelfish'], c: 1, e: 'Marlin searches the ocean for his son Nemo, a clownfish.' },
  { d: 'medium', s: 'classic', q: 'Who directed "Avatar" (2009), once the highest-grossing film ever?', o: ['Peter Jackson', 'James Cameron', 'Robert Zemeckis', 'Michael Bay'], c: 1, e: 'James Cameron also directed Titanic and Aliens.' },
  { d: 'medium', s: 'classic', q: 'Who provides the voice of Shrek?', o: ['Eddie Murphy', 'Mike Myers', 'Antonio Banderas', 'John Lithgow'], c: 1, e: 'Mike Myers voices the lovable ogre.' },
  { d: 'medium', s: 'classic', q: 'Who directed "The Godfather" (1972)?', o: ['Martin Scorsese', 'Francis Ford Coppola', 'Sidney Lumet', 'Brian De Palma'], c: 1, e: 'Coppola adapted Mario Puzo\'s mafia epic.' },
  { d: 'medium', s: 'classic', q: 'Tom Hanks won an Oscar for which 1994 role?', o: ['Cast Away', 'Forrest Gump', 'Philadelphia', 'Big'], c: 1, e: 'He played the title role in Forrest Gump.' },
  { d: 'medium', s: 'classic', q: 'Who played the Joker in 2019\'s "Joker"?', o: ['Heath Ledger', 'Joaquin Phoenix', 'Jared Leto', 'Jack Nicholson'], c: 1, e: 'Joaquin Phoenix won an Oscar for the role.' },
  { d: 'medium', s: 'classic', q: 'Which studio produced the "Toy Story" films?', o: ['DreamWorks', 'Pixar', 'Illumination', 'Blue Sky'], c: 1, e: 'Pixar\'s Toy Story (1995) was the first fully CGI feature.' },
  // Hard (11)
  { d: 'hard', s: 'classic', q: 'Which film won the very first Academy Award for Best Picture (1929)?', o: ['Wings', 'Sunrise', 'The Jazz Singer', 'Metropolis'], c: 0, e: '"Wings" won the inaugural Best Picture Oscar.' },
  { d: 'hard', s: 'classic', q: 'Who directed "Parasite", the 2020 Best Picture winner?', o: ['Park Chan-wook', 'Bong Joon-ho', 'Hirokazu Kore-eda', 'Lee Chang-dong'], c: 1, e: 'Bong Joon-ho\'s Parasite was the first non-English Best Picture.' },
  { d: 'hard', s: 'classic', q: 'In filmmaking, what does the abbreviation "DOP" stand for?', o: ['Director of Photography', 'Department of Production', 'Digital Output Path', 'Dolby Optical Print'], c: 0, e: 'The DOP heads the camera and lighting crew.' },
  { d: 'hard', s: 'classic', q: 'Who directed, produced and starred in "Citizen Kane" (1941)?', o: ['Orson Welles', 'Alfred Hitchcock', 'John Ford', 'Frank Capra'], c: 0, e: 'Welles was 25 when he made Citizen Kane.' },
  { d: 'hard', s: 'classic', q: 'Who played Hannibal Lecter in "The Silence of the Lambs"?', o: ['Gary Oldman', 'Anthony Hopkins', 'Robert De Niro', 'Al Pacino'], c: 1, e: 'Hopkins won Best Actor with limited screen time.' },
  { d: 'hard', s: 'classic', q: 'What single word is the famous dying line in "Citizen Kane"?', o: ['Rosebud', 'Mother', 'Snowfall', 'Goodbye'], c: 0, e: '"Rosebud" drives the film\'s mystery.' },
  { d: 'hard', s: 'classic', q: 'Director Akira Kurosawa was from which country?', o: ['China', 'Japan', 'South Korea', 'Thailand'], c: 1, e: 'Kurosawa was a legendary Japanese filmmaker.' },
  { d: 'hard', s: 'classic', q: 'Ethan Hunt is the lead character in which film franchise?', o: ['John Wick', 'Mission: Impossible', 'Bourne', 'Kingsman'], c: 1, e: 'Tom Cruise plays Ethan Hunt in Mission: Impossible.' },
  { d: 'hard', s: 'classic', q: 'The 1957 classic "12 Angry Men" takes place almost entirely in what setting?', o: ['A courtroom', 'A jury deliberation room', 'A prison', 'A police station'], c: 1, e: 'Twelve jurors debate a verdict in one room.' },
  { d: 'hard', s: 'classic', q: 'Who directed "Schindler\'s List" (1993)?', o: ['Steven Spielberg', 'Roman Polanski', 'Oliver Stone', 'Sydney Pollack'], c: 0, e: 'Spielberg won Best Director for the Holocaust drama.' },
  { d: 'hard', s: 'classic', q: 'Which film won Best Picture at the 2024 Oscars?', o: ['Barbie', 'Oppenheimer', 'Poor Things', 'Killers of the Flower Moon'], c: 1, e: 'Nolan\'s Oppenheimer swept the 96th Academy Awards.' },

  // ===== SET B — INDIAN / MALAYALI CULTURAL (35) =====
  // Easy (12)
  { d: 'easy', s: 'cultural', q: '"Manjummel Boys" (2024) is set around which famous caves?', o: ['Edakkal Caves', 'Guna Caves', 'Ajanta Caves', 'Borra Caves'], c: 1, e: 'The film recreates a rescue at the Guna Caves, Kodaikanal.' },
  { d: 'easy', s: 'cultural', q: 'Who is the lead actor of the 2024 hit "Aavesham"?', o: ['Tovino Thomas', 'Fahadh Faasil', 'Dulquer Salmaan', 'Nivin Pauly'], c: 1, e: 'Fahadh Faasil plays the gangster Ranga.' },
  { d: 'easy', s: 'cultural', q: 'Who directed the superhero film "Minnal Murali"?', o: ['Basil Joseph', 'Lijo Jose Pellissery', 'Aashiq Abu', 'Jeo Baby'], c: 0, e: 'Basil Joseph directed the Tovino Thomas superhero hit.' },
  { d: 'easy', s: 'cultural', q: 'Who directed the Shah Rukh Khan blockbuster "Jawan"?', o: ['Rohit Shetty', 'Atlee', 'Siddharth Anand', 'Ali Abbas Zafar'], c: 1, e: 'Tamil director Atlee made his Hindi debut with Jawan.' },
  { d: 'easy', s: 'cultural', q: 'Who is the lead actor of "KGF: Chapter 2"?', o: ['Prabhas', 'Yash', 'Allu Arjun', 'Vijay Deverakonda'], c: 1, e: 'Yash plays Rocky in the KGF saga.' },
  { d: 'easy', s: 'cultural', q: 'Who directed the magnum opus "RRR"?', o: ['S. S. Rajamouli', 'Prashanth Neel', 'Sukumar', 'Nag Ashwin'], c: 0, e: 'Rajamouli directed the period action epic RRR.' },
  { d: 'easy', s: 'cultural', q: 'Which 2023 film marked Shah Rukh Khan\'s big-screen comeback after four years?', o: ['Dunki', 'Pathaan', 'Jawan', 'Zero'], c: 1, e: 'Pathaan (Jan 2023) ended SRK\'s post-Zero hiatus.' },
  { d: 'easy', s: 'cultural', q: '"Bramayugam" (2024) was presented entirely in what visual style?', o: ['Sepia tone', 'Black and white', 'Saturated color', 'Hand-drawn'], c: 1, e: 'Rahul Sadasivan shot the folk horror in black and white.' },
  { d: 'easy', s: 'cultural', q: 'Who directed the 2024 romcom "Premalu"?', o: ['Girish AD', 'Khalid Rahman', 'Vineeth Sreenivasan', 'Omar Lulu'], c: 0, e: 'Girish AD directed the hit campus romance.' },
  { d: 'easy', s: 'cultural', q: 'Who is the lead actor of the film "Lucifer" (2019)?', o: ['Mammootty', 'Mohanlal', 'Prithviraj', 'Suresh Gopi'], c: 1, e: 'Mohanlal stars as Stephen Nedumpally in Lucifer.' },
  { d: 'easy', s: 'cultural', q: 'Who plays the lead in "Aadujeevitham" (The Goat Life)?', o: ['Fahadh Faasil', 'Prithviraj Sukumaran', 'Tovino Thomas', 'Asif Ali'], c: 1, e: 'Prithviraj transformed physically to play Najeeb.' },
  { d: 'easy', s: 'cultural', q: 'Who directed the franchise-launching epic "Baahubali"?', o: ['Shankar', 'S. S. Rajamouli', 'Gautham Menon', 'Mani Ratnam'], c: 1, e: 'Rajamouli\'s Baahubali changed Indian cinema scale.' },
  // Medium (12)
  { d: 'medium', s: 'cultural', q: 'Who directed "Manjummel Boys"?', o: ['Chidambaram', 'Khalid Rahman', 'Lijo Jose Pellissery', 'Mahesh Narayanan'], c: 0, e: 'Chidambaram S. Poduval directed the survival thriller.' },
  { d: 'medium', s: 'cultural', q: 'The web series "Scam 1992" is based on the life of which stockbroker?', o: ['Ketan Parekh', 'Harshad Mehta', 'Nirav Modi', 'Vijay Mallya'], c: 1, e: 'It dramatises Harshad Mehta\'s 1992 securities scam.' },
  { d: 'medium', s: 'cultural', q: 'Who plays the lead in "Bramayugam" (2024)?', o: ['Mohanlal', 'Mammootty', 'Prithviraj', 'Jayaram'], c: 1, e: 'Mammootty plays the sinister Kodumon Potti.' },
  { d: 'medium', s: 'cultural', q: 'Who directed the 2023 film "Dunki" starring Shah Rukh Khan?', o: ['Rajkumar Hirani', 'Anubhav Sinha', 'Imtiaz Ali', 'Sriram Raghavan'], c: 0, e: 'Rajkumar Hirani directed the immigration dramedy Dunki.' },
  { d: 'medium', s: 'cultural', q: 'The disaster film "2018" depicts which natural calamity?', o: ['Gujarat earthquake', 'Kerala floods', 'Chennai floods', 'Uttarakhand floods'], c: 1, e: '"2018" recreates the devastating 2018 Kerala floods.' },
  { d: 'medium', s: 'cultural', q: 'Who is the lead actor of "Pushpa: The Rise"?', o: ['Jr NTR', 'Allu Arjun', 'Ram Charan', 'Mahesh Babu'], c: 1, e: 'Allu Arjun plays Pushpa Raj, the red-sander smuggler.' },
  { d: 'medium', s: 'cultural', q: 'Who directed "Animal" (2023)?', o: ['Sandeep Reddy Vanga', 'Ayan Mukerji', 'Karan Johar', 'Anurag Kashyap'], c: 0, e: 'Sandeep Reddy Vanga directed the Ranbir Kapoor crime drama.' },
  { d: 'medium', s: 'cultural', q: 'Who plays Georgekutty in the "Drishyam" films?', o: ['Mammootty', 'Mohanlal', 'Suresh Gopi', 'Dileep'], c: 1, e: 'Mohanlal\'s Georgekutty outwits the police in Drishyam.' },
  { d: 'medium', s: 'cultural', q: 'Who directed the cult romance "Premam" (2015)?', o: ['Alphonse Puthren', 'Anwar Rasheed', 'Aashiq Abu', 'Vineeth Sreenivasan'], c: 0, e: 'Alphonse Puthren directed the Nivin Pauly hit.' },
  { d: 'medium', s: 'cultural', q: 'Who directed the acclaimed "Kumbalangi Nights" (2019)?', o: ['Madhu C. Narayanan', 'Dileesh Pothan', 'Geetu Mohandas', 'Zakariya'], c: 0, e: 'Madhu C. Narayanan made his debut with Kumbalangi Nights.' },
  { d: 'medium', s: 'cultural', q: 'Who is the lead actor of the kinetic 2022 hit "Thallumaala"?', o: ['Tovino Thomas', 'Antony Varghese', 'Roshan Mathew', 'Shane Nigam'], c: 0, e: 'Tovino Thomas headlines the fight-comedy Thallumaala.' },
  { d: 'medium', s: 'cultural', q: 'Which Malayalam film was India\'s official Oscar entry for 2024?', o: ['2018: Everyone is a Hero', 'Jallikattu', 'Aadujeevitham', 'Manjummel Boys'], c: 0, e: '"2018" was India\'s submission for the 96th Academy Awards.' },
  // Hard (11)
  { d: 'hard', s: 'cultural', q: '"Manjummel Boys" recreates a real rescue at the Guna Caves in which year?', o: ['2001', '2006', '2010', '2015'], c: 1, e: 'The real incident occurred in 2006.' },
  { d: 'hard', s: 'cultural', q: 'What is Mammootty\'s character name in "Bheeshma Parvam"?', o: ['Khureshi-Ab\'raam', 'Michael', 'Stephen', 'David'], c: 1, e: 'Mammootty plays Michael, the family\'s patriarch.' },
  { d: 'hard', s: 'cultural', q: '"Aadujeevitham" is based on a bestselling novel by whom?', o: ['Benyamin', 'M. T. Vasudevan Nair', 'S. Hareesh', 'Subhash Chandran'], c: 0, e: 'Benyamin wrote the acclaimed novel "Aadujeevitham".' },
  { d: 'hard', s: 'cultural', q: 'Mammootty plays the character "Khureshi-Ab\'raam" in which 2024 film?', o: ['Turbo', 'Bramayugam', 'Kannur Squad', 'Christopher'], c: 0, e: 'He plays the action hero Khureshi-Ab\'raam in Turbo.' },
  { d: 'hard', s: 'cultural', q: 'Lijo Jose Pellissery directed which film that was India\'s 2020 Oscar entry?', o: ['Ee.Ma.Yau', 'Jallikattu', 'Angamaly Diaries', 'Churuli'], c: 1, e: 'The buffalo-chase drama Jallikattu was India\'s 2020 entry.' },
  { d: 'hard', s: 'cultural', q: 'Who directed the Drishyam films in Malayalam?', o: ['Jeethu Joseph', 'Lal Jose', 'Sathyan Anthikad', 'Kamal'], c: 0, e: 'Jeethu Joseph wrote and directed both Drishyam films.' },
  { d: 'hard', s: 'cultural', q: 'The period epic "RRR" is set primarily in which decade?', o: ['1900s', '1920s', '1940s', '1950s'], c: 1, e: 'RRR imagines two real freedom fighters in 1920s India.' },
  { d: 'hard', s: 'cultural', q: 'Who directed "Soorarai Pottru", which won multiple National Film Awards?', o: ['Sudha Kongara', 'Pa. Ranjith', 'Vetrimaaran', 'Mani Ratnam'], c: 0, e: 'Sudha Kongara directed the Suriya-led aviation drama.' },
  { d: 'hard', s: 'cultural', q: 'Pathaan and War belong to which shared cinematic universe?', o: ['Cop Universe', 'YRF Spy Universe', 'Lokesh Cinematic Universe', 'Maddock Horror Universe'], c: 1, e: 'Yash Raj Films\' Spy Universe links its action films.' },
  { d: 'hard', s: 'cultural', q: 'Who directed the folk horror "Bramayugam" (2024)?', o: ['Rahul Sadasivan', 'Jeethu Joseph', 'Khalid Rahman', 'Mahesh Narayanan'], c: 0, e: 'Rahul Sadasivan, who also made Bhoothakaalam, directed it.' },
  { d: 'hard', s: 'cultural', q: '"Manjummel Boys" became the highest-grossing Malayalam film, overtaking which earlier hit?', o: ['Lucifer', '2018', 'Pulimurugan', 'Drishyam 2'], c: 1, e: 'It surpassed the disaster epic "2018" at the box office.' },
];
