// Topic: Music — 70 questions (35 classic + 35 cultural)
// Each: d=difficulty, s=source, q=question, o=[A,B,C,D], c=correct index (0-3), e=explanation
export default [
  // ===== SET A — CLASSIC / GLOBAL (35) =====
  // Easy (12)
  { d: 'easy', s: 'classic', q: 'Who was the lead singer of the band Queen?', o: ['Freddie Mercury', 'Brian May', 'Roger Taylor', 'John Deacon'], c: 0, e: 'Freddie Mercury fronted Queen with his iconic four-octave voice.' },
  { d: 'easy', s: 'classic', q: 'Which artist released the best-selling album "Thriller"?', o: ['Prince', 'Michael Jackson', 'Stevie Wonder', 'Lionel Richie'], c: 1, e: '"Thriller" (1982) remains the best-selling album of all time.' },
  { d: 'easy', s: 'classic', q: 'The Beatles formed in which English city?', o: ['London', 'Manchester', 'Liverpool', 'Birmingham'], c: 2, e: 'The Beatles came together in Liverpool in 1960.' },
  { d: 'easy', s: 'classic', q: 'Who sang the 2017 mega-hit "Shape of You"?', o: ['Ed Sheeran', 'Sam Smith', 'Shawn Mendes', 'Justin Bieber'], c: 0, e: '"Shape of You" topped charts worldwide for Ed Sheeran.' },
  { d: 'easy', s: 'classic', q: 'Adele\'s record-breaking 2011 album was titled what?', o: ['19', '21', '25', '30'], c: 1, e: 'Adele names her albums after her age; "21" sold tens of millions.' },
  { d: 'easy', s: 'classic', q: 'What is rapper Eminem\'s real name?', o: ['Marshall Mathers', 'Calvin Broadus', 'Andre Young', 'O\'Shea Jackson'], c: 0, e: 'Marshall Bruce Mathers III performs as Eminem.' },
  { d: 'easy', s: 'classic', q: 'Beyoncé first rose to fame in which group?', o: ['TLC', 'Destiny\'s Child', 'Spice Girls', 'En Vogue'], c: 1, e: 'Beyoncé led Destiny\'s Child before her solo career.' },
  { d: 'easy', s: 'classic', q: 'Who is widely called the "King of Rock and Roll"?', o: ['Chuck Berry', 'Little Richard', 'Elvis Presley', 'Buddy Holly'], c: 2, e: 'Elvis Presley earned the title in the 1950s.' },
  { d: 'easy', s: 'classic', q: 'How many official members did The Beatles have?', o: ['3', '4', '5', '6'], c: 1, e: 'John, Paul, George and Ringo — the Fab Four.' },
  { d: 'easy', s: 'classic', q: 'In which genre did Taylor Swift begin her career?', o: ['Pop', 'Country', 'Rock', 'R&B'], c: 1, e: 'Swift started as a country artist before going pop.' },
  { d: 'easy', s: 'classic', q: '"Bohemian Rhapsody" is a famous song by which band?', o: ['The Who', 'Queen', 'Led Zeppelin', 'The Rolling Stones'], c: 1, e: 'Queen\'s 1975 epic mixes ballad, opera and rock.' },
  { d: 'easy', s: 'classic', q: 'Which country is pop star Rihanna from?', o: ['Jamaica', 'Trinidad', 'Barbados', 'Bahamas'], c: 2, e: 'Rihanna was born in Saint Michael, Barbados.' },
  // Medium (12)
  { d: 'medium', s: 'classic', q: 'Which band released the album "The Dark Side of the Moon"?', o: ['Pink Floyd', 'Genesis', 'Yes', 'King Crimson'], c: 0, e: 'Pink Floyd\'s 1973 classic spent years on the charts.' },
  { d: 'medium', s: 'classic', q: '"Smells Like Teen Spirit" was a breakthrough hit for which band?', o: ['Pearl Jam', 'Soundgarden', 'Nirvana', 'Alice in Chains'], c: 2, e: 'Nirvana\'s 1991 anthem defined grunge.' },
  { d: 'medium', s: 'classic', q: 'Bob Marley is most associated with which music genre?', o: ['Ska', 'Reggae', 'Calypso', 'Soca'], c: 1, e: 'Marley brought Jamaican reggae to the world.' },
  { d: 'medium', s: 'classic', q: 'A standard guitar has how many strings?', o: ['4', '5', '6', '7'], c: 2, e: 'Standard tuning uses six strings: E A D G B E.' },
  { d: 'medium', s: 'classic', q: 'Who recorded the hit single "Rolling in the Deep"?', o: ['Duffy', 'Adele', 'Amy Winehouse', 'Florence Welch'], c: 1, e: 'It was the lead single from Adele\'s "21".' },
  { d: 'medium', s: 'classic', q: 'Which band performed "Hotel California"?', o: ['Eagles', 'Fleetwood Mac', 'Lynyrd Skynyrd', 'The Doobie Brothers'], c: 0, e: 'The Eagles released "Hotel California" in 1976.' },
  { d: 'medium', s: 'classic', q: 'What is Lady Gaga\'s real name?', o: ['Stefani Germanotta', 'Katheryn Hudson', 'Robyn Fenty', 'Alecia Moore'], c: 0, e: 'She was born Stefani Joanne Angelina Germanotta.' },
  { d: 'medium', s: 'classic', q: '"Purple Rain" is an iconic album and film by which artist?', o: ['Prince', 'Rick James', 'David Bowie', 'George Michael'], c: 0, e: 'Prince released "Purple Rain" in 1984.' },
  { d: 'medium', s: 'classic', q: 'The Coachella music festival is held in which US state?', o: ['Nevada', 'Texas', 'California', 'Arizona'], c: 2, e: 'Coachella takes place in Indio, California.' },
  { d: 'medium', s: 'classic', q: 'Who recorded the genre-bending hit "Old Town Road"?', o: ['Post Malone', 'Lil Nas X', 'Childish Gambino', 'Travis Scott'], c: 1, e: 'Lil Nas X\'s 2019 track topped the Hot 100 for 19 weeks.' },
  { d: 'medium', s: 'classic', q: 'Which artist won the 2024 Grammy Album of the Year for "Midnights"?', o: ['Taylor Swift', 'SZA', 'Olivia Rodrigo', 'Miley Cyrus'], c: 0, e: 'Swift made history with her fourth Album of the Year win.' },
  { d: 'medium', s: 'classic', q: 'Michael Jackson is popularly known by which nickname?', o: ['King of Pop', 'The Boss', 'Mr. Showmanship', 'Soul Brother'], c: 0, e: 'He earned the "King of Pop" title in the 1980s.' },
  // Hard (11)
  { d: 'hard', s: 'classic', q: 'Who produced Michael Jackson\'s albums "Off the Wall" and "Thriller"?', o: ['Berry Gordy', 'Quincy Jones', 'Teddy Riley', 'Rodney Jerkins'], c: 1, e: 'Quincy Jones produced MJ\'s biggest solo albums.' },
  { d: 'hard', s: 'classic', q: 'How many completed symphonies did Beethoven write?', o: ['7', '9', '11', '5'], c: 1, e: 'Beethoven completed nine symphonies, the last being the "Choral".' },
  { d: 'hard', s: 'classic', q: 'What does "BPM" stand for in music?', o: ['Bass Per Measure', 'Beats Per Minute', 'Bars Per Movement', 'Bridge Pre Mix'], c: 1, e: 'BPM measures a song\'s tempo.' },
  { d: 'hard', s: 'classic', q: 'In standard concert tuning, the note A above middle C vibrates at what frequency?', o: ['432 Hz', '440 Hz', '480 Hz', '420 Hz'], c: 1, e: 'A4 = 440 Hz is the modern tuning standard.' },
  { d: 'hard', s: 'classic', q: 'A standard full-size piano has how many keys?', o: ['76', '88', '92', '100'], c: 1, e: 'A piano has 88 keys: 52 white and 36 black.' },
  { d: 'hard', s: 'classic', q: 'What was the first music video ever aired on MTV in 1981?', o: ['Billie Jean', 'Video Killed the Radio Star', 'Sweet Dreams', 'Take On Me'], c: 1, e: 'The Buggles\' track fittingly opened MTV.' },
  { d: 'hard', s: 'classic', q: '"Stairway to Heaven" is a landmark song by which band?', o: ['Deep Purple', 'Black Sabbath', 'Led Zeppelin', 'Cream'], c: 2, e: 'Led Zeppelin released it on their 1971 untitled fourth album.' },
  { d: 'hard', s: 'classic', q: 'Which record label did The Beatles found in 1968?', o: ['Apple Records', 'Parlophone', 'Capitol', 'Decca'], c: 0, e: 'Apple Records was the Beatles\' own label.' },
  { d: 'hard', s: 'classic', q: '"The Wall" is a concept album by which band?', o: ['The Police', 'Pink Floyd', 'Rush', 'Supertramp'], c: 1, e: 'Pink Floyd released the double album "The Wall" in 1979.' },
  { d: 'hard', s: 'classic', q: 'In a vinyl single, what is the lesser-promoted second track called?', o: ['The flip', 'The B-side', 'The cut', 'The fade'], c: 1, e: 'The B-side was the reverse face of a 7-inch single.' },
  { d: 'hard', s: 'classic', q: 'Which company is best known for the pitch-correction tool "Auto-Tune"?', o: ['Antares', 'Roland', 'Korg', 'Yamaha'], c: 0, e: 'Antares Audio Technologies released Auto-Tune in 1997.' },

  // ===== SET B — INDIAN / MALAYALI CULTURAL (35) =====
  // Easy (12)
  { d: 'easy', s: 'cultural', q: 'Who composed the music for the 2024 hit "Manjummel Boys"?', o: ['Shaan Rahman', 'Sushin Shyam', 'Vishnu Vijay', 'Gopi Sundar'], c: 1, e: 'Sushin Shyam scored the survival thriller Manjummel Boys.' },
  { d: 'easy', s: 'cultural', q: 'The viral song "Kesariya" is from which 2022 Bollywood film?', o: ['Brahmastra', 'Pathaan', 'Jawan', 'Animal'], c: 0, e: '"Kesariya" featured in Brahmastra: Part One.' },
  { d: 'easy', s: 'cultural', q: 'Which Punjabi artist popularised the viral track "Brown Munde"?', o: ['Diljit Dosanjh', 'AP Dhillon', 'Sidhu Moose Wala', 'Karan Aujla'], c: 1, e: 'AP Dhillon went global with "Brown Munde" in 2020.' },
  { d: 'easy', s: 'cultural', q: 'The high-energy song "Arjan Vailly" is from which 2023 film?', o: ['Jawan', 'Animal', 'Gadar 2', 'Tiger 3'], c: 1, e: '"Arjan Vailly" features in Sandeep Reddy Vanga\'s Animal.' },
  { d: 'easy', s: 'cultural', q: 'Who composed the music for the Fahadh Faasil hit "Aavesham"?', o: ['Sushin Shyam', 'Justin Varghese', 'Vishnu Vijay', 'Jakes Bejoy'], c: 0, e: 'Sushin Shyam delivered Aavesham\'s mass soundtrack.' },
  { d: 'easy', s: 'cultural', q: 'Who composed the music for "Aadujeevitham" (The Goat Life)?', o: ['Ilaiyaraaja', 'A. R. Rahman', 'Harris Jayaraj', 'Yuvan Shankar Raja'], c: 1, e: 'A. R. Rahman scored Blessy\'s The Goat Life.' },
  { d: 'easy', s: 'cultural', q: '"Tum Kya Mile" was a chart-topper from which 2023 film?', o: ['Rocky Aur Rani Kii Prem Kahaani', 'Dunki', 'Jawan', 'Pathaan'], c: 0, e: 'Arijit Singh and Shreya Ghoshal sang it for the Karan Johar film.' },
  { d: 'easy', s: 'cultural', q: 'The Oscar-winning song "Naatu Naatu" is from which film?', o: ['Pushpa', 'RRR', 'KGF 2', 'Baahubali'], c: 1, e: '"Naatu Naatu" from RRR won the Best Original Song Oscar.' },
  { d: 'easy', s: 'cultural', q: 'Who composed the music for the 2024 romcom "Premalu"?', o: ['Vishnu Vijay', 'Sushin Shyam', 'Bijibal', 'Hesham Abdul Wahab'], c: 0, e: 'Vishnu Vijay scored Girish AD\'s Premalu.' },
  { d: 'easy', s: 'cultural', q: 'Singer-actor Diljit Dosanjh primarily performs in which language?', o: ['Hindi', 'Punjabi', 'Tamil', 'Bhojpuri'], c: 1, e: 'Diljit is a leading Punjabi music and film star.' },
  { d: 'easy', s: 'cultural', q: 'The viral love song "Pasoori" first appeared on which show?', o: ['Coke Studio', 'MTV Unplugged', 'The Dewarists', 'Indian Idol'], c: 0, e: '"Pasoori" debuted on Coke Studio Pakistan Season 14.' },
  { d: 'easy', s: 'cultural', q: 'Which singer is fondly called the "Nightingale of India"?', o: ['Asha Bhosle', 'Lata Mangeshkar', 'Shreya Ghoshal', 'Geeta Dutt'], c: 1, e: 'Lata Mangeshkar held the beloved title for decades.' },
  // Medium (12)
  { d: 'medium', s: 'cultural', q: 'Who composed the Oscar-winning "Naatu Naatu"?', o: ['M. M. Keeravani', 'Devi Sri Prasad', 'Anirudh', 'Thaman S'], c: 0, e: 'M. M. Keeravani composed RRR\'s soundtrack.' },
  { d: 'medium', s: 'cultural', q: 'A. R. Rahman won his two Academy Awards for which film?', o: ['Lagaan', 'Slumdog Millionaire', 'Roja', 'Dil Se'], c: 1, e: 'He won Best Score and Best Song ("Jai Ho") for Slumdog Millionaire.' },
  { d: 'medium', s: 'cultural', q: 'The emotional song "Kanmani Anbodu" used in Manjummel Boys is originally from which film?', o: ['Guna', 'Nayakan', 'Anbe Sivam', 'Thalapathi'], c: 0, e: 'The 1991 Kamal Haasan film Guna gave us the classic.' },
  { d: 'medium', s: 'cultural', q: 'A. R. Rahman is popularly nicknamed what?', o: ['Maestro of Madras', 'Mozart of Madras', 'Beethoven of Chennai', 'Bach of Bombay'], c: 1, e: 'The press dubbed him the "Mozart of Madras".' },
  { d: 'medium', s: 'cultural', q: 'Who composed "Kesariya" for Brahmastra?', o: ['Pritam', 'Vishal-Shekhar', 'Amaal Mallik', 'Tanishk Bagchi'], c: 0, e: 'Pritam composed Brahmastra\'s soundtrack.' },
  { d: 'medium', s: 'cultural', q: 'The viral song "Manike Mage Hithe" originated from which country?', o: ['India', 'Sri Lanka', 'Nepal', 'Bangladesh'], c: 1, e: 'Sri Lankan singer Yohani made "Manike" a global hit.' },
  { d: 'medium', s: 'cultural', q: 'Composer Anirudh Ravichander is primarily associated with which film industry?', o: ['Mollywood', 'Tollywood', 'Kollywood (Tamil)', 'Bollywood'], c: 2, e: 'Anirudh is a top Tamil-cinema music director.' },
  { d: 'medium', s: 'cultural', q: 'Shaan Rahman is a well-known music director in which industry?', o: ['Bollywood', 'Malayalam cinema', 'Kollywood', 'Sandalwood'], c: 1, e: 'Shaan Rahman has scored many Malayalam hits.' },
  { d: 'medium', s: 'cultural', q: 'The viral song "Jimikki Kammal" became a sensation from which film?', o: ['Velipadinte Pusthakam', 'Premam', 'Bangalore Days', 'Charlie'], c: 0, e: 'The 2017 Mohanlal film made "Jimikki Kammal" go global.' },
  { d: 'medium', s: 'cultural', q: 'Which duo sang the original "Pasoori" on Coke Studio?', o: ['Atif Aslam & Aima Baig', 'Ali Sethi & Shae Gill', 'Rahat Fateh Ali Khan & Momina', 'Asim Azhar & Hania'], c: 1, e: 'Ali Sethi and Shae Gill performed the original.' },
  { d: 'medium', s: 'cultural', q: 'Vishnu Vijay rose to fame composing for which 2024 romantic hit?', o: ['Premalu', 'Hridayam', 'Thallumaala', 'Kumbalangi Nights'], c: 0, e: 'Premalu\'s soundtrack boosted Vishnu Vijay\'s profile.' },
  { d: 'medium', s: 'cultural', q: 'Which legendary playback singer is celebrated as "Gana Gandharvan" in Kerala?', o: ['P. Jayachandran', 'K. J. Yesudas', 'M. G. Sreekumar', 'G. Venugopal'], c: 1, e: 'K. J. Yesudas earned the "Gana Gandharvan" title.' },
  // Hard (11)
  { d: 'hard', s: 'cultural', q: 'What is the birth name of music maestro A. R. Rahman?', o: ['A. S. Dileep Kumar', 'Allah Rakha Khan', 'A. R. Mohammed', 'Dilip Shankar'], c: 0, e: 'He was born A. S. Dileep Kumar before converting.' },
  { d: 'hard', s: 'cultural', q: 'Composer M. M. Keeravani is a cousin of which famous director?', o: ['S. S. Rajamouli', 'Prashanth Neel', 'Sukumar', 'Trivikram'], c: 0, e: 'Keeravani and Rajamouli are first cousins.' },
  { d: 'hard', s: 'cultural', q: 'Sushin Shyam also scored which acclaimed 2019 Malayalam film?', o: ['Kumbalangi Nights', 'Uyare', 'Lucifer', 'Virus'], c: 0, e: 'Sushin Shyam\'s Kumbalangi Nights score won wide praise.' },
  { d: 'hard', s: 'cultural', q: 'The viral 2011 track "Why This Kolaveri Di" was sung by which actor?', o: ['Vijay', 'Dhanush', 'Simbu', 'Suriya'], c: 1, e: 'Dhanush sang the song from the Tamil film "3".' },
  { d: 'hard', s: 'cultural', q: 'A. R. Rahman composed the music for which Imtiaz Ali film starring Ranbir Kapoor?', o: ['Tamasha', 'Rockstar', 'Highway', 'Love Aaj Kal'], c: 1, e: 'Rahman\'s "Rockstar" (2011) soundtrack became iconic.' },
  { d: 'hard', s: 'cultural', q: 'Legendary composer Ilaiyaraaja is honoured with which title?', o: ['Isaignani', 'Sangeet Samrat', 'Nadabrahmam', 'Swara Raja'], c: 0, e: '"Isaignani" means musical genius/scholar.' },
  { d: 'hard', s: 'cultural', q: 'The composer duo "Vishal–Shekhar" mainly works in which industry?', o: ['Malayalam cinema', 'Bollywood', 'Tamil cinema', 'Telugu cinema'], c: 1, e: 'Vishal Dadlani and Shekhar Ravjiani are Bollywood composers.' },
  { d: 'hard', s: 'cultural', q: 'Which singer is known for the timeless ghazal-style classic "Lag Ja Gale"?', o: ['Asha Bhosle', 'Lata Mangeshkar', 'Noor Jehan', 'Geeta Dutt'], c: 1, e: 'Lata Mangeshkar sang the 1964 classic from Woh Kaun Thi.' },
  { d: 'hard', s: 'cultural', q: 'Pritam Chakraborty is a leading music director in which industry?', o: ['Tollywood', 'Bollywood', 'Mollywood', 'Kollywood'], c: 1, e: 'Pritam is one of Bollywood\'s most prolific composers.' },
  { d: 'hard', s: 'cultural', q: 'Which Kerala-born singer famously sang across Malayalam, Tamil, Hindi and more for over five decades?', o: ['S. P. Balasubrahmanyam', 'K. J. Yesudas', 'Hariharan', 'Unni Menon'], c: 1, e: 'Yesudas has recorded tens of thousands of songs in many languages.' },
  { d: 'hard', s: 'cultural', q: 'Hesham Abdul Wahab composed the acclaimed soundtrack for which 2022 Malayalam blockbuster?', o: ['Hridayam', 'Jana Gana Mana', 'Bheeshma Parvam', 'Nna Thaan Case Kodu'], c: 0, e: 'Hesham\'s music for Hridayam was a chart-topper.' },
];
