// Topic: Mythology — 70 questions (Set A Greek/Norse/Egyptian classic, Set B Indian/Hindu cultural)
export default [
  // ===== SET A — CLASSIC / GLOBAL (35) =====
  // Easy (12)
  { d: 'easy', s: 'classic', q: 'Zeus is the king of the gods in which mythology?', o: ['Norse', 'Greek', 'Egyptian', 'Roman'], c: 1, e: 'Zeus rules the Greek pantheon from Olympus.' },
  { d: 'easy', s: 'classic', q: 'Thor is the god of what in Norse mythology?', o: ['Sea', 'Thunder', 'Wisdom', 'Death'], c: 1, e: 'Thor wields thunder and his hammer.' },
  { d: 'easy', s: 'classic', q: 'Who is the Greek god of the sea?', o: ['Hades', 'Poseidon', 'Apollo', 'Hermes'], c: 1, e: 'Poseidon rules the seas.' },
  { d: 'easy', s: 'classic', q: 'Aphrodite is the Greek goddess of what?', o: ['War', 'Love and beauty', 'Wisdom', 'The hunt'], c: 1, e: 'Aphrodite is the goddess of love.' },
  { d: 'easy', s: 'classic', q: 'Odin is the chief god of which mythology?', o: ['Greek', 'Norse', 'Roman', 'Celtic'], c: 1, e: 'Odin leads the Norse gods.' },
  { d: 'easy', s: 'classic', q: 'What is the name of the winged horse in Greek myth?', o: ['Centaur', 'Pegasus', 'Griffin', 'Chimera'], c: 1, e: 'Pegasus is the famous winged horse.' },
  { d: 'easy', s: 'classic', q: 'Hades rules over which realm?', o: ['The sky', 'The Underworld', 'The sea', 'The forest'], c: 1, e: 'Hades is lord of the Underworld.' },
  { d: 'easy', s: 'classic', q: 'Medusa was a creature with what instead of hair?', o: ['Fire', 'Snakes', 'Feathers', 'Vines'], c: 1, e: 'Medusa\'s hair was made of living snakes.' },
  { d: 'easy', s: 'classic', q: 'Heracles (Hercules) is famous in myth for his great what?', o: ['Wisdom', 'Strength', 'Speed', 'Wealth'], c: 1, e: 'Heracles performed the Twelve Labors with his strength.' },
  { d: 'easy', s: 'classic', q: 'Ares is the Greek god of what?', o: ['Love', 'War', 'The sun', 'The harvest'], c: 1, e: 'Ares is the god of war.' },
  { d: 'easy', s: 'classic', q: 'Cupid is the Roman god of what?', o: ['Love', 'War', 'Wine', 'The sea'], c: 0, e: 'Cupid shoots arrows of love.' },
  { d: 'easy', s: 'classic', q: 'What is the Roman name for the king of the gods?', o: ['Mars', 'Jupiter', 'Neptune', 'Pluto'], c: 1, e: 'Jupiter is the Roman counterpart of Zeus.' },
  // Medium (12)
  { d: 'medium', s: 'classic', q: 'Athena is the Greek goddess of what?', o: ['Wisdom and war strategy', 'Love', 'The sea', 'The moon'], c: 0, e: 'Athena embodies wisdom and strategic warfare.' },
  { d: 'medium', s: 'classic', q: 'Loki is the trickster god of which mythology?', o: ['Greek', 'Norse', 'Egyptian', 'Hindu'], c: 1, e: 'Loki is the Norse trickster.' },
  { d: 'medium', s: 'classic', q: 'The three-headed dog guarding the Underworld is named what?', o: ['Cerberus', 'Fenrir', 'Argus', 'Orthrus'], c: 0, e: 'Cerberus guards the gates of Hades.' },
  { d: 'medium', s: 'classic', q: 'Who is the wandering hero of Homer\'s "Odyssey"?', o: ['Achilles', 'Odysseus', 'Hector', 'Perseus'], c: 1, e: 'Odysseus journeys home in the Odyssey.' },
  { d: 'medium', s: 'classic', q: 'The phrase "Achilles\' heel" refers to his only what?', o: ['Strength', 'Weak point', 'Weapon', 'Friend'], c: 1, e: 'Achilles was vulnerable only at his heel.' },
  { d: 'medium', s: 'classic', q: 'Mars is the Roman god of what?', o: ['War', 'Love', 'Trade', 'The sky'], c: 0, e: 'Mars is the Roman god of war.' },
  { d: 'medium', s: 'classic', q: 'The Minotaur was kept in which structure?', o: ['The Colosseum', 'The Labyrinth', 'The Parthenon', 'The Acropolis'], c: 1, e: 'The Minotaur dwelt in the Labyrinth of Crete.' },
  { d: 'medium', s: 'classic', q: 'Ra was the sun god in which mythology?', o: ['Greek', 'Egyptian', 'Norse', 'Roman'], c: 1, e: 'Ra is the Egyptian sun god.' },
  { d: 'medium', s: 'classic', q: 'What is the name of Thor\'s hammer?', o: ['Gungnir', 'Mjolnir', 'Excalibur', 'Stormbreaker'], c: 1, e: 'Thor wields the hammer Mjolnir.' },
  { d: 'medium', s: 'classic', q: 'Apollo is the Greek god of the sun, music and what else?', o: ['Prophecy', 'War', 'Death', 'Wealth'], c: 0, e: 'Apollo is also the god of prophecy.' },
  { d: 'medium', s: 'classic', q: 'In Greek myth, who opened a jar (box) releasing evils into the world?', o: ['Helen', 'Pandora', 'Persephone', 'Hera'], c: 1, e: 'Pandora\'s curiosity released the world\'s evils.' },
  { d: 'medium', s: 'classic', q: 'Which Roman goddess of love corresponds to the Greek Aphrodite?', o: ['Juno', 'Venus', 'Diana', 'Minerva'], c: 1, e: 'Venus is the Roman goddess of love.' },
  // Hard (11)
  { d: 'hard', s: 'classic', q: 'The jackal-headed Egyptian god associated with mummification is who?', o: ['Horus', 'Anubis', 'Set', 'Thoth'], c: 1, e: 'Anubis presided over embalming and the dead.' },
  { d: 'hard', s: 'classic', q: 'In Norse myth, what is the prophesied end-of-the-world battle called?', o: ['Valhalla', 'Ragnarök', 'Bifrost', 'Asgard'], c: 1, e: 'Ragnarök is the Norse apocalypse.' },
  { d: 'hard', s: 'classic', q: 'In Greek myth, the primordial personification of the Earth is who?', o: ['Gaia', 'Rhea', 'Hestia', 'Nyx'], c: 0, e: 'Gaia is the primordial Earth goddess.' },
  { d: 'hard', s: 'classic', q: 'Which river did souls cross to enter the Greek Underworld?', o: ['Nile', 'Styx', 'Lethe', 'Acheron'], c: 1, e: 'The dead crossed the River Styx.' },
  { d: 'hard', s: 'classic', q: 'Who is the hero of the ancient Mesopotamian epic?', o: ['Gilgamesh', 'Enkidu', 'Marduk', 'Sargon'], c: 0, e: 'The Epic of Gilgamesh is among the oldest stories.' },
  { d: 'hard', s: 'classic', q: 'In Norse cosmology, what is the great world-tree called?', o: ['Yggdrasil', 'Mjolnir', 'Valhalla', 'Midgard'], c: 0, e: 'Yggdrasil connects the nine worlds.' },
  { d: 'hard', s: 'classic', q: 'Which Titan was condemned to hold up the sky?', o: ['Prometheus', 'Atlas', 'Cronus', 'Helios'], c: 1, e: 'Atlas bears the heavens on his shoulders.' },
  { d: 'hard', s: 'classic', q: 'The Celtic festival that influenced modern Halloween is called what?', o: ['Beltane', 'Samhain', 'Imbolc', 'Lughnasadh'], c: 1, e: 'Samhain marked the end of the harvest season.' },
  { d: 'hard', s: 'classic', q: 'In Greek myth, who flew too close to the sun on wax wings?', o: ['Daedalus', 'Icarus', 'Bellerophon', 'Theseus'], c: 1, e: 'Icarus\' wax wings melted near the sun.' },
  { d: 'hard', s: 'classic', q: 'Demeter is the Greek goddess of what?', o: ['The harvest', 'The hunt', 'The sea', 'War'], c: 0, e: 'Demeter governs agriculture and the harvest.' },
  { d: 'hard', s: 'classic', q: 'The Egyptian goddess of magic, motherhood and healing is who?', o: ['Nut', 'Isis', 'Bastet', 'Hathor'], c: 1, e: 'Isis was a powerful Egyptian goddess.' },

  // ===== SET B — INDIAN / HINDU MYTHOLOGY (35) =====
  // Easy (12)
  { d: 'easy', s: 'cultural', q: 'King Mahabali is central to which Kerala festival?', o: ['Vishu', 'Onam', 'Thiruvathira', 'Pongal'], c: 1, e: 'Onam celebrates the return of King Mahabali.' },
  { d: 'easy', s: 'cultural', q: 'Hanuman is traditionally considered the son of which deity?', o: ['Agni (Fire)', 'Vayu (Wind)', 'Indra', 'Surya'], c: 1, e: 'Hanuman is the son of Vayu, the wind god.' },
  { d: 'easy', s: 'cultural', q: 'The epic "Mahabharata" was composed by whom?', o: ['Valmiki', 'Ved Vyasa', 'Tulsidas', 'Kalidasa'], c: 1, e: 'Sage Ved Vyasa composed the Mahabharata.' },
  { d: 'easy', s: 'cultural', q: 'Lord Rama is an avatar of which god?', o: ['Shiva', 'Vishnu', 'Brahma', 'Indra'], c: 1, e: 'Rama is the seventh avatar of Vishnu.' },
  { d: 'easy', s: 'cultural', q: 'Which Hindu god has the head of an elephant?', o: ['Hanuman', 'Ganesha', 'Kartikeya', 'Narasimha'], c: 1, e: 'Ganesha is the elephant-headed god.' },
  { d: 'easy', s: 'cultural', q: 'Krishna is an avatar of which god?', o: ['Shiva', 'Vishnu', 'Brahma', 'Surya'], c: 1, e: 'Krishna is a celebrated avatar of Vishnu.' },
  { d: 'easy', s: 'cultural', q: 'In the Hindu trinity, who is the destroyer?', o: ['Brahma', 'Vishnu', 'Shiva', 'Indra'], c: 2, e: 'Shiva is the destroyer/transformer.' },
  { d: 'easy', s: 'cultural', q: 'Who is the hero of the epic "Ramayana"?', o: ['Krishna', 'Rama', 'Arjuna', 'Bhima'], c: 1, e: 'Rama is the central hero of the Ramayana.' },
  { d: 'easy', s: 'cultural', q: 'Lakshmi is the Hindu goddess of what?', o: ['Knowledge', 'Wealth and prosperity', 'War', 'Destruction'], c: 1, e: 'Lakshmi is the goddess of wealth.' },
  { d: 'easy', s: 'cultural', q: 'Who is the four-faced creator god in Hindu mythology?', o: ['Vishnu', 'Brahma', 'Shiva', 'Ganesha'], c: 1, e: 'Brahma is the creator with four faces.' },
  { d: 'easy', s: 'cultural', q: 'Krishna delivered which sacred discourse on the Kurukshetra battlefield?', o: ['Ramayana', 'Bhagavad Gita', 'Vedas', 'Upanishads'], c: 1, e: 'The Bhagavad Gita is Krishna\'s counsel to Arjuna.' },
  { d: 'easy', s: 'cultural', q: 'Saraswati is the Hindu goddess of what?', o: ['Wealth', 'Knowledge and arts', 'War', 'The harvest'], c: 1, e: 'Saraswati embodies knowledge, music and learning.' },
  // Medium (12)
  { d: 'medium', s: 'cultural', q: 'What is the vahana (mount) of Lord Ganesha?', o: ['A peacock', 'A mouse', 'An eagle', 'A bull'], c: 1, e: 'Ganesha rides a mouse (mooshika).' },
  { d: 'medium', s: 'cultural', q: 'Who served as Arjuna\'s charioteer in the Mahabharata war?', o: ['Bhishma', 'Krishna', 'Karna', 'Drona'], c: 1, e: 'Krishna guided Arjuna\'s chariot.' },
  { d: 'medium', s: 'cultural', q: 'Ravana, the antagonist of the Ramayana, was the king of where?', o: ['Ayodhya', 'Lanka', 'Mathura', 'Hastinapura'], c: 1, e: 'Ravana ruled the kingdom of Lanka.' },
  { d: 'medium', s: 'cultural', q: 'Which goddess slew the buffalo demon Mahishasura?', o: ['Lakshmi', 'Durga', 'Saraswati', 'Sita'], c: 1, e: 'Durga vanquished Mahishasura.' },
  { d: 'medium', s: 'cultural', q: 'What is the eagle mount (vahana) of Lord Vishnu?', o: ['Nandi', 'Garuda', 'Airavata', 'Uchchaihshravas'], c: 1, e: 'Garuda is Vishnu\'s eagle mount.' },
  { d: 'medium', s: 'cultural', q: 'The five Pandava brothers shared which common wife?', o: ['Kunti', 'Draupadi', 'Gandhari', 'Subhadra'], c: 1, e: 'Draupadi was wife to all five Pandavas.' },
  { d: 'medium', s: 'cultural', q: 'Who is the consort of Lord Shiva?', o: ['Lakshmi', 'Parvati', 'Saraswati', 'Radha'], c: 1, e: 'Parvati is Shiva\'s consort.' },
  { d: 'medium', s: 'cultural', q: 'How many principal avatars make up the "Dashavatara" of Vishnu?', o: ['7', '10', '12', '5'], c: 1, e: 'Dashavatara means the ten avatars.' },
  { d: 'medium', s: 'cultural', q: 'Krishna was born in which city?', o: ['Ayodhya', 'Mathura', 'Dwarka', 'Vrindavan'], c: 1, e: 'Krishna was born in Mathura.' },
  { d: 'medium', s: 'cultural', q: 'The festival of Diwali celebrates Lord Rama\'s return to which city?', o: ['Mathura', 'Ayodhya', 'Lanka', 'Kashi'], c: 1, e: 'Diwali marks Rama\'s homecoming to Ayodhya.' },
  { d: 'medium', s: 'cultural', q: 'On which serpent does Lord Vishnu recline in the cosmic ocean?', o: ['Vasuki', 'Ananta (Shesha)', 'Takshaka', 'Kaliya'], c: 1, e: 'Vishnu rests on the serpent Ananta-Shesha.' },
  { d: 'medium', s: 'cultural', q: 'What is the bull mount of Lord Shiva called?', o: ['Garuda', 'Nandi', 'Airavata', 'Kamadhenu'], c: 1, e: 'Nandi the bull is Shiva\'s mount.' },
  // Hard (11)
  { d: 'hard', s: 'cultural', q: 'Which avatar of Vishnu sent King Mahabali to the netherworld in the Onam legend?', o: ['Vamana', 'Narasimha', 'Parashurama', 'Matsya'], c: 0, e: 'The dwarf Vamana pushed Mahabali down with his foot.' },
  { d: 'hard', s: 'cultural', q: 'Karna, the tragic Mahabharata warrior, was the son of which god?', o: ['Indra', 'Surya (Sun)', 'Agni', 'Yama'], c: 1, e: 'Karna was the son of the sun god Surya.' },
  { d: 'hard', s: 'cultural', q: 'Bhishma of the Mahabharata had which extraordinary boon?', o: ['Immortality', 'To choose the time of his own death', 'Invisibility', 'Eternal youth'], c: 1, e: 'Bhishma had Ichha-Mrityu, control over his death.' },
  { d: 'hard', s: 'cultural', q: 'What is the name of Vishnu\'s spinning discus weapon?', o: ['Trishula', 'Sudarshana Chakra', 'Vajra', 'Gada'], c: 1, e: 'The Sudarshana Chakra is Vishnu\'s discus.' },
  { d: 'hard', s: 'cultural', q: 'The first avatar of Vishnu, Matsya, took the form of a what?', o: ['Tortoise', 'Fish', 'Boar', 'Lion'], c: 1, e: 'Matsya is the fish avatar that saved Manu.' },
  { d: 'hard', s: 'cultural', q: 'Abhimanyu, the young warrior slain in the Chakravyuha, was the son of whom?', o: ['Bhima', 'Arjuna', 'Yudhishthira', 'Nakula'], c: 1, e: 'Abhimanyu was Arjuna\'s son.' },
  { d: 'hard', s: 'cultural', q: 'Eklavya famously offered his thumb as guru-dakshina to which teacher?', o: ['Dronacharya', 'Kripacharya', 'Parashurama', 'Sandipani'], c: 0, e: 'Eklavya gave his thumb to Drona.' },
  { d: 'hard', s: 'cultural', q: 'Lord Ayyappa, worshipped at Sabarimala, is said to be born of Shiva and which form of Vishnu?', o: ['Mohini', 'Narasimha', 'Vamana', 'Kurma'], c: 0, e: 'Ayyappa is the son of Shiva and Vishnu\'s Mohini avatar.' },
  { d: 'hard', s: 'cultural', q: 'To find the Sanjeevani herb, Hanuman carried which entire feature?', o: ['A river', 'A mountain', 'A forest', 'A temple'], c: 1, e: 'Hanuman lifted the whole mountain (Dronagiri).' },
  { d: 'hard', s: 'cultural', q: 'King Mahabali was a benevolent king of which lineage?', o: ['Deva (gods)', 'Asura (demons)', 'Yaksha', 'Naga'], c: 1, e: 'Mahabali was a righteous Asura king, grandson of Prahlada.' },
  { d: 'hard', s: 'cultural', q: 'The "Samudra Manthan" (churning of the ocean) used which mountain as the churning rod?', o: ['Mount Meru', 'Mount Mandara', 'Mount Kailash', 'Mount Govardhana'], c: 1, e: 'Mount Mandara served as the churning rod.' },
];
