// Topic: Nature & Animals — 70 questions (Wave 1 global classic, Wave 2 India focus)
export default [
  // ===== WAVE 1 — GLOBAL CLASSIC (35) =====
  // Easy (12)
  { d: 'easy', s: 'classic', q: 'What is the largest land animal on Earth?', o: ['Hippopotamus', 'African elephant', 'White rhino', 'Giraffe'], c: 1, e: 'The African elephant is the biggest land animal.' },
  { d: 'easy', s: 'classic', q: 'Which is the fastest land animal?', o: ['Lion', 'Cheetah', 'Pronghorn', 'Horse'], c: 1, e: 'The cheetah can sprint over 100 km/h.' },
  { d: 'easy', s: 'classic', q: 'What is the largest animal that has ever lived?', o: ['Blue whale', 'Whale shark', 'Elephant', 'Brachiosaurus'], c: 0, e: 'The blue whale is the largest animal ever.' },
  { d: 'easy', s: 'classic', q: 'Which animal is traditionally called the "King of the Jungle"?', o: ['Tiger', 'Lion', 'Leopard', 'Gorilla'], c: 1, e: 'The lion bears the regal nickname.' },
  { d: 'easy', s: 'classic', q: 'A group of lions is called a what?', o: ['Pack', 'Pride', 'Herd', 'Flock'], c: 1, e: 'Lions live in groups called prides.' },
  { d: 'easy', s: 'classic', q: 'Which of these birds cannot fly?', o: ['Penguin', 'Eagle', 'Sparrow', 'Pigeon'], c: 0, e: 'Penguins swim rather than fly.' },
  { d: 'easy', s: 'classic', q: 'Which is the tallest animal in the world?', o: ['Elephant', 'Giraffe', 'Camel', 'Horse'], c: 1, e: 'The giraffe is the tallest living animal.' },
  { d: 'easy', s: 'classic', q: 'A baby dog is called a what?', o: ['Kit', 'Puppy', 'Cub', 'Calf'], c: 1, e: 'Young dogs are puppies.' },
  { d: 'easy', s: 'classic', q: 'Which insects are famous for producing honey?', o: ['Ants', 'Bees', 'Wasps', 'Beetles'], c: 1, e: 'Honeybees make honey.' },
  { d: 'easy', s: 'classic', q: 'Which is the largest of the big cats?', o: ['Lion', 'Tiger', 'Jaguar', 'Leopard'], c: 1, e: 'The tiger is the largest cat species.' },
  { d: 'easy', s: 'classic', q: 'Which animal is famous for changing its skin color?', o: ['Gecko', 'Chameleon', 'Iguana', 'Skink'], c: 1, e: 'Chameleons change color to communicate and regulate heat.' },
  { d: 'easy', s: 'classic', q: 'How many legs does a spider have?', o: ['6', '8', '10', '12'], c: 1, e: 'Spiders are arachnids with eight legs.' },
  // Medium (12)
  { d: 'medium', s: 'classic', q: 'Which bird is the fastest animal in a dive?', o: ['Golden eagle', 'Peregrine falcon', 'Swift', 'Albatross'], c: 1, e: 'The peregrine falcon dives at over 300 km/h.' },
  { d: 'medium', s: 'classic', q: 'A group of crows is poetically called a what?', o: ['Murder', 'Gaggle', 'Parliament', 'Colony'], c: 0, e: 'A group of crows is a "murder".' },
  { d: 'medium', s: 'classic', q: 'Which is the only mammal capable of true flight?', o: ['Flying squirrel', 'Bat', 'Sugar glider', 'Colugo'], c: 1, e: 'Bats are the only flying mammals.' },
  { d: 'medium', s: 'classic', q: 'What is the largest species of fish?', o: ['Great white shark', 'Whale shark', 'Manta ray', 'Marlin'], c: 1, e: 'The whale shark is the biggest fish.' },
  { d: 'medium', s: 'classic', q: 'What do giant pandas eat almost exclusively?', o: ['Fish', 'Bamboo', 'Berries', 'Insects'], c: 1, e: 'Pandas live mostly on bamboo.' },
  { d: 'medium', s: 'classic', q: 'What does a camel store in its hump?', o: ['Water', 'Fat', 'Air', 'Food pellets'], c: 1, e: 'The hump stores fat, not water.' },
  { d: 'medium', s: 'classic', q: 'The scientific study of birds is called what?', o: ['Entomology', 'Ornithology', 'Herpetology', 'Ichthyology'], c: 1, e: 'Ornithology is the study of birds.' },
  { d: 'medium', s: 'classic', q: 'Which big cat cannot roar?', o: ['Lion', 'Cheetah', 'Tiger', 'Jaguar'], c: 1, e: 'Cheetahs purr and chirp but cannot roar.' },
  { d: 'medium', s: 'classic', q: 'What is the largest living reptile?', o: ['Komodo dragon', 'Saltwater crocodile', 'Green anaconda', 'Galápagos tortoise'], c: 1, e: 'The saltwater crocodile is the biggest reptile.' },
  { d: 'medium', s: 'classic', q: 'A group of wolves is known as a what?', o: ['Herd', 'Pack', 'Pride', 'Troop'], c: 1, e: 'Wolves travel in packs.' },
  { d: 'medium', s: 'classic', q: 'Which is the fastest fish in the ocean?', o: ['Tuna', 'Sailfish', 'Marlin', 'Swordfish'], c: 1, e: 'The sailfish is the fastest swimmer.' },
  { d: 'medium', s: 'classic', q: 'Which scientific term describes animals active at night?', o: ['Diurnal', 'Nocturnal', 'Crepuscular', 'Hibernal'], c: 1, e: 'Nocturnal animals are active at night.' },
  // Hard (11)
  { d: 'hard', s: 'classic', q: 'What is the smallest bird in the world?', o: ['Hummingbird (bee)', 'Wren', 'Goldcrest', 'Sunbird'], c: 0, e: 'The bee hummingbird is the smallest bird.' },
  { d: 'hard', s: 'classic', q: 'Which reptile is recorded with one of the most powerful bite forces?', o: ['Komodo dragon', 'Saltwater crocodile', 'Snapping turtle', 'Monitor lizard'], c: 1, e: 'Saltwater crocodiles have an enormous bite force.' },
  { d: 'hard', s: 'classic', q: 'In biological classification, which rank comes just below "genus"?', o: ['Family', 'Species', 'Order', 'Phylum'], c: 1, e: 'Species is the rank below genus.' },
  { d: 'hard', s: 'classic', q: 'What is the largest invertebrate on Earth?', o: ['Giant clam', 'Giant squid', 'Lobster', 'Octopus'], c: 1, e: 'The giant (or colossal) squid is the largest invertebrate.' },
  { d: 'hard', s: 'classic', q: 'The transformation of a caterpillar into a butterfly is called what?', o: ['Mutation', 'Metamorphosis', 'Mitosis', 'Regeneration'], c: 1, e: 'Insects develop through metamorphosis.' },
  { d: 'hard', s: 'classic', q: 'Which continent has no native species of snakes?', o: ['Australia', 'Antarctica', 'Europe', 'Africa'], c: 1, e: 'Antarctica is too cold for snakes.' },
  { d: 'hard', s: 'classic', q: 'A "joey" is the baby of which animal?', o: ['Kangaroo', 'Koala', 'Otter', 'Both kangaroo and koala'], c: 3, e: 'Both kangaroo and koala young are called joeys.' },
  { d: 'hard', s: 'classic', q: 'What is the largest flightless bird?', o: ['Emu', 'Ostrich', 'Cassowary', 'Rhea'], c: 1, e: 'The ostrich is the largest flightless bird.' },
  { d: 'hard', s: 'classic', q: 'Which animal has the longest lifespan among the following?', o: ['Giant tortoise', 'Elephant', 'Parrot', 'Horse'], c: 0, e: 'Giant tortoises can live well over 150 years.' },
  { d: 'hard', s: 'classic', q: 'The "axolotl" is famous for its ability to do what?', o: ['Fly', 'Regenerate body parts', 'Change sex', 'Glow in the dark'], c: 1, e: 'Axolotls can regrow limbs and organs.' },
  { d: 'hard', s: 'classic', q: 'Which mammal lays eggs?', o: ['Platypus', 'Bat', 'Dolphin', 'Sloth'], c: 0, e: 'The platypus is an egg-laying monotreme.' },

  // ===== WAVE 2 — INDIA FOCUS (35) =====
  // Easy (12)
  { d: 'easy', s: 'classic', q: 'What is India\'s national animal?', o: ['Lion', 'Bengal tiger', 'Elephant', 'Leopard'], c: 1, e: 'The Bengal tiger is India\'s national animal.' },
  { d: 'easy', s: 'classic', q: 'What is India\'s national bird?', o: ['Peacock', 'Sparrow', 'Eagle', 'Crane'], c: 0, e: 'The Indian peafowl (peacock) is the national bird.' },
  { d: 'easy', s: 'classic', q: 'The Asiatic lion survives in the wild only in which Indian forest?', o: ['Sundarbans', 'Gir Forest', 'Bandipur', 'Corbett'], c: 1, e: 'Gir Forest in Gujarat is the last refuge of the Asiatic lion.' },
  { d: 'easy', s: 'classic', q: 'The famous one-horned rhinoceros is found mainly in which state?', o: ['Kerala', 'Assam', 'Rajasthan', 'Punjab'], c: 1, e: 'Kaziranga in Assam protects the one-horned rhino.' },
  { d: 'easy', s: 'classic', q: 'What is India\'s national aquatic animal?', o: ['Sea turtle', 'Ganges river dolphin', 'Gharial', 'Mahseer fish'], c: 1, e: 'The Ganges river dolphin is the national aquatic animal.' },
  { d: 'easy', s: 'classic', q: 'Periyar Tiger Reserve is located in which state?', o: ['Tamil Nadu', 'Kerala', 'Karnataka', 'Goa'], c: 1, e: 'Periyar is a famous reserve in Kerala.' },
  { d: 'easy', s: 'classic', q: 'What is India\'s national flower?', o: ['Rose', 'Lotus', 'Marigold', 'Jasmine'], c: 1, e: 'The lotus is India\'s national flower.' },
  { d: 'easy', s: 'classic', q: 'Silent Valley National Park is located in which state?', o: ['Kerala', 'Karnataka', 'Tamil Nadu', 'Maharashtra'], c: 0, e: 'Silent Valley lies in Palakkad, Kerala.' },
  { d: 'easy', s: 'classic', q: 'What is India\'s national tree?', o: ['Neem', 'Banyan', 'Peepal', 'Mango'], c: 1, e: 'The banyan is India\'s national tree.' },
  { d: 'easy', s: 'classic', q: 'Kaziranga National Park is most famous for which animal?', o: ['Tiger', 'One-horned rhinoceros', 'Snow leopard', 'Elephant'], c: 1, e: 'Kaziranga is renowned for its rhinos.' },
  { d: 'easy', s: 'classic', q: 'India\'s flagship conservation effort for big cats is called what?', o: ['Project Elephant', 'Project Tiger', 'Project Lion', 'Project Cheetah'], c: 1, e: 'Project Tiger was launched to save tigers.' },
  { d: 'easy', s: 'classic', q: 'The Royal Bengal Tiger famously inhabits which mangrove region?', o: ['Sundarbans', 'Western Ghats', 'Thar Desert', 'Nilgiris'], c: 0, e: 'The Sundarbans host the swimming Bengal tigers.' },
  // Medium (12)
  { d: 'medium', s: 'classic', q: 'In which year was Project Tiger launched in India?', o: ['1965', '1973', '1985', '1991'], c: 1, e: 'Project Tiger began in 1973.' },
  { d: 'medium', s: 'classic', q: 'The Western Ghats are recognized globally as a what?', o: ['Desert belt', 'Biodiversity hotspot', 'Tundra zone', 'Volcanic chain'], c: 1, e: 'The Western Ghats are a UNESCO biodiversity hotspot.' },
  { d: 'medium', s: 'classic', q: 'The endangered Nilgiri Tahr is found in which mountain range?', o: ['Himalayas', 'Western Ghats', 'Aravallis', 'Vindhyas'], c: 1, e: 'The Nilgiri Tahr roams the Western Ghats.' },
  { d: 'medium', s: 'classic', q: 'Salim Ali, the "Birdman of India", was a famous what?', o: ['Botanist', 'Ornithologist', 'Geologist', 'Zoologist of reptiles'], c: 1, e: 'Salim Ali was India\'s pioneering ornithologist.' },
  { d: 'medium', s: 'classic', q: 'Which Indian state is nicknamed the "Tiger State" for its many tigers?', o: ['Kerala', 'Madhya Pradesh', 'Gujarat', 'Assam'], c: 1, e: 'Madhya Pradesh has the most tigers in India.' },
  { d: 'medium', s: 'classic', q: 'The snow leopard is found in which Indian region?', o: ['The Himalayas', 'The Deccan', 'The Sundarbans', 'The Thar Desert'], c: 0, e: 'Snow leopards inhabit the high Himalayas.' },
  { d: 'medium', s: 'classic', q: 'The Thattekad Bird Sanctuary in Kerala is named in honor of whom?', o: ['Salim Ali', 'Jim Corbett', 'M.S. Swaminathan', 'Verghese Kurien'], c: 0, e: 'It honors ornithologist Salim Ali.' },
  { d: 'medium', s: 'classic', q: 'Roughly how many states does the Western Ghats range pass through?', o: ['3', '6', '9', '11'], c: 1, e: 'The Western Ghats span about six states.' },
  { d: 'medium', s: 'classic', q: 'Which critically endangered grassland bird is found in parts of India?', o: ['Great Indian Bustard', 'Indian Roller', 'Sarus Crane', 'Hoopoe'], c: 0, e: 'The Great Indian Bustard is critically endangered.' },
  { d: 'medium', s: 'classic', q: 'Project Cheetah, launched in 2022, reintroduced cheetahs to which park?', o: ['Gir', 'Kuno National Park', 'Ranthambore', 'Bandhavgarh'], c: 1, e: 'Cheetahs from Africa were released in Kuno, Madhya Pradesh.' },
  { d: 'medium', s: 'classic', q: 'Which is the state animal of Kerala?', o: ['Tiger', 'Indian elephant', 'Nilgiri Tahr', 'Sloth bear'], c: 1, e: 'The Indian elephant is Kerala\'s state animal.' },
  { d: 'medium', s: 'classic', q: 'The Olive Ridley sea turtles famously nest in mass along the coast of which state?', o: ['Kerala', 'Odisha', 'Goa', 'Gujarat'], c: 1, e: 'Odisha\'s beaches host massive Olive Ridley nesting (arribada).' },
  // Hard (11)
  { d: 'hard', s: 'classic', q: 'The Nilgiri Tahr\'s key stronghold is which Kerala national park?', o: ['Eravikulam', 'Periyar', 'Silent Valley', 'Wayanad'], c: 0, e: 'Eravikulam National Park protects the Nilgiri Tahr.' },
  { d: 'hard', s: 'classic', q: 'The Lion-tailed macaque is endemic to which region?', o: ['Eastern Ghats', 'Western Ghats', 'Himalayan foothills', 'Andaman Islands'], c: 1, e: 'This rare primate lives only in the Western Ghats.' },
  { d: 'hard', s: 'classic', q: 'Which large hornbill is the state bird of Kerala?', o: ['Malabar Pied Hornbill', 'Great Hornbill', 'Indian Grey Hornbill', 'Rhinoceros Hornbill'], c: 1, e: 'The Great Hornbill is Kerala\'s state bird.' },
  { d: 'hard', s: 'classic', q: 'The Malabar Giant Squirrel is primarily found where?', o: ['Thar Desert', 'Western Ghats forests', 'Sundarbans', 'Ladakh'], c: 1, e: 'The colorful giant squirrel lives in Western Ghats forests.' },
  { d: 'hard', s: 'classic', q: 'The King Cobra holds which world record?', o: ['Most venomous snake', 'Longest venomous snake', 'Fastest snake', 'Largest snake'], c: 1, e: 'The King Cobra is the world\'s longest venomous snake.' },
  { d: 'hard', s: 'classic', q: 'Parambikulam Tiger Reserve lies in which state\'s Western Ghats?', o: ['Tamil Nadu', 'Kerala', 'Karnataka', 'Goa'], c: 1, e: 'Parambikulam is a tiger reserve in Kerala.' },
  { d: 'hard', s: 'classic', q: 'The Western Ghats hold which UNESCO designation?', o: ['Biosphere only', 'World Heritage Site', 'Ramsar wetland', 'Geopark'], c: 1, e: 'The Western Ghats are a UNESCO World Heritage Site.' },
  { d: 'hard', s: 'classic', q: 'The critically endangered "Gharial" is what kind of animal?', o: ['A deer', 'A fish-eating crocodilian', 'A river dolphin', 'A turtle'], c: 1, e: 'The gharial is a slender-snouted, fish-eating crocodilian.' },
  { d: 'hard', s: 'classic', q: 'Salim Ali authored which classic field guide?', o: ['The Book of Indian Birds', 'My Family and Other Animals', 'Silent Spring', 'The Jungle Book'], c: 0, e: 'His "Book of Indian Birds" is a classic.' },
  { d: 'hard', s: 'classic', q: 'The endemic amphibian "Purple frog" was rediscovered in which mountains?', o: ['Himalayas', 'Western Ghats', 'Eastern Ghats', 'Satpura'], c: 1, e: 'The purple frog is a living-fossil endemic to the Western Ghats.' },
  { d: 'hard', s: 'classic', q: 'Which Kerala reserve was India\'s first declared as a tiger reserve area through Project Tiger and is famed for boat safaris?', o: ['Periyar', 'Silent Valley', 'Eravikulam', 'Aralam'], c: 0, e: 'Periyar, with its lake, is famed for boat-based wildlife viewing.' },
];
