// Topic: OTT & Web Series — 70 questions (35 classic + 35 Indian/cultural)
export default [
  // ===== SET A — CLASSIC / GLOBAL (35) =====
  // Easy (12)
  { d: 'easy', s: 'classic', q: '"Stranger Things" is set in which fictional town?', o: ['Derry', 'Hawkins', 'Riverdale', 'Twin Peaks'], c: 1, e: 'The show is set in Hawkins, Indiana.' },
  { d: 'easy', s: 'classic', q: '"Money Heist" (La Casa de Papel) originally comes from which country?', o: ['Italy', 'Spain', 'France', 'Mexico'], c: 1, e: 'Money Heist is a Spanish series.' },
  { d: 'easy', s: 'classic', q: 'The global hit "Squid Game" is from which country?', o: ['Japan', 'South Korea', 'China', 'Thailand'], c: 1, e: 'Squid Game is a South Korean series.' },
  { d: 'easy', s: 'classic', q: 'Who is the chemistry-teacher protagonist of "Breaking Bad"?', o: ['Jesse Pinkman', 'Walter White', 'Saul Goodman', 'Hank Schrader'], c: 1, e: 'Walter White turns to making meth.' },
  { d: 'easy', s: 'classic', q: '"Game of Thrones" is based on novels by which author?', o: ['J.R.R. Tolkien', 'George R.R. Martin', 'Brandon Sanderson', 'Patrick Rothfuss'], c: 1, e: 'George R.R. Martin wrote "A Song of Ice and Fire".' },
  { d: 'easy', s: 'classic', q: 'The series "Wednesday" is a spinoff of which classic property?', o: ['The Munsters', 'The Addams Family', 'Beetlejuice', 'The Witches'], c: 1, e: 'Wednesday Addams headlines the spinoff.' },
  { d: 'easy', s: 'classic', q: 'Which platform streams the royal drama "The Crown"?', o: ['Hulu', 'Netflix', 'Disney+', 'Apple TV+'], c: 1, e: 'The Crown is a Netflix original.' },
  { d: 'easy', s: 'classic', q: 'In "The Mandalorian", what is the popular character "Baby Yoda" actually named?', o: ['Grogu', 'Yaddle', 'Kuiil', 'Cara'], c: 0, e: 'Baby Yoda\'s name is Grogu.' },
  { d: 'easy', s: 'classic', q: 'The US version of "The Office" is set at which fictional paper company?', o: ['Sterling Cooper', 'Dunder Mifflin', 'Pied Piper', 'Wernham Hogg'], c: 1, e: 'Dunder Mifflin Scranton is the setting.' },
  { d: 'easy', s: 'classic', q: 'In "Squid Game", contestants compete for what prize?', o: ['Freedom', 'A huge cash prize', 'A new identity', 'A house'], c: 1, e: 'Players risk their lives for prize money.' },
  { d: 'easy', s: 'classic', q: 'Which series features the Iron Throne and warring noble houses?', o: ['The Witcher', 'Game of Thrones', 'Vikings', 'The Last Kingdom'], c: 1, e: 'Game of Thrones centers on the Iron Throne.' },
  { d: 'easy', s: 'classic', q: 'Which streaming service produced "The Boys"?', o: ['Netflix', 'Amazon Prime Video', 'Disney+', 'Hulu'], c: 1, e: 'The Boys is an Amazon Prime Video original.' },
  // Medium (12)
  { d: 'medium', s: 'classic', q: '"Squid Game" Season 2 was released in which year?', o: ['2022', '2023', '2024', '2025'], c: 2, e: 'Season 2 premiered in December 2024.' },
  { d: 'medium', s: 'classic', q: 'Who plays Eleven in "Stranger Things"?', o: ['Sadie Sink', 'Millie Bobby Brown', 'Natalia Dyer', 'Maya Hawke'], c: 1, e: 'Millie Bobby Brown plays Eleven.' },
  { d: 'medium', s: 'classic', q: 'Which prequel/spinoff follows the lawyer from "Breaking Bad"?', o: ['Better Call Saul', 'El Camino', 'Ozark', 'Fargo'], c: 0, e: 'Better Call Saul follows Saul Goodman.' },
  { d: 'medium', s: 'classic', q: 'Which HBO series is a prequel to "Game of Thrones"?', o: ['House of the Dragon', 'The Last Kingdom', 'Rings of Power', 'Westworld'], c: 0, e: 'House of the Dragon is set 200 years earlier.' },
  { d: 'medium', s: 'classic', q: 'Who plays the title role in Netflix\'s "Wednesday"?', o: ['Millie Bobby Brown', 'Jenna Ortega', 'Sadie Sink', 'Kiernan Shipka'], c: 1, e: 'Jenna Ortega stars as Wednesday Addams.' },
  { d: 'medium', s: 'classic', q: 'In "Money Heist", the gang\'s first major target is which institution?', o: ['Bank of Spain', 'Royal Mint of Spain', 'A casino', 'A jewelry vault'], c: 1, e: 'The first heist hits the Royal Mint.' },
  { d: 'medium', s: 'classic', q: 'Who played Geralt of Rivia in the early seasons of "The Witcher"?', o: ['Henry Cavill', 'Liam Hemsworth', 'Charlie Hunnam', 'Sam Heughan'], c: 0, e: 'Henry Cavill originated the role.' },
  { d: 'medium', s: 'classic', q: 'HBO\'s "The Last of Us" is based on what source material?', o: ['A novel', 'A video game', 'A comic', 'A board game'], c: 1, e: 'It adapts the acclaimed PlayStation game.' },
  { d: 'medium', s: 'classic', q: 'Who created "Squid Game"?', o: ['Bong Joon-ho', 'Hwang Dong-hyuk', 'Park Chan-wook', 'Lee Jung-jae'], c: 1, e: 'Hwang Dong-hyuk wrote and directed Squid Game.' },
  { d: 'medium', s: 'classic', q: 'Who created "Stranger Things"?', o: ['The Duffer Brothers', 'The Russo Brothers', 'The Wachowskis', 'The Coen Brothers'], c: 0, e: 'Matt and Ross Duffer created the show.' },
  { d: 'medium', s: 'classic', q: 'The acclaimed miniseries "Chernobyl" aired on which network?', o: ['Netflix', 'HBO', 'AMC', 'Showtime'], c: 1, e: 'Chernobyl (2019) was an HBO miniseries.' },
  { d: 'medium', s: 'classic', q: 'The anthology series "Black Mirror" was created by whom?', o: ['Charlie Brooker', 'Vince Gilligan', 'Ryan Murphy', 'Shonda Rhimes'], c: 0, e: 'Charlie Brooker created Black Mirror.' },
  // Hard (11)
  { d: 'hard', s: 'classic', q: '"Breaking Bad" is primarily set in which US city?', o: ['Phoenix', 'Albuquerque', 'Denver', 'El Paso'], c: 1, e: 'The series is set in Albuquerque, New Mexico.' },
  { d: 'hard', s: 'classic', q: 'In which year did the final season of "Game of Thrones" air?', o: ['2017', '2018', '2019', '2020'], c: 2, e: 'The eighth and final season aired in 2019.' },
  { d: 'hard', s: 'classic', q: 'In "Money Heist", the robbers adopt code names based on what?', o: ['Animals', 'Cities', 'Colors', 'Planets'], c: 1, e: 'Characters go by city names like Tokyo and Berlin.' },
  { d: 'hard', s: 'classic', q: 'The US "Office" is adapted from a sitcom from which country?', o: ['Canada', 'Australia', 'United Kingdom', 'Ireland'], c: 2, e: 'It is based on the original British series.' },
  { d: 'hard', s: 'classic', q: 'The iconic deadly first game in "Squid Game" is which childhood game?', o: ['Tug of War', 'Red Light, Green Light', 'Marbles', 'Hopscotch'], c: 1, e: 'A giant doll oversees Red Light, Green Light.' },
  { d: 'hard', s: 'classic', q: 'In "Breaking Bad", Walter White\'s product is famously known by which color?', o: ['Green', 'Blue', 'Red', 'Gold'], c: 1, e: 'His signature blue methamphetamine.' },
  { d: 'hard', s: 'classic', q: 'Which Netflix series became its most-watched show upon release in 2021?', o: ['Bridgerton', 'Squid Game', 'Lupin', 'The Witcher'], c: 1, e: 'Squid Game set Netflix viewership records.' },
  { d: 'hard', s: 'classic', q: '"The Crown" chronicles the reign of which monarch?', o: ['Queen Victoria', 'Queen Elizabeth II', 'King George VI', 'King Charles III'], c: 1, e: 'It dramatizes Queen Elizabeth II\'s reign.' },
  { d: 'hard', s: 'classic', q: 'The 2022 hit "Dahmer" series streamed on which platform?', o: ['Hulu', 'Netflix', 'Peacock', 'HBO Max'], c: 1, e: 'Ryan Murphy\'s Dahmer was a Netflix release.' },
  { d: 'hard', s: 'classic', q: 'Which actor plays Joel in HBO\'s "The Last of Us"?', o: ['Pedro Pascal', 'Oscar Isaac', 'Javier Bardem', 'Diego Luna'], c: 0, e: 'Pedro Pascal stars as Joel.' },
  { d: 'hard', s: 'classic', q: 'The series "Better Call Saul" is set primarily before the events of which show?', o: ['Ozark', 'Breaking Bad', 'Fargo', 'The Wire'], c: 1, e: 'It is a prequel to Breaking Bad.' },

  // ===== SET B — INDIAN / CULTURAL (35) =====
  // Easy (12)
  { d: 'easy', s: 'cultural', q: 'Which actor plays the menacing "Kaleen Bhaiya" in "Mirzapur"?', o: ['Nawazuddin Siddiqui', 'Pankaj Tripathi', 'Manoj Bajpayee', 'Jaideep Ahlawat'], c: 1, e: 'Pankaj Tripathi plays Akhandanand Tripathi.' },
  { d: 'easy', s: 'cultural', q: '"Scam 1992" is based on the life of which figure?', o: ['Vijay Mallya', 'Harshad Mehta', 'Nirav Modi', 'Ketan Parekh'], c: 1, e: 'It chronicles stockbroker Harshad Mehta.' },
  { d: 'easy', s: 'cultural', q: 'Who plays Srikant Tiwari in "The Family Man"?', o: ['Manoj Bajpayee', 'Pankaj Tripathi', 'Kay Kay Menon', 'Sharib Hashmi'], c: 0, e: 'Manoj Bajpayee leads The Family Man.' },
  { d: 'easy', s: 'cultural', q: 'The comedy "Panchayat" is set in what kind of place?', o: ['A big city', 'A rural village', 'A college', 'A startup'], c: 1, e: 'It follows life in a remote UP village.' },
  { d: 'easy', s: 'cultural', q: 'Which platform streams "Mirzapur"?', o: ['Netflix', 'Amazon Prime Video', 'Disney+ Hotstar', 'SonyLIV'], c: 1, e: 'Mirzapur is an Amazon Prime Video original.' },
  { d: 'easy', s: 'cultural', q: '"Sacred Games" holds the distinction of being India\'s first what?', o: ['Netflix original series', 'OTT film', 'Reality show', 'Talk show'], c: 0, e: 'Sacred Games was Netflix India\'s first original.' },
  { d: 'easy', s: 'cultural', q: 'Who played the antagonist Raji in "The Family Man" Season 2?', o: ['Priyamani', 'Samantha Ruth Prabhu', 'Shreya Dhanwanthary', 'Sobhita Dhulipala'], c: 1, e: 'Samantha Ruth Prabhu played Raji.' },
  { d: 'easy', s: 'cultural', q: '"Delhi Crime" is based on the investigation of which real case?', o: ['The 2012 Delhi assault case', 'The Aarushi case', 'The Sheena Bora case', 'The Nithari case'], c: 0, e: 'Season 1 dramatizes the 2012 Nirbhaya case.' },
  { d: 'easy', s: 'cultural', q: 'Who plays the lead "Abhishek Tripathi" in "Panchayat"?', o: ['Jitendra Kumar', 'Vikrant Massey', 'Ayushmann Khurrana', 'Rajkummar Rao'], c: 0, e: 'Jitendra Kumar plays the reluctant secretary.' },
  { d: 'easy', s: 'cultural', q: 'The TVF series "Kota Factory" focuses on students preparing for what?', o: ['Civil services', 'Engineering/medical entrance exams', 'Bank jobs', 'Acting'], c: 1, e: 'It depicts coaching-hub aspirants in Kota.' },
  { d: 'easy', s: 'cultural', q: 'Which platform produced "Sacred Games"?', o: ['Amazon Prime', 'Netflix', 'Hotstar', 'Zee5'], c: 1, e: 'Sacred Games is a Netflix series.' },
  { d: 'easy', s: 'cultural', q: 'In "Mirzapur", which two brothers are central characters early on?', o: ['Guddu and Bablu', 'Munna and Sharad', 'Kaleen and Dadda', 'Ramakant and JP'], c: 0, e: 'Guddu and Bablu Pandit drive Season 1.' },
  // Medium (12)
  { d: 'medium', s: 'cultural', q: 'Who directed the acclaimed series "Scam 1992"?', o: ['Anurag Kashyap', 'Hansal Mehta', 'Vikramaditya Motwane', 'Raj & DK'], c: 1, e: 'Hansal Mehta directed Scam 1992.' },
  { d: 'medium', s: 'cultural', q: '"The Family Man" was created by which director duo?', o: ['Raj & DK', 'Abbas-Mustan', 'Anurag & Vikram', 'Farhan & Ritesh'], c: 0, e: 'Raj Nidimoru and Krishna D.K. created it.' },
  { d: 'medium', s: 'cultural', q: '"Sacred Games" is based on a novel by whom?', o: ['Amish Tripathi', 'Vikram Chandra', 'Aravind Adiga', 'Jhumpa Lahiri'], c: 1, e: 'Vikram Chandra wrote the source novel.' },
  { d: 'medium', s: 'cultural', q: '"Delhi Crime" won which major international award?', o: ['Golden Globe', 'International Emmy for Best Drama Series', 'BAFTA', 'Peabody only'], c: 1, e: 'It won the 2020 International Emmy for Best Drama.' },
  { d: 'medium', s: 'cultural', q: '"Mirzapur" is set primarily in which Indian state?', o: ['Bihar', 'Uttar Pradesh', 'Madhya Pradesh', 'Jharkhand'], c: 1, e: 'The crime saga unfolds in Uttar Pradesh.' },
  { d: 'medium', s: 'cultural', q: 'The fictional agency Srikant works for in "The Family Man" is called what?', o: ['RAW', 'TASC', 'NIA', 'CBI'], c: 1, e: 'He works for the fictional T.A.S.C.' },
  { d: 'medium', s: 'cultural', q: 'The Malayalam OTT hit "The Great Indian Kitchen" critiques what theme?', o: ['Corruption', 'Patriarchy and domestic labor', 'Caste politics', 'Migration'], c: 1, e: 'It exposes everyday patriarchy in a household.' },
  { d: 'medium', s: 'cultural', q: 'The web series "Made in Heaven" revolves around which profession?', o: ['Lawyers', 'Wedding planners', 'Doctors', 'Chefs'], c: 1, e: 'It follows Delhi wedding planners.' },
  { d: 'medium', s: 'cultural', q: 'Which thriller series is produced by Anushka Sharma\'s Clean Slate Filmz?', o: ['Paatal Lok', 'Aarya', 'Special Ops', 'Asur'], c: 0, e: 'Paatal Lok was produced by Clean Slate Filmz.' },
  { d: 'medium', s: 'cultural', q: 'The TVF series "Aspirants" follows young people preparing for which exam?', o: ['JEE', 'UPSC Civil Services', 'CAT', 'NEET'], c: 1, e: 'Aspirants depicts UPSC aspirants in Delhi.' },
  { d: 'medium', s: 'cultural', q: 'The Tripathi family\'s public business front in "Mirzapur" is what?', o: ['A carpet (rug) business', 'A hotel', 'A film studio', 'A bank'], c: 0, e: 'They run a carpet business alongside guns.' },
  { d: 'medium', s: 'cultural', q: 'Which 2023 Prime series depicts the golden age of the Hindi film industry?', o: ['Jubilee', 'Rocket Boys', 'Tandav', 'Bandish Bandits'], c: 0, e: 'Jubilee is set in the 1940s-50s film world.' },
  // Hard (11)
  { d: 'hard', s: 'cultural', q: 'Which actor played Harshad Mehta in "Scam 1992"?', o: ['Pratik Gandhi', 'Rajkummar Rao', 'Vijay Varma', 'Jaideep Ahlawat'], c: 0, e: 'Pratik Gandhi\'s breakout role was Harshad Mehta.' },
  { d: 'hard', s: 'cultural', q: 'Who are the two lead actors of "Sacred Games"?', o: ['Saif Ali Khan & Nawazuddin Siddiqui', 'Manoj Bajpayee & Kay Kay Menon', 'Abhishek Bachchan & Vicky Kaushal', 'Pankaj Tripathi & Ali Fazal'], c: 0, e: 'Saif and Nawazuddin headline Sacred Games.' },
  { d: 'hard', s: 'cultural', q: 'Who plays the lead investigator Vartika Chaturvedi in "Delhi Crime"?', o: ['Tabu', 'Shefali Shah', 'Konkona Sen Sharma', 'Richa Chadha'], c: 1, e: 'Shefali Shah leads Delhi Crime.' },
  { d: 'hard', s: 'cultural', q: '"The Great Indian Kitchen" was originally made in which language?', o: ['Tamil', 'Malayalam', 'Kannada', 'Telugu'], c: 1, e: 'It is a Malayalam film (later remade).' },
  { d: 'hard', s: 'cultural', q: 'The village in "Panchayat" is named what?', o: ['Phulera', 'Mirzapur', 'Wasseypur', 'Barfi'], c: 0, e: 'The series is set in Phulera village.' },
  { d: 'hard', s: 'cultural', q: '"The Family Man" Season 2 storyline prominently features which conflict?', o: ['Kashmir insurgency', 'A Tamil separatist group', 'Naxal movement', 'Punjab militancy'], c: 1, e: 'Season 2 centers on a Tamil rebel plot.' },
  { d: 'hard', s: 'cultural', q: 'Which web series is set in the fictional coal-mafia world reminiscent of Dhanbad?', o: ['Mirzapur', 'Jamtara', 'Rangbaaz', 'Maharani'], c: 2, e: 'Rangbaaz dramatizes gangster sagas; (Gangs of Wasseypur did Dhanbad on film).' },
  { d: 'hard', s: 'cultural', q: 'The series "Jamtara" is about which kind of crime?', o: ['Drug trade', 'Phishing/online scams', 'Smuggling', 'Extortion'], c: 1, e: 'Jamtara depicts a phishing-scam hub.' },
  { d: 'hard', s: 'cultural', q: 'Which biographical series dramatizes the lives of Homi Bhabha and Vikram Sarabhai?', o: ['Rocket Boys', 'Rocket Singh', 'Mission Mangal', 'Shaktimaan'], c: 0, e: 'Rocket Boys depicts India\'s science pioneers.' },
  { d: 'hard', s: 'cultural', q: 'Pankaj Tripathi\'s line "Aadarniya..." and his calm menace made which character iconic?', o: ['Guddu Pandit', 'Kaleen Bhaiya', 'Sartaj Singh', 'JP Yadav'], c: 1, e: 'His Kaleen Bhaiya is a fan favorite.' },
  { d: 'hard', s: 'cultural', q: 'The acclaimed series "Paatal Lok" derives its title from which concept?', o: ['A real city', 'The mythological netherworld', 'A prison name', 'A police code'], c: 1, e: 'Paatal Lok refers to the mythic underworld.' },
];
