// Topic: Pop Culture — 70 questions (35 classic + 35 Indian/Malayali cultural)
export default [
  // ===== SET A — CLASSIC / GLOBAL (35) =====
  // Easy (12)
  { d: 'easy', s: 'classic', q: 'Which film won Best Picture at the 2024 Oscars?', o: ['Barbie', 'Oppenheimer', 'Poor Things', 'Past Lives'], c: 1, e: 'Oppenheimer won Best Picture in 2024.' },
  { d: 'easy', s: 'classic', q: 'The infamous slap at the 2022 Oscars involved Will Smith and whom?', o: ['Chris Rock', 'Kevin Hart', 'Dave Chappelle', 'Jimmy Kimmel'], c: 0, e: 'Will Smith slapped Chris Rock onstage.' },
  { d: 'easy', s: 'classic', q: 'The blockbuster "Barbie" (2023) was directed by whom?', o: ['Sofia Coppola', 'Greta Gerwig', 'Patty Jenkins', 'Chloé Zhao'], c: 1, e: 'Greta Gerwig directed Barbie.' },
  { d: 'easy', s: 'classic', q: 'Taylor Swift\'s record-breaking 2023–24 concert tour was called what?', o: ['Reputation Tour', 'The Eras Tour', '1989 World Tour', 'Lover Fest'], c: 1, e: 'The Eras Tour smashed revenue records.' },
  { d: 'easy', s: 'classic', q: 'Which short-video app exploded in global popularity around 2020?', o: ['Vine', 'TikTok', 'Triller', 'Dubsmash'], c: 1, e: 'TikTok became a cultural phenomenon.' },
  { d: 'easy', s: 'classic', q: 'Who is the author of the "Harry Potter" books?', o: ['Suzanne Collins', 'J.K. Rowling', 'Stephenie Meyer', 'Rick Riordan'], c: 1, e: 'J.K. Rowling wrote the Harry Potter series.' },
  { d: 'easy', s: 'classic', q: 'Who originated the role of Iron Man in the Marvel Cinematic Universe?', o: ['Chris Evans', 'Robert Downey Jr.', 'Chris Hemsworth', 'Mark Ruffalo'], c: 1, e: 'Robert Downey Jr. launched the MCU as Iron Man.' },
  { d: 'easy', s: 'classic', q: 'Which superstar is nicknamed "Queen Bey"?', o: ['Rihanna', 'Beyoncé', 'Adele', 'Lady Gaga'], c: 1, e: 'Beyoncé is widely called Queen Bey.' },
  { d: 'easy', s: 'classic', q: 'The line "I am Groot" comes from which franchise?', o: ['Star Wars', 'Guardians of the Galaxy', 'Avatar', 'Transformers'], c: 1, e: 'Groot from Guardians of the Galaxy says little else.' },
  { d: 'easy', s: 'classic', q: 'The globally famous group BTS comes from which country?', o: ['Japan', 'South Korea', 'China', 'Thailand'], c: 1, e: 'BTS is a South Korean K-pop group.' },
  { d: 'easy', s: 'classic', q: 'The rallying cry "Wakanda Forever" is from which film?', o: ['Black Panther', 'Aquaman', 'Thor', 'Shazam'], c: 0, e: 'It is the salute from Black Panther.' },
  { d: 'easy', s: 'classic', q: 'The Kardashian-Jenner family rose to fame primarily through what?', o: ['Music', 'Reality TV', 'Sports', 'Politics'], c: 1, e: 'Their reality show launched their fame.' },
  // Medium (12)
  { d: 'medium', s: 'classic', q: 'Which actor won a posthumous Oscar for playing the Joker?', o: ['Jack Nicholson', 'Heath Ledger', 'Joaquin Phoenix', 'Jared Leto'], c: 1, e: 'Heath Ledger won posthumously for The Dark Knight.' },
  { d: 'medium', s: 'classic', q: 'The 2023 "Barbenheimer" trend paired Barbie with which other film?', o: ['Oppenheimer', 'Mission: Impossible', 'Indiana Jones', 'Elemental'], c: 0, e: 'Barbie and Oppenheimer released the same day.' },
  { d: 'medium', s: 'classic', q: 'Which film launched the Marvel Cinematic Universe in 2008?', o: ['Thor', 'Iron Man', 'The Avengers', 'Hulk'], c: 1, e: 'Iron Man (2008) started the MCU.' },
  { d: 'medium', s: 'classic', q: 'Which streaming service produced "Stranger Things"?', o: ['Hulu', 'Netflix', 'Disney+', 'HBO'], c: 1, e: 'Stranger Things is a Netflix original.' },
  { d: 'medium', s: 'classic', q: 'Rihanna headlined the halftime show at which 2023 event?', o: ['Grammys', 'Super Bowl LVII', 'Coachella', 'VMAs'], c: 1, e: 'Rihanna performed at Super Bowl LVII in 2023.' },
  { d: 'medium', s: 'classic', q: 'Which celebrity founded the cosmetics line Fenty Beauty?', o: ['Kylie Jenner', 'Rihanna', 'Selena Gomez', 'Ariana Grande'], c: 1, e: 'Rihanna launched Fenty Beauty in 2017.' },
  { d: 'medium', s: 'classic', q: 'Rapper Drake hails from which country?', o: ['USA', 'Canada', 'UK', 'Jamaica'], c: 1, e: 'Drake is from Toronto, Canada.' },
  { d: 'medium', s: 'classic', q: 'The annual Met Gala is a fundraising event centered on what?', o: ['Film', 'Fashion', 'Music', 'Architecture'], c: 1, e: 'The Met Gala celebrates fashion and costume.' },
  { d: 'medium', s: 'classic', q: 'Harry Styles first rose to fame in which boy band?', o: ['The Wanted', 'One Direction', 'Backstreet Boys', '5SOS'], c: 1, e: 'Harry Styles was part of One Direction.' },
  { d: 'medium', s: 'classic', q: 'Which 2019 film became (for a time) the highest-grossing of all time?', o: ['Avengers: Endgame', 'Frozen II', 'The Lion King', 'Joker'], c: 0, e: 'Avengers: Endgame topped the box office in 2019.' },
  { d: 'medium', s: 'classic', q: 'The popular sitcom "Friends" is set in which city?', o: ['Chicago', 'New York', 'Los Angeles', 'Boston'], c: 1, e: 'Friends is set in Manhattan, New York.' },
  { d: 'medium', s: 'classic', q: 'The 2024 "Brat summer" trend was tied to which pop artist\'s album?', o: ['Dua Lipa', 'Charli XCX', 'Billie Eilish', 'Sabrina Carpenter'], c: 1, e: 'Charli XCX\'s album "Brat" drove the trend.' },
  // Hard (11)
  { d: 'hard', s: 'classic', q: 'What was the title of the very first video uploaded to YouTube?', o: ['Charlie Bit My Finger', 'Me at the zoo', 'Evolution of Dance', 'Lazy Sunday'], c: 1, e: '"Me at the zoo" was uploaded in 2005.' },
  { d: 'hard', s: 'classic', q: 'Which artist holds the record for the most Grammy Awards won?', o: ['Quincy Jones', 'Beyoncé', 'Stevie Wonder', 'Adele'], c: 1, e: 'Beyoncé holds the most Grammy wins.' },
  { d: 'hard', s: 'classic', q: 'In the acronym "EGOT", the "T" stands for which award?', o: ['Theatre', 'Tony', 'Telly', 'Turner'], c: 1, e: 'EGOT = Emmy, Grammy, Oscar, Tony.' },
  { d: 'hard', s: 'classic', q: 'Who became the first woman to win the Best Director Oscar?', o: ['Greta Gerwig', 'Kathryn Bigelow', 'Sofia Coppola', 'Jane Campion'], c: 1, e: 'Kathryn Bigelow won for The Hurt Locker (2010).' },
  { d: 'hard', s: 'classic', q: 'Which is the longest-running primetime animated sitcom?', o: ['Family Guy', 'The Simpsons', 'South Park', 'Bob\'s Burgers'], c: 1, e: 'The Simpsons has aired since 1989.' },
  { d: 'hard', s: 'classic', q: 'The line "Why so serious?" is delivered by the Joker in which film?', o: ['Joker (2019)', 'The Dark Knight', 'Batman (1989)', 'Suicide Squad'], c: 1, e: 'Heath Ledger\'s Joker says it in The Dark Knight.' },
  { d: 'hard', s: 'classic', q: 'The prestigious Cannes Film Festival is held in which country?', o: ['Italy', 'France', 'Spain', 'Switzerland'], c: 1, e: 'Cannes is on the French Riviera.' },
  { d: 'hard', s: 'classic', q: 'Which three films are tied for the most Oscars ever won, at eleven each?', o: ['Ben-Hur, Titanic, LOTR: Return of the King', 'Avatar, Gladiator, Chicago', 'Parasite, Moonlight, Crash', 'Forrest Gump, Braveheart, The Aviator'], c: 0, e: 'Each of those three won 11 Academy Awards.' },
  { d: 'hard', s: 'classic', q: 'Which actor played James Bond in seven films, the most of any actor?', o: ['Sean Connery', 'Roger Moore', 'Pierce Brosnan', 'Daniel Craig'], c: 1, e: 'Roger Moore played Bond seven times.' },
  { d: 'hard', s: 'classic', q: 'The "Streisand effect" describes what phenomenon?', o: ['A song stuck in your head', 'Suppressing info making it spread more', 'Sudden celebrity breakups', 'Box office bombs'], c: 1, e: 'Trying to hide information often amplifies it.' },
  { d: 'hard', s: 'classic', q: 'Which musician\'s 1982 album held the record as best-selling for decades?', o: ['Prince – Purple Rain', 'Michael Jackson – Thriller', 'Fleetwood Mac – Rumours', 'AC/DC – Back in Black'], c: 1, e: 'Thriller remains the best-selling album ever.' },

  // ===== SET B — INDIAN / MALAYALI CULTURAL (35) =====
  // Easy (12)
  { d: 'easy', s: 'cultural', q: 'The viral song "Entammede Jimikki Kammal" is from which film?', o: ['Premam', 'Velipadinte Pusthakam', 'Bangalore Days', 'Charlie'], c: 1, e: 'The 2017 Mohanlal film made the song a global trend.' },
  { d: 'easy', s: 'cultural', q: 'The Malayalam word "Adipoli" means what?', o: ['Boring', 'Excellent/Amazing', 'Slow', 'Sad'], c: 1, e: '"Adipoli" expresses something awesome.' },
  { d: 'easy', s: 'cultural', q: 'Superstar Mohanlal is affectionately called what by fans?', o: ['Ikka', 'Lalettan', 'Thalaivar', 'Mega Star'], c: 1, e: 'Fans lovingly call Mohanlal "Lalettan".' },
  { d: 'easy', s: 'cultural', q: 'Superstar Mammootty is affectionately called what?', o: ['Lalettan', 'Ikka', 'Chiranjeevi', 'Anna'], c: 1, e: 'Mammootty is fondly known as "Ikka".' },
  { d: 'easy', s: 'cultural', q: 'Actor Dulquer Salmaan is the son of which Malayalam legend?', o: ['Mohanlal', 'Mammootty', 'Suresh Gopi', 'Jayaram'], c: 1, e: 'Dulquer is Mammootty\'s son.' },
  { d: 'easy', s: 'cultural', q: 'The Malayalam slang "Pwoli" means what?', o: ['Tired', 'Awesome/great', 'Hungry', 'Late'], c: 1, e: '"Pwoli" describes something great.' },
  { d: 'easy', s: 'cultural', q: 'The "Pookalam" flower carpet is a key tradition of which festival?', o: ['Vishu', 'Onam', 'Thiruvathira', 'Diwali'], c: 1, e: 'Elaborate Pookalams adorn homes during Onam.' },
  { d: 'easy', s: 'cultural', q: 'In casual Malayalam, "Machane" or "Machan" means what?', o: ['Boss', 'Buddy/bro', 'Stranger', 'Teacher'], c: 1, e: 'It is a friendly term for a close pal.' },
  { d: 'easy', s: 'cultural', q: 'The viral "Naatu Naatu" hook step comes from which film?', o: ['Pushpa', 'RRR', 'KGF', 'Baahubali'], c: 1, e: 'The dance is from RRR.' },
  { d: 'easy', s: 'cultural', q: 'Which actor played the meme-famous "Pushpa" with the chin-flick gesture?', o: ['Prabhas', 'Allu Arjun', 'Vijay', 'Ram Charan'], c: 1, e: 'Allu Arjun\'s Pushpa gesture became a meme.' },
  { d: 'easy', s: 'cultural', q: 'The 2015 hit "Premam" turned which actor into a youth icon?', o: ['Dulquer Salmaan', 'Nivin Pauly', 'Tovino Thomas', 'Fahadh Faasil'], c: 1, e: 'Nivin Pauly\'s "George" became iconic.' },
  { d: 'easy', s: 'cultural', q: 'The Malayalam exclamation "Kidu" expresses what?', o: ['Disappointment', 'Something superb', 'Confusion', 'Fear'], c: 1, e: '"Kidu" means top-class or superb.' },
  // Medium (12)
  { d: 'medium', s: 'cultural', q: 'Mohanlal\'s character in the blockbuster "Lucifer" is named what?', o: ['Stephen Nedumpally', 'Mangalassery Neelakandan', 'Aadu Thoma', 'Induchoodan'], c: 0, e: 'He plays Stephen Nedumpally / Khureshi-Ab\'raam.' },
  { d: 'medium', s: 'cultural', q: 'The viral "complete man" villain Shammi in "Kumbalangi Nights" was played by whom?', o: ['Soubin Shahir', 'Fahadh Faasil', 'Shane Nigam', 'Sreenath Bhasi'], c: 1, e: 'Fahadh Faasil\'s Shammi became iconic.' },
  { d: 'medium', s: 'cultural', q: 'The comedy classic duo Dasan and Vijayan ("Nadodikkattu") were played by whom?', o: ['Mohanlal & Sreenivasan', 'Mammootty & Jagathy', 'Mohanlal & Mukesh', 'Dileep & Kalabhavan Mani'], c: 0, e: 'Mohanlal and Sreenivasan starred as the duo.' },
  { d: 'medium', s: 'cultural', q: 'The psychological thriller classic "Manichithrathazhu" (1993) was directed by whom?', o: ['Priyadarshan', 'Fazil', 'Sibi Malayil', 'Bharathan'], c: 1, e: 'Fazil directed the cult classic.' },
  { d: 'medium', s: 'cultural', q: 'The folk-horror hit "Kantara" celebrates the culture of which region?', o: ['Kerala (Malabar)', 'Tulu Nadu (Karnataka)', 'Tamil Nadu', 'Andhra'], c: 1, e: 'Kantara depicts coastal Karnataka\'s Tulu traditions.' },
  { d: 'medium', s: 'cultural', q: 'The slang phrase "Set aanu" in Malayalam means what?', o: ['It\'s broken', 'It\'s fine/sorted', 'I\'m angry', 'Let\'s go'], c: 1, e: '"Set aanu" means everything is okay/sorted.' },
  { d: 'medium', s: 'cultural', q: 'Veteran comedian "Mamukkoya" was famous for roles speaking which dialect?', o: ['Travancore', 'Malabar/Kozhikode', 'Kochi', 'Kuttanad'], c: 1, e: 'Mamukkoya was beloved for his Kozhikode-style comedy.' },
  { d: 'medium', s: 'cultural', q: 'Actor Suresh Gopi is best known for which kind of mass roles?', o: ['Romantic leads', 'Police/action with punch dialogues', 'Comedy', 'Villain only'], c: 1, e: 'Suresh Gopi\'s cop roles spawned countless memes.' },
  { d: 'medium', s: 'cultural', q: 'The realistic small-town comedy "Maheshinte Prathikaaram" starred which actor?', o: ['Fahadh Faasil', 'Tovino Thomas', 'Asif Ali', 'Vineeth Sreenivasan'], c: 0, e: 'Fahadh Faasil played Mahesh.' },
  { d: 'medium', s: 'cultural', q: 'Fahadh Faasil\'s gangster "Ranga" in "Aavesham" operates mostly in which city?', o: ['Chennai', 'Bengaluru', 'Hyderabad', 'Kochi'], c: 1, e: 'Aavesham is set among Malayali students in Bengaluru.' },
  { d: 'medium', s: 'cultural', q: 'The comedy "CID Moosa" starred which actor in the lead?', o: ['Dileep', 'Jayaram', 'Kunchacko Boban', 'Jayasurya'], c: 0, e: 'Dileep played the bumbling detective Moosa.' },
  { d: 'medium', s: 'cultural', q: 'Sathyan Anthikad is celebrated in Malayalam cinema as a famous what?', o: ['Music director', 'Director', 'Cinematographer', 'Lyricist'], c: 1, e: 'Sathyan Anthikad is a beloved director of family films.' },
  // Hard (11)
  { d: 'hard', s: 'cultural', q: 'Mohanlal\'s iconic role "Aadu Thoma" is from which 1995 film?', o: ['Spadikam', 'Kireedam', 'Devasuram', 'Aaraam Thampuran'], c: 0, e: 'Aadu Thoma is the hero of Spadikam.' },
  { d: 'hard', s: 'cultural', q: 'Late comedian Innocent was renowned in Malayalam cinema as a master of what?', o: ['Action', 'Comedy', 'Singing', 'Dance'], c: 1, e: 'Innocent was a legendary comedy actor.' },
  { d: 'hard', s: 'cultural', q: 'Veteran actor Jagathy Sreekumar holds a notable record for acting in the most what?', o: ['TV serials', 'Films', 'Stage plays', 'Ads'], c: 1, e: 'He is celebrated for an enormous filmography.' },
  { d: 'hard', s: 'cultural', q: 'The cult emotional drama "Kireedam" (1989) starred which actor as Sethumadhavan?', o: ['Mammootty', 'Mohanlal', 'Suresh Gopi', 'Murali'], c: 1, e: 'Mohanlal played the tragic Sethumadhavan.' },
  { d: 'hard', s: 'cultural', q: 'In the film "Drishyam", Georgekutty\'s great passion that shapes the plot is what?', o: ['Cricket', 'Watching movies', 'Cooking', 'Music'], c: 1, e: 'His love of films inspires his alibi.' },
  { d: 'hard', s: 'cultural', q: 'The viral Manjummel Boys climax used the song "Kanmani Anbodu" originally from which film?', o: ['Guna', 'Nayakan', 'Roja', 'Bombay'], c: 0, e: 'The song is from the 1991 film Guna.' },
  { d: 'hard', s: 'cultural', q: 'Actor Soubin Shahir first won wide fan-love through which 2015 film?', o: ['Premam', 'Charlie', 'Action Hero Biju', 'Maheshinte Prathikaaram'], c: 0, e: 'His cameo in Premam went viral.' },
  { d: 'hard', s: 'cultural', q: 'The meme-famous dialogue "Mammooty\'s style" aside, which actor is called "The Complete Actor" in Malayalam fandom?', o: ['Mohanlal', 'Mammootty', 'Fahadh Faasil', 'Prithviraj'], c: 0, e: 'Mohanlal is often dubbed "The Complete Actor".' },
  { d: 'hard', s: 'cultural', q: 'The slang "Thallu" (as in "Thallumaala") refers to what?', o: ['A dance', 'A brawl/fight', 'A song', 'A feast'], c: 1, e: '"Thallu" colloquially means a fight.' },
  { d: 'hard', s: 'cultural', q: 'Which director is known for gritty films like "Angamaly Diaries" and "Jallikattu"?', o: ['Lijo Jose Pellissery', 'Dileesh Pothan', 'Aashiq Abu', 'Khalid Rahman'], c: 0, e: 'Lijo Jose Pellissery is known for his raw style.' },
  { d: 'hard', s: 'cultural', q: 'The phrase "Onnum ariyaatha Mathai" became a meme from which actor\'s persona?', o: ['Innocent', 'Salim Kumar', 'Suraj Venjaramoodu', 'Harisree Ashokan'], c: 0, e: 'It is tied to Innocent\'s comic everyman roles.' },
];
