// Topic: Science — 70 questions (all classic; Wave 1 fundamentals, Wave 2 recent science 2020-2025)
export default [
  // ===== WAVE 1 — FUNDAMENTALS (35) =====
  // Easy (12)
  { d: 'easy', s: 'classic', q: 'What is the chemical formula for water?', o: ['CO2', 'H2O', 'O2', 'NaCl'], c: 1, e: 'Water is two hydrogen atoms and one oxygen.' },
  { d: 'easy', s: 'classic', q: 'How many planets are in our Solar System?', o: ['7', '8', '9', '10'], c: 1, e: 'There are eight planets since Pluto was reclassified.' },
  { d: 'easy', s: 'classic', q: 'Which planet is closest to the Sun?', o: ['Venus', 'Mercury', 'Mars', 'Earth'], c: 1, e: 'Mercury orbits nearest the Sun.' },
  { d: 'easy', s: 'classic', q: 'Which gas do humans need to breathe to survive?', o: ['Carbon dioxide', 'Oxygen', 'Nitrogen', 'Hydrogen'], c: 1, e: 'We inhale oxygen for cellular respiration.' },
  { d: 'easy', s: 'classic', q: 'What is often called the "powerhouse of the cell"?', o: ['Nucleus', 'Mitochondria', 'Ribosome', 'Golgi body'], c: 1, e: 'Mitochondria produce the cell\'s energy (ATP).' },
  { d: 'easy', s: 'classic', q: 'What is the chemical symbol for gold?', o: ['Go', 'Gd', 'Au', 'Ag'], c: 2, e: 'Au comes from the Latin "aurum".' },
  { d: 'easy', s: 'classic', q: 'How many bones are in the adult human body?', o: ['206', '230', '180', '300'], c: 0, e: 'Adults have 206 bones.' },
  { d: 'easy', s: 'classic', q: 'What force pulls objects toward the Earth?', o: ['Magnetism', 'Gravity', 'Friction', 'Tension'], c: 1, e: 'Gravity attracts mass toward Earth\'s center.' },
  { d: 'easy', s: 'classic', q: 'Which is the largest planet in the Solar System?', o: ['Saturn', 'Jupiter', 'Neptune', 'Earth'], c: 1, e: 'Jupiter is the largest planet.' },
  { d: 'easy', s: 'classic', q: 'Plants make their own food through which process?', o: ['Respiration', 'Photosynthesis', 'Digestion', 'Fermentation'], c: 1, e: 'Photosynthesis converts sunlight into glucose.' },
  { d: 'easy', s: 'classic', q: 'Approximately how fast does light travel in a vacuum?', o: ['300,000 km/s', '30,000 km/s', '3,000 km/s', '3 million km/s'], c: 0, e: 'Light travels about 299,792 km per second.' },
  { d: 'easy', s: 'classic', q: 'What does the symbol "H" represent on the periodic table?', o: ['Helium', 'Hydrogen', 'Mercury', 'Hassium'], c: 1, e: 'H is hydrogen, the lightest element.' },
  // Medium (12)
  { d: 'medium', s: 'classic', q: 'Newton\'s First Law of Motion is also known as the law of what?', o: ['Gravity', 'Inertia', 'Acceleration', 'Momentum'], c: 1, e: 'Objects stay in motion or rest unless acted on — inertia.' },
  { d: 'medium', s: 'classic', q: 'What is the chemical symbol for sodium?', o: ['So', 'Sd', 'Na', 'S'], c: 2, e: 'Na comes from the Latin "natrium".' },
  { d: 'medium', s: 'classic', q: 'How many chromosomes does a typical human cell contain?', o: ['23', '46', '48', '92'], c: 1, e: 'Humans have 23 pairs, totaling 46.' },
  { d: 'medium', s: 'classic', q: 'What is the hardest naturally occurring substance?', o: ['Quartz', 'Diamond', 'Steel', 'Granite'], c: 1, e: 'Diamond ranks 10 on the Mohs scale.' },
  { d: 'medium', s: 'classic', q: 'What does "DNA" stand for?', o: ['Deoxyribonucleic acid', 'Dinucleic acid', 'Diribonucleic acid', 'Deoxyribose acid'], c: 0, e: 'DNA carries genetic instructions.' },
  { d: 'medium', s: 'classic', q: 'What is the pH value of pure, neutral water?', o: ['0', '7', '14', '1'], c: 1, e: 'Neutral water has a pH of 7.' },
  { d: 'medium', s: 'classic', q: 'Which planet is known as the "Red Planet"?', o: ['Venus', 'Mars', 'Jupiter', 'Mercury'], c: 1, e: 'Iron oxide gives Mars its red hue.' },
  { d: 'medium', s: 'classic', q: 'What is the SI unit of electrical resistance?', o: ['Volt', 'Ampere', 'Ohm', 'Watt'], c: 2, e: 'Resistance is measured in ohms (Ω).' },
  { d: 'medium', s: 'classic', q: 'Which part of a cell contains its genetic material?', o: ['Cytoplasm', 'Nucleus', 'Membrane', 'Vacuole'], c: 1, e: 'The nucleus holds the chromosomes.' },
  { d: 'medium', s: 'classic', q: 'Sound cannot travel through which of the following?', o: ['Water', 'Steel', 'A vacuum', 'Air'], c: 2, e: 'Sound needs a medium; a vacuum has none.' },
  { d: 'medium', s: 'classic', q: 'What is the most abundant gas in Earth\'s atmosphere?', o: ['Oxygen', 'Nitrogen', 'Carbon dioxide', 'Argon'], c: 1, e: 'Nitrogen makes up about 78% of the air.' },
  { d: 'medium', s: 'classic', q: 'The branch of science that studies living organisms is called what?', o: ['Geology', 'Biology', 'Chemistry', 'Physics'], c: 1, e: 'Biology is the study of life.' },
  // Hard (11)
  { d: 'hard', s: 'classic', q: 'The Uncertainty Principle is a key idea in which field?', o: ['Thermodynamics', 'Quantum mechanics', 'Optics', 'Astronomy'], c: 1, e: 'Heisenberg formulated it within quantum mechanics.' },
  { d: 'hard', s: 'classic', q: 'What is the chemical symbol for tungsten?', o: ['Tu', 'Tg', 'W', 'Tn'], c: 2, e: 'W comes from "wolfram".' },
  { d: 'hard', s: 'classic', q: 'How many elements are in the modern periodic table?', o: ['108', '112', '118', '124'], c: 2, e: 'There are 118 confirmed elements.' },
  { d: 'hard', s: 'classic', q: 'Who formulated the famous equation E = mc²?', o: ['Isaac Newton', 'Albert Einstein', 'Niels Bohr', 'Max Planck'], c: 1, e: 'Einstein published it in 1905.' },
  { d: 'hard', s: 'classic', q: 'The Higgs boson is associated with giving particles what property?', o: ['Charge', 'Mass', 'Spin', 'Color'], c: 1, e: 'The Higgs field endows particles with mass.' },
  { d: 'hard', s: 'classic', q: 'What is absolute zero approximately, in degrees Celsius?', o: ['0°C', '-100°C', '-273°C', '-373°C'], c: 2, e: 'Absolute zero is about -273.15°C.' },
  { d: 'hard', s: 'classic', q: 'CRISPR technology is primarily used for what?', o: ['Gene editing', 'Cloning organs', 'Carbon capture', 'Data storage'], c: 0, e: 'CRISPR allows precise editing of DNA.' },
  { d: 'hard', s: 'classic', q: 'Which pigment makes photosynthesis possible in plants?', o: ['Carotene', 'Chlorophyll', 'Melanin', 'Hemoglobin'], c: 1, e: 'Chlorophyll captures light energy.' },
  { d: 'hard', s: 'classic', q: 'The "half-life" of a substance refers to its rate of what?', o: ['Combustion', 'Radioactive decay', 'Evaporation', 'Crystallization'], c: 1, e: 'Half-life is the time for half the atoms to decay.' },
  { d: 'hard', s: 'classic', q: 'Which subatomic particle carries a negative charge?', o: ['Proton', 'Neutron', 'Electron', 'Positron'], c: 2, e: 'Electrons carry a negative charge.' },
  { d: 'hard', s: 'classic', q: 'What is the smallest unit of a chemical element that retains its properties?', o: ['Molecule', 'Atom', 'Cell', 'Compound'], c: 1, e: 'The atom is the basic unit of an element.' },

  // ===== WAVE 2 — RECENT SCIENCE 2020-2025 (35) =====
  // Easy (12)
  { d: 'easy', s: 'classic', q: 'The COVID-19 pandemic was caused by which virus?', o: ['H1N1', 'SARS-CoV-2', 'Ebola', 'MERS-CoV'], c: 1, e: 'SARS-CoV-2 emerged in late 2019.' },
  { d: 'easy', s: 'classic', q: 'Which space telescope launched in December 2021 as Hubble\'s successor?', o: ['Kepler', 'James Webb Space Telescope', 'Spitzer', 'TESS'], c: 1, e: 'JWST launched on Christmas Day 2021.' },
  { d: 'easy', s: 'classic', q: 'ChatGPT is best described as what kind of technology?', o: ['Search engine', 'AI chatbot / language model', 'Antivirus', 'Web browser'], c: 1, e: 'ChatGPT is a large language model chatbot.' },
  { d: 'easy', s: 'classic', q: 'mRNA vaccine technology was first widely deployed against which disease?', o: ['Malaria', 'COVID-19', 'Polio', 'Measles'], c: 1, e: 'Pfizer and Moderna used mRNA for COVID-19.' },
  { d: 'easy', s: 'classic', q: 'The first-ever image of a black hole was released in which year?', o: ['2015', '2019', '2021', '2023'], c: 1, e: 'The Event Horizon Telescope unveiled it in 2019.' },
  { d: 'easy', s: 'classic', q: 'Which company, founded by Elon Musk, builds reusable rockets?', o: ['Blue Origin', 'SpaceX', 'Virgin Galactic', 'Boeing'], c: 1, e: 'SpaceX pioneered reusable orbital rockets.' },
  { d: 'easy', s: 'classic', q: 'Which Indian mission successfully soft-landed on the Moon in 2023?', o: ['Chandrayaan-2', 'Chandrayaan-3', 'Mangalyaan', 'Aditya-L1'], c: 1, e: 'Chandrayaan-3 landed in August 2023.' },
  { d: 'easy', s: 'classic', q: 'The James Webb Space Telescope observes mainly in which kind of light?', o: ['Ultraviolet', 'Infrared', 'X-ray', 'Radio'], c: 1, e: 'JWST is optimized for infrared astronomy.' },
  { d: 'easy', s: 'classic', q: 'Which is a popular AI image-generation tool?', o: ['Photoshop', 'Midjourney', 'WinZip', 'Notepad'], c: 1, e: 'Midjourney generates images from text prompts.' },
  { d: 'easy', s: 'classic', q: 'In "5G" mobile technology, what does the "G" stand for?', o: ['Gigabyte', 'Generation', 'Global', 'Gateway'], c: 1, e: '5G is the fifth generation of mobile networks.' },
  { d: 'easy', s: 'classic', q: 'SpaceX\'s most-flown workhorse rocket is called what?', o: ['Falcon 9', 'Saturn V', 'Atlas', 'Delta IV'], c: 0, e: 'The reusable Falcon 9 launches frequently.' },
  { d: 'easy', s: 'classic', q: 'Which company created the GPT family of AI models?', o: ['Google', 'OpenAI', 'Meta', 'IBM'], c: 1, e: 'OpenAI develops GPT models.' },
  // Medium (12)
  { d: 'medium', s: 'classic', q: 'COVID-19 mRNA vaccines instruct cells to make which viral component?', o: ['Whole virus', 'Spike protein', 'RNA polymerase', 'Envelope'], c: 1, e: 'The body learns to recognize the spike protein.' },
  { d: 'medium', s: 'classic', q: 'The James Webb Telescope orbits near which gravitational point?', o: ['Low Earth orbit', 'Lagrange Point 2 (L2)', 'The Moon', 'Mars orbit'], c: 1, e: 'JWST sits at the Sun-Earth L2 point.' },
  { d: 'medium', s: 'classic', q: 'The 2019 black hole image showed the black hole at the center of which galaxy?', o: ['Andromeda', 'M87', 'Whirlpool', 'Sombrero'], c: 1, e: 'It captured the supermassive black hole in M87.' },
  { d: 'medium', s: 'classic', q: 'Chandrayaan-3 made history by landing near which lunar region?', o: ['Equator', 'South Pole', 'Far side center', 'Sea of Tranquility'], c: 1, e: 'India was first to land near the lunar south pole.' },
  { d: 'medium', s: 'classic', q: 'The 2020 Nobel Prize in Chemistry honored the development of which tool?', o: ['mRNA vaccines', 'CRISPR-Cas9 gene editing', 'PCR testing', 'Quantum dots'], c: 1, e: 'Doudna and Charpentier won for CRISPR-Cas9.' },
  { d: 'medium', s: 'classic', q: 'NASA\'s Perseverance rover landed on Mars in which year?', o: ['2018', '2021', '2023', '2016'], c: 1, e: 'Perseverance touched down in Jezero Crater in 2021.' },
  { d: 'medium', s: 'classic', q: 'The "Ingenuity" helicopter achieved powered flight on which planet?', o: ['Venus', 'Mars', 'The Moon', 'Titan'], c: 1, e: 'Ingenuity was the first aircraft to fly on Mars.' },
  { d: 'medium', s: 'classic', q: 'The heavily transmissible COVID variant "Omicron" was identified in which year?', o: ['2019', '2020', '2021', '2022'], c: 2, e: 'Omicron was reported in late 2021.' },
  { d: 'medium', s: 'classic', q: 'In 2022, scientists at NIF achieved a milestone in which technology?', o: ['Quantum computing', 'Nuclear fusion ignition', 'Cold fusion', 'Antimatter storage'], c: 1, e: 'They produced net energy gain from a fusion reaction.' },
  { d: 'medium', s: 'classic', q: 'The AI system "AlphaFold" famously predicts what?', o: ['Weather', 'Protein structures', 'Stock prices', 'Earthquakes'], c: 1, e: 'AlphaFold predicts 3D protein folding.' },
  { d: 'medium', s: 'classic', q: 'India\'s mission to study the Sun, launched in 2023, is called what?', o: ['Gaganyaan', 'Aditya-L1', 'Mangalyaan', 'Astrosat'], c: 1, e: 'Aditya-L1 observes the Sun from the L1 point.' },
  { d: 'medium', s: 'classic', q: 'Which two scientists shared the 2020 Chemistry Nobel for CRISPR?', o: ['Doudna & Charpentier', 'Watson & Crick', 'Karikó & Weissman', 'Penrose & Genzel'], c: 0, e: 'Jennifer Doudna and Emmanuelle Charpentier won.' },
  // Hard (11)
  { d: 'hard', s: 'classic', q: 'The 2023 Nobel Prize in Medicine recognized mRNA vaccine research by whom?', o: ['Doudna & Charpentier', 'Karikó & Weissman', 'Allison & Honjo', 'Lander & Zhang'], c: 1, e: 'Katalin Karikó and Drew Weissman won for mRNA work.' },
  { d: 'hard', s: 'classic', q: 'CERN\'s Large Hadron Collider confirmed the Higgs boson in which year?', o: ['2008', '2012', '2015', '2019'], c: 1, e: 'The Higgs discovery was announced in 2012.' },
  { d: 'hard', s: 'classic', q: 'Which collaboration captured the first image of a black hole?', o: ['LIGO', 'Event Horizon Telescope', 'SKA', 'Gaia'], c: 1, e: 'The EHT links radio telescopes worldwide.' },
  { d: 'hard', s: 'classic', q: 'The James Webb Telescope\'s primary mirror is coated with what metal?', o: ['Silver', 'Gold', 'Aluminum', 'Platinum'], c: 1, e: 'A thin gold layer optimizes infrared reflection.' },
  { d: 'hard', s: 'classic', q: 'Roger Penrose shared the 2020 Physics Nobel for theoretical work on what?', o: ['Dark matter', 'Black holes', 'Neutrinos', 'Gravitational waves'], c: 1, e: 'He proved black hole formation follows from relativity.' },
  { d: 'hard', s: 'classic', q: 'The international fusion reactor "ITER" is being built in which country?', o: ['United States', 'France', 'Japan', 'South Korea'], c: 1, e: 'ITER is under construction in southern France.' },
  { d: 'hard', s: 'classic', q: 'AlphaFold was developed by which AI lab?', o: ['OpenAI', 'DeepMind', 'Anthropic', 'Meta AI'], c: 1, e: 'Google DeepMind created AlphaFold.' },
  { d: 'hard', s: 'classic', q: 'The 2022 image of "Sagittarius A*" showed the black hole at the center of what?', o: ['Andromeda', 'The Milky Way', 'M87', 'The Large Magellanic Cloud'], c: 1, e: 'Sgr A* is our galaxy\'s central black hole.' },
  { d: 'hard', s: 'classic', q: 'NASA\'s "Artemis" program aims to return humans to which destination?', o: ['Mars', 'The Moon', 'An asteroid', 'Venus'], c: 1, e: 'Artemis targets a crewed return to the Moon.' },
  { d: 'hard', s: 'classic', q: 'SARS-CoV-2 belongs to which family of viruses?', o: ['Influenza viruses', 'Coronaviruses', 'Retroviruses', 'Adenoviruses'], c: 1, e: 'It is a coronavirus, named for its crown-like spikes.' },
  { d: 'hard', s: 'classic', q: 'The DeepMind program that mastered the game of Go was called what?', o: ['AlphaGo', 'Deep Blue', 'Watson', 'AlphaFold'], c: 0, e: 'AlphaGo beat world champion Lee Sedol in 2016.' },
];
