// Topic: Sports — 70 questions (35 classic + 35 Indian/Malayali cultural)
export default [
  // ===== SET A — CLASSIC / GLOBAL (35) =====
  // Easy (12)
  { d: 'easy', s: 'classic', q: 'How many players are on the field per side in football (soccer)?', o: ['9', '10', '11', '12'], c: 2, e: 'Each soccer team fields 11 players.' },
  { d: 'easy', s: 'classic', q: 'In which sport is a score of zero called "love"?', o: ['Tennis', 'Cricket', 'Golf', 'Badminton'], c: 0, e: 'Tennis uses "love" for zero.' },
  { d: 'easy', s: 'classic', q: 'The modern Summer Olympics are held every how many years?', o: ['2', '3', '4', '5'], c: 2, e: 'The Summer Games occur every four years.' },
  { d: 'easy', s: 'classic', q: 'Michael Jordan is a legend of which sport?', o: ['Baseball', 'Basketball', 'American Football', 'Tennis'], c: 1, e: 'Jordan starred for the Chicago Bulls in the NBA.' },
  { d: 'easy', s: 'classic', q: 'How many rings appear on the Olympic flag?', o: ['4', '5', '6', '7'], c: 1, e: 'Five interlocking rings represent the continents.' },
  { d: 'easy', s: 'classic', q: 'A "slam dunk" is a move in which sport?', o: ['Volleyball', 'Basketball', 'Handball', 'Netball'], c: 1, e: 'A dunk pushes the ball down through the hoop.' },
  { d: 'easy', s: 'classic', q: 'Usain Bolt is world-famous in which discipline?', o: ['Long jump', 'Sprinting', 'Marathon', 'Hurdles'], c: 1, e: 'Bolt holds the 100m and 200m world records.' },
  { d: 'easy', s: 'classic', q: 'The FIFA World Cup is the top tournament for which sport?', o: ['Rugby', 'Football (soccer)', 'Cricket', 'Hockey'], c: 1, e: 'FIFA governs world football.' },
  { d: 'easy', s: 'classic', q: 'How many points is a touchdown worth in American football?', o: ['3', '6', '7', '2'], c: 1, e: 'A touchdown is worth six points.' },
  { d: 'easy', s: 'classic', q: 'The sport of cricket originated in which country?', o: ['India', 'Australia', 'England', 'South Africa'], c: 2, e: 'Cricket began in England.' },
  { d: 'easy', s: 'classic', q: 'The term "hat-trick" originated in which sport?', o: ['Football', 'Cricket', 'Hockey', 'Tennis'], c: 1, e: 'It first described three wickets in three balls in cricket.' },
  { d: 'easy', s: 'classic', q: 'Roger Federer is a champion of which sport?', o: ['Golf', 'Tennis', 'Squash', 'Badminton'], c: 1, e: 'Federer won 20 Grand Slam singles titles.' },
  // Medium (12)
  { d: 'medium', s: 'classic', q: 'Which country has won the most FIFA World Cups?', o: ['Germany', 'Brazil', 'Italy', 'Argentina'], c: 1, e: 'Brazil has won the World Cup five times.' },
  { d: 'medium', s: 'classic', q: 'The Tour de France is a major competition in which sport?', o: ['Running', 'Cycling', 'Motorsport', 'Rowing'], c: 1, e: 'The Tour de France is the premier road cycling race.' },
  { d: 'medium', s: 'classic', q: 'How many players from one team are on the court in basketball?', o: ['4', '5', '6', '7'], c: 1, e: 'Each basketball team plays five at a time.' },
  { d: 'medium', s: 'classic', q: 'Whose NBA all-time scoring record did LeBron James break in 2023?', o: ['Michael Jordan', 'Kareem Abdul-Jabbar', 'Kobe Bryant', 'Karl Malone'], c: 1, e: 'LeBron passed Kareem Abdul-Jabbar.' },
  { d: 'medium', s: 'classic', q: 'The Ashes is a Test cricket rivalry between England and which country?', o: ['India', 'Australia', 'South Africa', 'New Zealand'], c: 1, e: 'The Ashes is contested by England and Australia.' },
  { d: 'medium', s: 'classic', q: 'In golf, a score of one under par on a hole is called what?', o: ['Eagle', 'Birdie', 'Bogey', 'Par'], c: 1, e: 'One under par is a birdie.' },
  { d: 'medium', s: 'classic', q: 'Which country hosted the 2022 FIFA World Cup?', o: ['Russia', 'Qatar', 'Brazil', 'UAE'], c: 1, e: 'Qatar hosted the first Middle Eastern World Cup.' },
  { d: 'medium', s: 'classic', q: 'Lionel Messi led which nation to victory at the 2022 World Cup?', o: ['Brazil', 'Argentina', 'France', 'Spain'], c: 1, e: 'Argentina beat France in the final.' },
  { d: 'medium', s: 'classic', q: 'How many Grand Slam tournaments are there in tennis each year?', o: ['3', '4', '5', '6'], c: 1, e: 'The four Slams are Australian, French, Wimbledon and US Open.' },
  { d: 'medium', s: 'classic', q: 'Wimbledon, the oldest tennis Grand Slam, is played on which surface?', o: ['Clay', 'Grass', 'Hard court', 'Carpet'], c: 1, e: 'Wimbledon is the only Slam on grass.' },
  { d: 'medium', s: 'classic', q: 'Which German driver has won seven Formula 1 World Championships?', o: ['Sebastian Vettel', 'Michael Schumacher', 'Nico Rosberg', 'Niki Lauda'], c: 1, e: 'Schumacher won seven F1 titles, a record later equalled by Hamilton.' },
  { d: 'medium', s: 'classic', q: 'Serena Williams dominated which sport for two decades?', o: ['Golf', 'Tennis', 'Athletics', 'Swimming'], c: 1, e: 'Serena won 23 Grand Slam singles titles.' },
  // Hard (11)
  { d: 'hard', s: 'classic', q: 'Which country won the 2022 FIFA World Cup?', o: ['France', 'Argentina', 'Croatia', 'Brazil'], c: 1, e: 'Argentina won on penalties against France.' },
  { d: 'hard', s: 'classic', q: 'What is the official distance of a marathon?', o: ['40.0 km', '42.195 km', '45.0 km', '38.5 km'], c: 1, e: 'A marathon is 42.195 km (26.2 miles).' },
  { d: 'hard', s: 'classic', q: 'In cricket, a batter dismissed for zero runs is said to be out for a what?', o: ['Blob', 'Duck', 'Goose', 'Zero ball'], c: 1, e: 'A score of zero is a "duck".' },
  { d: 'hard', s: 'classic', q: 'The traditional Olympic motto translates to "Faster, Higher, ____".', o: ['Bolder', 'Stronger', 'Braver', 'Together'], c: 1, e: 'Citius, Altius, Fortius — Faster, Higher, Stronger.' },
  { d: 'hard', s: 'classic', q: 'Which boxer famously called himself "The Greatest"?', o: ['Mike Tyson', 'Muhammad Ali', 'Joe Frazier', 'George Foreman'], c: 1, e: 'Muhammad Ali was "The Greatest".' },
  { d: 'hard', s: 'classic', q: 'Who holds the record for most men\'s tennis Grand Slam singles titles?', o: ['Rafael Nadal', 'Novak Djokovic', 'Roger Federer', 'Pete Sampras'], c: 1, e: 'Djokovic has won 24 Grand Slam singles titles.' },
  { d: 'hard', s: 'classic', q: 'The 1936 Summer Olympics were held in which city?', o: ['Berlin', 'Amsterdam', 'Los Angeles', 'London'], c: 0, e: 'Berlin hosted the 1936 Games.' },
  { d: 'hard', s: 'classic', q: 'How many players are on the field per side in rugby union?', o: ['13', '15', '11', '7'], c: 1, e: 'Rugby union teams field 15 players.' },
  { d: 'hard', s: 'classic', q: 'Which country has won the most Olympic gold medals in history?', o: ['Russia', 'USA', 'China', 'Germany'], c: 1, e: 'The United States leads the all-time gold count.' },
  { d: 'hard', s: 'classic', q: 'The first modern Olympic Games (1896) were held in which city?', o: ['Paris', 'Athens', 'London', 'Rome'], c: 1, e: 'The modern Olympics began in Athens, Greece.' },
  { d: 'hard', s: 'classic', q: 'In US horse racing, the Triple Crown is the Kentucky Derby, the Preakness, and which race?', o: ['Royal Ascot', 'Belmont Stakes', 'Melbourne Cup', 'Breeders\' Cup'], c: 1, e: 'The Belmont Stakes completes the Triple Crown.' },

  // ===== SET B — INDIAN / MALAYALI CULTURAL (35) =====
  // Easy (12)
  { d: 'easy', s: 'cultural', q: 'India won the 2024 T20 World Cup by defeating which team in the final?', o: ['Australia', 'England', 'South Africa', 'Pakistan'], c: 2, e: 'India beat South Africa in the Barbados final.' },
  { d: 'easy', s: 'cultural', q: 'Which team won the IPL 2024 season?', o: ['Chennai Super Kings', 'Mumbai Indians', 'Kolkata Knight Riders', 'Royal Challengers'], c: 2, e: 'Kolkata Knight Riders won IPL 2024.' },
  { d: 'easy', s: 'cultural', q: 'Praggnanandhaa is a young Indian star in which sport?', o: ['Badminton', 'Chess', 'Table tennis', 'Squash'], c: 1, e: 'R. Praggnanandhaa is a chess grandmaster.' },
  { d: 'easy', s: 'cultural', q: 'Neeraj Chopra won India\'s historic Olympic gold in which event?', o: ['Long jump', 'Javelin throw', 'Shot put', 'Discus'], c: 1, e: 'Chopra won javelin gold at the Tokyo Olympics.' },
  { d: 'easy', s: 'cultural', q: 'Virat Kohli is a global star in which sport?', o: ['Hockey', 'Cricket', 'Football', 'Kabaddi'], c: 1, e: 'Kohli is one of cricket\'s greatest batters.' },
  { d: 'easy', s: 'cultural', q: 'Who captained India to the 2011 ODI Cricket World Cup title?', o: ['Sourav Ganguly', 'MS Dhoni', 'Virat Kohli', 'Rahul Dravid'], c: 1, e: 'MS Dhoni led India to the 2011 World Cup.' },
  { d: 'easy', s: 'cultural', q: 'Sachin Tendulkar is reverently called the "God of" which sport?', o: ['Hockey', 'Cricket', 'Tennis', 'Football'], c: 1, e: 'Tendulkar is the "God of Cricket".' },
  { d: 'easy', s: 'cultural', q: 'The IPL is a franchise league for which sport?', o: ['Football', 'Cricket', 'Kabaddi', 'Hockey'], c: 1, e: 'The Indian Premier League is T20 cricket.' },
  { d: 'easy', s: 'cultural', q: 'Rohit Sharma is popularly nicknamed what?', o: ['The Wall', 'Hitman', 'Captain Cool', 'Master Blaster'], c: 1, e: 'Rohit Sharma is known as the "Hitman".' },
  { d: 'easy', s: 'cultural', q: 'P. V. Sindhu, an Olympic medallist, competes in which sport?', o: ['Tennis', 'Badminton', 'Boxing', 'Wrestling'], c: 1, e: 'Sindhu is a star badminton player.' },
  { d: 'easy', s: 'cultural', q: 'The Pro Kabaddi League made which traditional sport a TV phenomenon?', o: ['Kho Kho', 'Kabaddi', 'Mallakhamb', 'Gilli Danda'], c: 1, e: 'PKL popularized kabaddi nationwide.' },
  { d: 'easy', s: 'cultural', q: 'Kerala Blasters is a fan-favorite club in which Indian league?', o: ['IPL', 'Indian Super League (football)', 'Pro Kabaddi', 'Hockey India League'], c: 1, e: 'Kerala Blasters play football in the ISL.' },
  // Medium (12)
  { d: 'medium', s: 'cultural', q: 'Neeraj Chopra\'s gold-winning javelin throw came at which Olympics?', o: ['Rio 2016', 'Tokyo 2020', 'Paris 2024', 'London 2012'], c: 1, e: 'He won at the Tokyo Olympics (held in 2021).' },
  { d: 'medium', s: 'cultural', q: 'India defeated which team in the final of the 2011 ODI World Cup?', o: ['Pakistan', 'Sri Lanka', 'Australia', 'England'], c: 1, e: 'India beat Sri Lanka in Mumbai.' },
  { d: 'medium', s: 'cultural', q: 'The Indian Premier League (IPL) was launched in which year?', o: ['2006', '2008', '2010', '2012'], c: 1, e: 'The first IPL season was in 2008.' },
  { d: 'medium', s: 'cultural', q: 'Which team won the very first IPL title in 2008?', o: ['Chennai Super Kings', 'Rajasthan Royals', 'Mumbai Indians', 'Deccan Chargers'], c: 1, e: 'Rajasthan Royals won under Shane Warne.' },
  { d: 'medium', s: 'cultural', q: 'Abhinav Bindra won India\'s first individual Olympic gold in which sport?', o: ['Wrestling', 'Shooting', 'Boxing', 'Archery'], c: 1, e: 'Bindra won 10m air rifle gold in 2008.' },
  { d: 'medium', s: 'cultural', q: 'Mary Kom is a celebrated Indian champion in which sport?', o: ['Wrestling', 'Boxing', 'Weightlifting', 'Judo'], c: 1, e: 'Mary Kom is a multiple-time world boxing champion.' },
  { d: 'medium', s: 'cultural', q: 'Sunil Chhetri is the long-time captain of India in which sport?', o: ['Cricket', 'Football', 'Hockey', 'Kabaddi'], c: 1, e: 'Chhetri is India\'s football talisman.' },
  { d: 'medium', s: 'cultural', q: 'India\'s men\'s hockey team won bronze at Tokyo 2020, ending a drought of how long?', o: ['21 years', '31 years', '41 years', '51 years'], c: 2, e: 'It was India\'s first Olympic hockey medal in 41 years.' },
  { d: 'medium', s: 'cultural', q: 'Saina Nehwal, a former world No. 1, plays which sport?', o: ['Tennis', 'Badminton', 'Squash', 'Table tennis'], c: 1, e: 'Saina Nehwal is a badminton great.' },
  { d: 'medium', s: 'cultural', q: 'Pankaj Advani has won numerous world titles in which cue sport?', o: ['Snooker/Billiards', 'Pool only', 'Carrom', 'Darts'], c: 0, e: 'Advani dominates billiards and snooker.' },
  { d: 'medium', s: 'cultural', q: 'Harmanpreet Kaur captains India in which sport?', o: ['Hockey', 'Women\'s cricket', 'Kabaddi', 'Football'], c: 1, e: 'Harmanpreet Kaur leads India\'s women\'s cricket team.' },
  { d: 'medium', s: 'cultural', q: 'Which legend hit the winning six in the 2011 World Cup final?', o: ['Yuvraj Singh', 'MS Dhoni', 'Gautam Gambhir', 'Virat Kohli'], c: 1, e: 'Dhoni\'s six sealed India\'s win.' },
  // Hard (11)
  { d: 'hard', s: 'cultural', q: 'Who holds the record for the most runs in international cricket?', o: ['Ricky Ponting', 'Sachin Tendulkar', 'Kumar Sangakkara', 'Virat Kohli'], c: 1, e: 'Tendulkar scored over 34,000 international runs.' },
  { d: 'hard', s: 'cultural', q: 'India\'s 1983 World Cup triumph came against which team in the final?', o: ['Australia', 'West Indies', 'England', 'Pakistan'], c: 1, e: 'Kapil Dev\'s India beat the West Indies at Lord\'s.' },
  { d: 'hard', s: 'cultural', q: 'The 2024 T20 World Cup final was hosted at which venue?', o: ['Lord\'s, England', 'Barbados', 'Mumbai', 'Melbourne'], c: 1, e: 'The final was played in Bridgetown, Barbados.' },
  { d: 'hard', s: 'cultural', q: 'Praggnanandhaa finished runner-up at the 2023 Chess World Cup to whom?', o: ['Fabiano Caruana', 'Magnus Carlsen', 'Ding Liren', 'Hikaru Nakamura'], c: 1, e: 'He lost the final to Magnus Carlsen.' },
  { d: 'hard', s: 'cultural', q: 'Viswanathan Anand is a five-time world champion in which game?', o: ['Bridge', 'Chess', 'Carrom', 'Scrabble'], c: 1, e: 'Anand was a dominant chess world champion.' },
  { d: 'hard', s: 'cultural', q: 'Spinner Harbhajan Singh is nicknamed what?', o: ['The Turbanator', 'The Wizard', 'The Magician', 'The Spin King'], c: 0, e: 'Harbhajan earned the "Turbanator" nickname.' },
  { d: 'hard', s: 'cultural', q: 'Jasprit Bumrah is renowned for which bowling discipline?', o: ['Off spin', 'Leg spin', 'Fast (pace) bowling', 'Left-arm spin'], c: 2, e: 'Bumrah is a world-class fast bowler.' },
  { d: 'hard', s: 'cultural', q: 'The Ranji Trophy is India\'s premier domestic championship in which sport?', o: ['Football', 'Cricket', 'Hockey', 'Badminton'], c: 1, e: 'The Ranji Trophy is first-class domestic cricket.' },
  { d: 'hard', s: 'cultural', q: 'Wrestler Sushil Kumar won Olympic medals at consecutive Games in which sport?', o: ['Boxing', 'Wrestling', 'Judo', 'Weightlifting'], c: 1, e: 'Sushil Kumar won wrestling medals in 2008 and 2012.' },
  { d: 'hard', s: 'cultural', q: 'Which Indian shuttler won a silver medal at the 2016 Rio Olympics?', o: ['Saina Nehwal', 'P. V. Sindhu', 'Ashwini Ponnappa', 'Jwala Gutta'], c: 1, e: 'Sindhu won silver in Rio 2016.' },
  { d: 'hard', s: 'cultural', q: 'MS Dhoni is famously nicknamed what for his calm under pressure?', o: ['Captain Cool', 'The Wall', 'Mr. 360', 'The Finisher King'], c: 0, e: 'Dhoni is widely known as "Captain Cool".' },
];
