// Topic: Technology — 70 questions (35 classic + 35 Indian/cultural & AI)
export default [
  // ===== SET A — CLASSIC / GLOBAL (35) =====
  // Easy (12)
  { d: 'easy', s: 'classic', q: 'Who co-founded Apple alongside Steve Wozniak?', o: ['Bill Gates', 'Steve Jobs', 'Jeff Bezos', 'Larry Page'], c: 1, e: 'Steve Jobs co-founded Apple in 1976.' },
  { d: 'easy', s: 'classic', q: 'Which company makes the Windows operating system?', o: ['Apple', 'Microsoft', 'Google', 'IBM'], c: 1, e: 'Microsoft develops Windows.' },
  { d: 'easy', s: 'classic', q: 'What does "www" stand for?', o: ['World Wide Web', 'Web Wide World', 'Wireless Web Workspace', 'World Web Window'], c: 0, e: 'WWW is the World Wide Web.' },
  { d: 'easy', s: 'classic', q: 'Who is the founder of Facebook (now Meta)?', o: ['Elon Musk', 'Mark Zuckerberg', 'Jack Dorsey', 'Evan Spiegel'], c: 1, e: 'Mark Zuckerberg founded Facebook in 2004.' },
  { d: 'easy', s: 'classic', q: 'What does "PDF" stand for?', o: ['Portable Document Format', 'Public Data File', 'Printed Document Form', 'Personal Data Folder'], c: 0, e: 'PDF is the Portable Document Format.' },
  { d: 'easy', s: 'classic', q: 'Which company makes the iPhone?', o: ['Samsung', 'Apple', 'Nokia', 'Sony'], c: 1, e: 'Apple makes the iPhone.' },
  { d: 'easy', s: 'classic', q: 'The "brain" of a computer is commonly called the what?', o: ['RAM', 'CPU', 'GPU', 'SSD'], c: 1, e: 'The CPU is the central processing unit.' },
  { d: 'easy', s: 'classic', q: 'What does "RAM" stand for?', o: ['Random Access Memory', 'Rapid Action Module', 'Read Allocate Memory', 'Run Access Mode'], c: 0, e: 'RAM is a computer\'s short-term memory.' },
  { d: 'easy', s: 'classic', q: 'Which company owns YouTube?', o: ['Meta', 'Google', 'Amazon', 'Microsoft'], c: 1, e: 'Google acquired YouTube in 2006.' },
  { d: 'easy', s: 'classic', q: 'Who leads the electric carmaker Tesla?', o: ['Tim Cook', 'Elon Musk', 'Sundar Pichai', 'Jensen Huang'], c: 1, e: 'Elon Musk is Tesla\'s CEO.' },
  { d: 'easy', s: 'classic', q: 'What does "USB" stand for?', o: ['Universal Serial Bus', 'United System Bus', 'Universal Storage Box', 'User Service Bus'], c: 0, e: 'USB is the Universal Serial Bus.' },
  { d: 'easy', s: 'classic', q: 'Which company developed the Android operating system?', o: ['Apple', 'Google', 'Microsoft', 'Samsung'], c: 1, e: 'Google develops Android.' },
  // Medium (12)
  { d: 'medium', s: 'classic', q: 'Who co-founded Microsoft with Paul Allen?', o: ['Steve Ballmer', 'Bill Gates', 'Steve Jobs', 'Larry Ellison'], c: 1, e: 'Bill Gates co-founded Microsoft in 1975.' },
  { d: 'medium', s: 'classic', q: 'Which programming language shares its name with a type of snake?', o: ['Java', 'Python', 'Ruby', 'Cobra'], c: 1, e: 'Python was named after Monty Python, not the snake — but shares the name.' },
  { d: 'medium', s: 'classic', q: 'In which year was the first iPhone released?', o: ['2005', '2007', '2009', '2010'], c: 1, e: 'Apple launched the first iPhone in 2007.' },
  { d: 'medium', s: 'classic', q: 'What does "HTML" stand for?', o: ['HyperText Markup Language', 'High Tech Modern Language', 'Hyperlink Text Mode Layer', 'Home Tool Markup Language'], c: 0, e: 'HTML structures web pages.' },
  { d: 'medium', s: 'classic', q: 'Who founded the online retailer Amazon?', o: ['Jeff Bezos', 'Larry Page', 'Jack Ma', 'Michael Dell'], c: 0, e: 'Jeff Bezos founded Amazon in 1994.' },
  { d: 'medium', s: 'classic', q: 'Which company acquired Instagram in 2012?', o: ['Google', 'Facebook (Meta)', 'Twitter', 'Snap'], c: 1, e: 'Facebook bought Instagram for about $1 billion.' },
  { d: 'medium', s: 'classic', q: 'What does "AI" stand for?', o: ['Automated Interface', 'Artificial Intelligence', 'Advanced Internet', 'Applied Integration'], c: 1, e: 'AI is Artificial Intelligence.' },
  { d: 'medium', s: 'classic', q: 'Which early browser popularized the web in the mid-1990s?', o: ['Internet Explorer', 'Netscape Navigator', 'Safari', 'Chrome'], c: 1, e: 'Netscape Navigator dominated the early web.' },
  { d: 'medium', s: 'classic', q: 'What does "CPU" stand for?', o: ['Central Processing Unit', 'Computer Power Unit', 'Core Program Utility', 'Central Program Unit'], c: 0, e: 'CPU is the Central Processing Unit.' },
  { d: 'medium', s: 'classic', q: 'Which company manufactures the PlayStation console?', o: ['Microsoft', 'Sony', 'Nintendo', 'Sega'], c: 1, e: 'Sony makes the PlayStation.' },
  { d: 'medium', s: 'classic', q: 'Twitter was rebranded to which single letter in 2023?', o: ['Z', 'X', 'T', 'Q'], c: 1, e: 'Elon Musk rebranded Twitter as "X".' },
  { d: 'medium', s: 'classic', q: 'Which company is the parent of Google, created in 2015?', o: ['Alphabet', 'Meta', 'Oracle', 'Tesla'], c: 0, e: 'Alphabet Inc. is Google\'s parent company.' },
  // Hard (11)
  { d: 'hard', s: 'classic', q: 'Who is widely regarded as the first computer programmer?', o: ['Grace Hopper', 'Ada Lovelace', 'Alan Turing', 'Margaret Hamilton'], c: 1, e: 'Ada Lovelace wrote an algorithm for Babbage\'s engine.' },
  { d: 'hard', s: 'classic', q: 'What does "HTTP" stand for?', o: ['HyperText Transfer Protocol', 'High Transfer Text Process', 'Host Transmission Transfer Path', 'HyperText Transmit Program'], c: 0, e: 'HTTP moves data across the web.' },
  { d: 'hard', s: 'classic', q: 'Who is credited as the inventor of the World Wide Web?', o: ['Vint Cerf', 'Tim Berners-Lee', 'Bill Gates', 'Steve Wozniak'], c: 1, e: 'Tim Berners-Lee invented the Web in 1989.' },
  { d: 'hard', s: 'classic', q: 'Moore\'s Law predicts the doubling of what about every two years?', o: ['Internet speed', 'Transistors on a chip', 'Hard drive size', 'Screen resolution'], c: 1, e: 'It describes transistor density doubling over time.' },
  { d: 'hard', s: 'classic', q: 'What does "SQL" stand for?', o: ['Structured Query Language', 'System Quality Layer', 'Sequential Query Logic', 'Standard Question List'], c: 0, e: 'SQL manages relational databases.' },
  { d: 'hard', s: 'classic', q: 'ENIAC, completed in 1945, is famous as one of the first what?', o: ['Smartphones', 'Electronic general-purpose computers', 'Operating systems', 'Search engines'], c: 1, e: 'ENIAC was an early electronic computer.' },
  { d: 'hard', s: 'classic', q: 'The binary number system uses which two digits?', o: ['1 and 2', '0 and 1', '0 and 9', '1 and 10'], c: 1, e: 'Binary uses only 0 and 1.' },
  { d: 'hard', s: 'classic', q: 'What does "GPU" stand for?', o: ['General Processing Unit', 'Graphics Processing Unit', 'Global Power Unit', 'Grid Program Utility'], c: 1, e: 'GPUs handle graphics and parallel computation.' },
  { d: 'hard', s: 'classic', q: 'The open-source Linux kernel was created by whom?', o: ['Richard Stallman', 'Linus Torvalds', 'Dennis Ritchie', 'Ken Thompson'], c: 1, e: 'Linus Torvalds released Linux in 1991.' },
  { d: 'hard', s: 'classic', q: 'Which company designs the ARM CPU architecture used in most smartphones?', o: ['Intel', 'Arm Holdings', 'AMD', 'Qualcomm'], c: 1, e: 'Arm licenses its low-power chip designs widely.' },
  { d: 'hard', s: 'classic', q: 'The programming languages C and Unix were developed at which lab?', o: ['Bell Labs', 'IBM Research', 'Xerox PARC', 'MIT Media Lab'], c: 0, e: 'Bell Labs produced both C and Unix.' },

  // ===== SET B — INDIAN / AI / CULTURAL (35) =====
  // Easy (12)
  { d: 'easy', s: 'cultural', q: 'ChatGPT was released to the public in which month and year?', o: ['November 2022', 'January 2023', 'June 2021', 'March 2023'], c: 0, e: 'OpenAI launched ChatGPT in November 2022.' },
  { d: 'easy', s: 'cultural', q: 'The AI assistant "Claude" is made by which company?', o: ['OpenAI', 'Anthropic', 'Google', 'Meta'], c: 1, e: 'Anthropic develops the Claude models.' },
  { d: 'easy', s: 'cultural', q: 'What does "GPT" stand for?', o: ['General Purpose Tool', 'Generative Pre-trained Transformer', 'Global Processing Technology', 'Guided Prompt Trainer'], c: 1, e: 'GPT is a Generative Pre-trained Transformer.' },
  { d: 'easy', s: 'cultural', q: 'Apple\'s suite of AI features is branded as what?', o: ['Apple AI', 'Apple Intelligence', 'Siri Plus', 'iThink'], c: 1, e: 'Apple announced "Apple Intelligence" in 2024.' },
  { d: 'easy', s: 'cultural', q: 'Which Indian space mission successfully orbited Mars?', o: ['Chandrayaan-1', 'Mangalyaan', 'Aditya-L1', 'Gaganyaan'], c: 1, e: 'Mangalyaan (Mars Orbiter Mission) reached Mars in 2014.' },
  { d: 'easy', s: 'cultural', q: 'Which company owns Instagram and WhatsApp?', o: ['Google', 'Meta', 'Microsoft', 'ByteDance'], c: 1, e: 'Meta (formerly Facebook) owns both.' },
  { d: 'easy', s: 'cultural', q: 'India\'s instant digital payment system is known by which acronym?', o: ['NEFT', 'UPI', 'IMPS', 'RTGS'], c: 1, e: 'UPI (Unified Payments Interface) powers QR payments.' },
  { d: 'easy', s: 'cultural', q: 'Which company disrupted India\'s telecom market with cheap 4G in 2016?', o: ['Airtel', 'Reliance Jio', 'Vodafone', 'BSNL'], c: 1, e: 'Reliance Jio launched in 2016.' },
  { d: 'easy', s: 'cultural', q: 'ISRO is India\'s national agency for what?', o: ['Defense', 'Space research', 'Banking', 'Telecom'], c: 1, e: 'ISRO is the Indian Space Research Organisation.' },
  { d: 'easy', s: 'cultural', q: 'CRED and Zepto are examples of what kind of companies?', o: ['Oil firms', 'Indian startups (apps)', 'Banks', 'Airlines'], c: 1, e: 'They are popular Indian app-based startups.' },
  { d: 'easy', s: 'cultural', q: 'What does "OTP" mean in online transactions?', o: ['One Time Password', 'Online Transfer Protocol', 'Open Transaction Page', 'Official Transfer Pin'], c: 0, e: 'An OTP is a one-time verification code.' },
  { d: 'easy', s: 'cultural', q: 'Which Indian app is famous for "10-minute" grocery delivery?', o: ['Zepto', 'Ola', 'PhonePe', 'Myntra'], c: 0, e: 'Zepto popularized ultra-fast grocery delivery.' },
  // Medium (12)
  { d: 'medium', s: 'cultural', q: 'India\'s UPI payment system was developed by which body?', o: ['RBI', 'NPCI', 'SEBI', 'TRAI'], c: 1, e: 'The National Payments Corporation of India built UPI.' },
  { d: 'medium', s: 'cultural', q: 'Chandrayaan-3 successfully landed on the Moon in which year?', o: ['2019', '2021', '2023', '2024'], c: 2, e: 'India\'s Chandrayaan-3 landed in August 2023.' },
  { d: 'medium', s: 'cultural', q: 'ISRO is headquartered in which city?', o: ['Hyderabad', 'Bengaluru', 'Chennai', 'New Delhi'], c: 1, e: 'ISRO\'s headquarters are in Bengaluru.' },
  { d: 'medium', s: 'cultural', q: 'Which is India\'s largest IT services company?', o: ['Infosys', 'TCS', 'Wipro', 'HCL'], c: 1, e: 'Tata Consultancy Services (TCS) is the largest.' },
  { d: 'medium', s: 'cultural', q: 'Which US retail giant acquired Flipkart in 2018?', o: ['Amazon', 'Walmart', 'Target', 'eBay'], c: 1, e: 'Walmart bought a majority stake in Flipkart.' },
  { d: 'medium', s: 'cultural', q: 'Paytm was founded by whom?', o: ['Vijay Shekhar Sharma', 'Bhavish Aggarwal', 'Kunal Shah', 'Ritesh Agarwal'], c: 0, e: 'Vijay Shekhar Sharma founded Paytm.' },
  { d: 'medium', s: 'cultural', q: 'The "Digital India" government program was launched in which year?', o: ['2010', '2015', '2018', '2020'], c: 1, e: 'Digital India launched in 2015.' },
  { d: 'medium', s: 'cultural', q: 'Flipkart was co-founded by Sachin Bansal and which other Bansal?', o: ['Binny Bansal', 'Rohit Bansal', 'Kunal Bansal', 'Amit Bansal'], c: 0, e: 'Sachin and Binny Bansal (unrelated) founded Flipkart.' },
  { d: 'medium', s: 'cultural', q: 'India\'s biometric identity system is called what?', o: ['PAN', 'Aadhaar', 'Voter ID', 'Ration card'], c: 1, e: 'Aadhaar is the 12-digit unique identity.' },
  { d: 'medium', s: 'cultural', q: 'OpenAI\'s GPT-4 powers many products; OpenAI is based in which US city?', o: ['Seattle', 'San Francisco', 'Austin', 'Boston'], c: 1, e: 'OpenAI is headquartered in San Francisco.' },
  { d: 'medium', s: 'cultural', q: 'Which large language model family is developed by Anthropic?', o: ['Gemini', 'Claude', 'Llama', 'Mistral'], c: 1, e: 'Anthropic builds the Claude family of models.' },
  { d: 'medium', s: 'cultural', q: 'India\'s mission to study the Sun is named what?', o: ['Aditya-L1', 'Surya', 'Gaganyaan', 'Mangalyaan'], c: 0, e: 'Aditya-L1 observes the Sun from space.' },
  // Hard (11)
  { d: 'hard', s: 'cultural', q: 'ISRO\'s reliable workhorse rocket "PSLV" stands for what?', o: ['Polar Satellite Launch Vehicle', 'Primary Space Launch Vessel', 'Planetary Survey Launch Vehicle', 'Public Sector Launch Vehicle'], c: 0, e: 'PSLV is the Polar Satellite Launch Vehicle.' },
  { d: 'hard', s: 'cultural', q: 'India\'s Mars Orbiter Mission was notable for succeeding on which attempt?', o: ['Its third', 'Its first', 'Its second', 'Its fifth'], c: 1, e: 'India reached Mars orbit on its very first try.' },
  { d: 'hard', s: 'cultural', q: 'What was the name of India\'s first satellite, launched in 1975?', o: ['Bhaskara', 'Aryabhata', 'Rohini', 'INSAT'], c: 1, e: 'India\'s first satellite was named Aryabhata.' },
  { d: 'hard', s: 'cultural', q: 'Chandrayaan-3\'s lander was named what?', o: ['Pragyan', 'Vikram', 'Aryabhata', 'Bhaskar'], c: 1, e: 'The lander Vikram carried the rover Pragyan.' },
  { d: 'hard', s: 'cultural', q: 'Which Indian-born executive is the CEO of Google and Alphabet?', o: ['Satya Nadella', 'Sundar Pichai', 'Shantanu Narayen', 'Parag Agrawal'], c: 1, e: 'Sundar Pichai leads Google and Alphabet.' },
  { d: 'hard', s: 'cultural', q: 'Which Indian-born executive became CEO of Microsoft in 2014?', o: ['Sundar Pichai', 'Satya Nadella', 'Arvind Krishna', 'Shantanu Narayen'], c: 1, e: 'Satya Nadella has led Microsoft since 2014.' },
  { d: 'hard', s: 'cultural', q: 'Infosys was co-founded in 1981 by whom?', o: ['Azim Premji', 'N. R. Narayana Murthy', 'Shiv Nadar', 'Ratan Tata'], c: 1, e: 'Narayana Murthy co-founded Infosys.' },
  { d: 'hard', s: 'cultural', q: 'Anthropic, the maker of Claude, was founded by former staff of which company?', o: ['Google', 'OpenAI', 'Meta', 'Microsoft'], c: 1, e: 'Ex-OpenAI researchers founded Anthropic in 2021.' },
  { d: 'hard', s: 'cultural', q: 'India\'s TCS is part of which large business conglomerate?', o: ['Reliance', 'Tata Group', 'Adani Group', 'Birla Group'], c: 1, e: 'TCS belongs to the Tata Group.' },
  { d: 'hard', s: 'cultural', q: 'Mangalyaan was famously cheaper than which Hollywood film about space?', o: ['Interstellar', 'Gravity', 'The Martian', 'Apollo 13'], c: 1, e: 'India\'s Mars mission cost less than the film "Gravity".' },
  { d: 'hard', s: 'cultural', q: 'The UPI and Aadhaar systems are examples of India\'s what?', o: ['Private monopolies', 'Digital public infrastructure', 'Foreign imports', 'Defense projects'], c: 1, e: 'They form India\'s digital public infrastructure stack.' },
];
